mv -if data_el_2016_runC_v1/*/*/*/*/ReducedSelection_*.root	data_el_2016_runC_v1/
mv -if data_el_2016_runE_v1/*/*/*/*/ReducedSelection_*.root	data_el_2016_runE_v1/
mv -if data_el_2016_runF_v1/*/*/*/*/ReducedSelection_*.root	data_el_2016_runF_v1/
mv -if data_el_2016_runG_v1/*/*/*/*/ReducedSelection_*.root	data_el_2016_runG_v1/
mv -if data_el_2016_runH_v2/*/*/*/*/ReducedSelection_*.root	data_el_2016_runH_v2/
mv -if data_el_2016_runH_v3/*/*/*/*/ReducedSelection_*.root	data_el_2016_runH_v3/
mv -if data_mu_2016_runB_v3/*/*/*/*/ReducedSelection_*.root	data_mu_2016_runB_v3/
mv -if data_mu_2016_runD_v1/*/*/*/*/ReducedSelection_*.root	data_mu_2016_runD_v1/
mv -if data_mu_2016_runE_v1/*/*/*/*/ReducedSelection_*.root	data_mu_2016_runE_v1/
mv -if data_mu_2016_runF_v1/*/*/*/*/ReducedSelection_*.root	data_mu_2016_runF_v1/
mv -if data_mu_2016_runG_v1/*/*/*/*/ReducedSelection_*.root	data_mu_2016_runG_v1/
mv -if data_mu_2016_runH_v3/*/*/*/*/ReducedSelection_*.root	data_mu_2016_runH_v3/
mv -if DYJetsToLL_amcatnlo_ext1/*/*/*/*/ReducedSelection_*.root	DYJetsToLL_amcatnlo_ext1/
mv -if sch/*/*/*/*/ReducedSelection_*.root	sch/
mv -if Signal_LL/*/*/*/*/ReducedSelection_*.root	Signal_LL/
mv -if Signal_LT/*/*/*/*/ReducedSelection_*.root	Signal_LT/
mv -if Signal_TT/*/*/*/*/ReducedSelection_*.root	Signal_TT/
mv -if tch/*/*/*/*/ReducedSelection_*.root	tch/
mv -if tch_bar/*/*/*/*/ReducedSelection_*.root	tch_bar/
mv -if TTbar_amcatnlo/*/*/*/*/ReducedSelection_*.root	TTbar_amcatnlo/
mv -if TTbar_powheg/*/*/*/*/ReducedSelection_*.root	TTbar_powheg/
mv -if tWch/*/*/*/*/ReducedSelection_*.root	tWch/
mv -if tWch_bar/*/*/*/*/ReducedSelection_*.root	tWch_bar/
mv -if tWch_bar_ext1/*/*/*/*/ReducedSelection_*.root	tWch_bar_ext1/
mv -if tWch_ext1/*/*/*/*/ReducedSelection_*.root	tWch_ext1/
mv -if WJets100/*/*/*/*/ReducedSelection_*.root	WJets100/
mv -if WJets100ext1/*/*/*/*/ReducedSelection_*.root	WJets100ext1/
mv -if WJets100ext2/*/*/*/*/ReducedSelection_*.root	WJets100ext2/
mv -if WJets1200/*/*/*/*/ReducedSelection_*.root	WJets1200/
mv -if WJets1200ext1/*/*/*/*/ReducedSelection_*.root	WJets1200ext1/
mv -if WJets200/*/*/*/*/ReducedSelection_*.root	WJets200/
mv -if WJets200ext1/*/*/*/*/ReducedSelection_*.root	WJets200ext1/
mv -if WJets200ext2/*/*/*/*/ReducedSelection_*.root	WJets200ext2/
mv -if WJets2500/*/*/*/*/ReducedSelection_*.root	WJets2500/
mv -if WJets2500ext1/*/*/*/*/ReducedSelection_*.root	WJets2500ext1/
mv -if WJets400/*/*/*/*/ReducedSelection_*.root	WJets400/
mv -if WJets400ext1/*/*/*/*/ReducedSelection_*.root	WJets400ext1/
mv -if WJets600/*/*/*/*/ReducedSelection_*.root	WJets600/
mv -if WJets600ext1/*/*/*/*/ReducedSelection_*.root	WJets600ext1/
mv -if WJets800ext1/*/*/*/*/ReducedSelection_*.root	WJets800ext1/
mv -if WJets_amcatnlo/*/*/*/*/ReducedSelection_*.root	WJets_amcatnlo/
mv -if WJets_madgraph/*/*/*/*/ReducedSelection_*.root	WJets_madgraph/
mv -if WW_excl/*/*/*/*/ReducedSelection_*.root	WW_excl/
mv -if WW_excl_amcatnlo/*/*/*/*/ReducedSelection_*.root	WW_excl_amcatnlo/
mv -if WW_excl_ext1/*/*/*/*/ReducedSelection_*.root	WW_excl_ext1/
mv -if WZ_excl_amcatnlo/*/*/*/*/ReducedSelection_*.root	WZ_excl_amcatnlo/
mv -if ZZ_excl_amcatnlo/*/*/*/*/ReducedSelection_*.root	ZZ_excl_amcatnlo/
