//////////////////////////////////////////////////////////
// This class has been automatically generated on
// Wed Jun 21 15:06:48 2017 by ROOT version 6.06/01
// from TTree Events/Events
// found on file: root://eoscms.cern.ch//store/user/arapyan/Run2/WWJJToLNuQQ_LL_13TeV-madgraph-pythia8/Samples/170503_175516/0000/Output_19.root
//////////////////////////////////////////////////////////

#ifndef setInputTree_h
#define setInputTree_h

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>
#include <iostream>
#include <TTree.h>

// Header file for the classes stored in the TTree if any.
#include "TClonesArray.h"

#include "BaconAnaDefs.hh"

class setInputTree {
public :
   TChain          *fChain;   //!pointer to the analyzed TTree or TChain
   Int_t           fCurrent; //!current Tree number in a TChain
   unsigned int    fITrigger;


   // Declaration of leaf types
 //baconhep::TEventInfo *Info;
   UInt_t          runNum;
   UInt_t          evtNum;
   UInt_t          lumiSec;
   UInt_t          metFilterFailBits;
   UInt_t          nPU;
   UInt_t          nPUm;
   UInt_t          nPUp;
   Float_t         nPUmean;
   Float_t         nPUmeanm;
   Float_t         nPUmeanp;
   Float_t         pvx;
   Float_t         pvy;
   Float_t         pvz;
   Float_t         bsx;
   Float_t         bsy;
   Float_t         bsz;
   Float_t         caloMET;
   Float_t         caloMETphi;
   Float_t         pfMET;
   Float_t         pfMETphi;
   Float_t         pfMETCov00;
   Float_t         pfMETCov01;
   Float_t         pfMETCov11;
   Float_t         pfMETC;
   Float_t         pfMETCphi;
   Float_t         pfMETCCov00;
   Float_t         pfMETCCov01;
   Float_t         pfMETCCov11;
   Float_t         pfMETCjerup;
   Float_t         pfMETCjerdn;
   Float_t         pfMETCjenup;
   Float_t         pfMETCjendn;
   Float_t         pfMETCuncup;
   Float_t         pfMETCuncdn;
   Float_t         pfMETCjrsup;
   Float_t         pfMETCjrsdn;
   Float_t         pfMETCphijerup;
   Float_t         pfMETCphijerdn;
   Float_t         pfMETCphijenup;
   Float_t         pfMETCphijendn;
   Float_t         pfMETCphiuncup;
   Float_t         pfMETCphiuncdn;
   Float_t         pfMETCphijrsup;
   Float_t         pfMETCphijrsdn;
   Float_t         puppET;
   Float_t         puppETphi;
   Float_t         puppETCov00;
   Float_t         puppETCov01;
   Float_t         puppETCov11;
   Float_t         puppETC;
   Float_t         puppETCphi;
   Float_t         puppETCCov00;
   Float_t         puppETCCov01;
   Float_t         puppETCCov11;
   Float_t         alpacaMET;
   Float_t         alpacaMETphi;
   Float_t         pcpMET;
   Float_t         pcpMETphi;
   Float_t         trkMET;
   Float_t         trkMETphi;
   Float_t         rhoIso;
   Float_t         rhoJet;
   //TriggerBits	   triggerBits;	// fired trigger bits
 //bitset<256>     triggerBits;
   Bool_t          hasGoodPV;
 //baconhep::TGenEventInfo *GenEvtInfo;
   Int_t           id_1;
   Int_t           id_2;
   Float_t         x_1;
   Float_t         x_2;
   Float_t         scalePDF;
   Float_t         xs;
   Float_t         weight;
   Int_t           GenParticle_;
   Int_t           GenParticle_parent[108];   //[GenParticle_]
   Int_t           GenParticle_pdgId[108];   //[GenParticle_]
   Int_t           GenParticle_status[108];   //[GenParticle_]
   Float_t         GenParticle_pt[108];   //[GenParticle_]
   Float_t         GenParticle_eta[108];   //[GenParticle_]
   Float_t         GenParticle_phi[108];   //[GenParticle_]
   Float_t         GenParticle_mass[108];   //[GenParticle_]
   Float_t         GenParticle_y[108];   //[GenParticle_]
   Int_t           Electron_;
   Float_t         Electron_pt[5];   //[Electron_]
   Float_t         Electron_eta[5];   //[Electron_]
   Float_t         Electron_phi[5];   //[Electron_]
   Float_t         Electron_scEt[5];   //[Electron_]
   Float_t         Electron_scEta[5];   //[Electron_]
   Float_t         Electron_scPhi[5];   //[Electron_]
   Float_t         Electron_ecalEnergy[5];   //[Electron_]
   Float_t         Electron_pfPt[5];   //[Electron_]
   Float_t         Electron_pfEta[5];   //[Electron_]
   Float_t         Electron_pfPhi[5];   //[Electron_]
   Float_t         Electron_trkIso[5];   //[Electron_]
   Float_t         Electron_ecalIso[5];   //[Electron_]
   Float_t         Electron_hcalIso[5];   //[Electron_]
   Float_t         Electron_hcalDepth1Iso[5];   //[Electron_]
   Float_t         Electron_chHadIso[5];   //[Electron_]
   Float_t         Electron_gammaIso[5];   //[Electron_]
   Float_t         Electron_neuHadIso[5];   //[Electron_]
   Float_t         Electron_puIso[5];   //[Electron_]
   Float_t         Electron_ecalPFClusIso[5];   //[Electron_]
   Float_t         Electron_hcalPFClusIso[5];   //[Electron_]
   Float_t         Electron_puppiChHadIso[5];   //[Electron_]
   Float_t         Electron_puppiGammaIso[5];   //[Electron_]
   Float_t         Electron_puppiNeuHadIso[5];   //[Electron_]
   Float_t         Electron_puppiChHadIsoNoLep[5];   //[Electron_]
   Float_t         Electron_puppiGammaIsoNoLep[5];   //[Electron_]
   Float_t         Electron_puppiNeuHadIsoNoLep[5];   //[Electron_]
   Float_t         Electron_d0[5];   //[Electron_]
   Float_t         Electron_dz[5];   //[Electron_]
   Float_t         Electron_sip3d[5];   //[Electron_]
   Float_t         Electron_sieie[5];   //[Electron_]
   Float_t         Electron_e1x5[5];   //[Electron_]
   Float_t         Electron_e2x5[5];   //[Electron_]
   Float_t         Electron_e5x5[5];   //[Electron_]
   Float_t         Electron_r9[5];   //[Electron_]
   Float_t         Electron_eoverp[5];   //[Electron_]
   Float_t         Electron_hovere[5];   //[Electron_]
   Float_t         Electron_fbrem[5];   //[Electron_]
   Float_t         Electron_dEtaInSeed[5];   //[Electron_]
   Float_t         Electron_dEtaIn[5];   //[Electron_]
   Float_t         Electron_dPhiIn[5];   //[Electron_]
   Float_t         Electron_mva[5];   //[Electron_]
   Int_t           Electron_q[5];   //[Electron_]
   Bool_t          Electron_isConv[5];   //[Electron_]
   UInt_t          Electron_nMissingHits[5];   //[Electron_]
   UInt_t          Electron_typeBits[5];   //[Electron_]
   UInt_t          Electron_fiducialBits[5];   //[Electron_]
   Int_t           Electron_classification[5];   //[Electron_]
   Int_t           Electron_scID[5];   //[Electron_]
   Int_t           Electron_trkID[5];   //[Electron_]
 //bitset<256>     Electron_hltMatchBits[5];
   Int_t           Muon_;
   Float_t         Muon_pt[18];   //[Muon_]
   Float_t         Muon_eta[18];   //[Muon_]
   Float_t         Muon_phi[18];   //[Muon_]
   Float_t         Muon_ptErr[18];   //[Muon_]
   Float_t         Muon_staPt[18];   //[Muon_]
   Float_t         Muon_staEta[18];   //[Muon_]
   Float_t         Muon_staPhi[18];   //[Muon_]
   Float_t         Muon_pfPt[18];   //[Muon_]
   Float_t         Muon_pfEta[18];   //[Muon_]
   Float_t         Muon_pfPhi[18];   //[Muon_]
   Float_t         Muon_trkIso[18];   //[Muon_]
   Float_t         Muon_ecalIso[18];   //[Muon_]
   Float_t         Muon_hcalIso[18];   //[Muon_]
   Float_t         Muon_chHadIso[18];   //[Muon_]
   Float_t         Muon_gammaIso[18];   //[Muon_]
   Float_t         Muon_neuHadIso[18];   //[Muon_]
   Float_t         Muon_puIso[18];   //[Muon_]
   Float_t         Muon_puppiChHadIso[18];   //[Muon_]
   Float_t         Muon_puppiGammaIso[18];   //[Muon_]
   Float_t         Muon_puppiNeuHadIso[18];   //[Muon_]
   Float_t         Muon_puppiChHadIsoNoLep[18];   //[Muon_]
   Float_t         Muon_puppiGammaIsoNoLep[18];   //[Muon_]
   Float_t         Muon_puppiNeuHadIsoNoLep[18];   //[Muon_]
   Float_t         Muon_d0[18];   //[Muon_]
   Float_t         Muon_dz[18];   //[Muon_]
   Float_t         Muon_sip3d[18];   //[Muon_]
   Float_t         Muon_tkNchi2[18];   //[Muon_]
   Float_t         Muon_muNchi2[18];   //[Muon_]
   Float_t         Muon_trkKink[18];   //[Muon_]
   Float_t         Muon_glbKink[18];   //[Muon_]
   Float_t         Muon_trkHitFrac[18];   //[Muon_]
   Float_t         Muon_chi2LocPos[18];   //[Muon_]
   Float_t         Muon_segComp[18];   //[Muon_]
   Float_t         Muon_caloComp[18];   //[Muon_]
   Int_t           Muon_q[18];   //[Muon_]
   Int_t           Muon_nValidHits[18];   //[Muon_]
   UInt_t          Muon_typeBits[18];   //[Muon_]
   UInt_t          Muon_selectorBits[18];   //[Muon_]
   UInt_t          Muon_pogIDBits[18];   //[Muon_]
   UInt_t          Muon_nTkHits[18];   //[Muon_]
   UInt_t          Muon_nPixHits[18];   //[Muon_]
   UInt_t          Muon_nTkLayers[18];   //[Muon_]
   UInt_t          Muon_nPixLayers[18];   //[Muon_]
   UInt_t          Muon_nMatchStn[18];   //[Muon_]
   Int_t           Muon_trkID[18];   //[Muon_]
 //bitset<256>     Muon_hltMatchBits[18];
   Int_t           Tau_;
   Float_t         Tau_pt[9];   //[Tau_]
   Float_t         Tau_eta[9];   //[Tau_]
   Float_t         Tau_phi[9];   //[Tau_]
   Float_t         Tau_m[9];   //[Tau_]
   Float_t         Tau_e[9];   //[Tau_]
   Int_t           Tau_q[9];   //[Tau_]
   Float_t         Tau_dzLeadChHad[9];   //[Tau_]
   Float_t         Tau_d0LeadChHad[9];   //[Tau_]
   UInt_t          Tau_nSignalChHad[9];   //[Tau_]
   UInt_t          Tau_nSignalGamma[9];   //[Tau_]
   Int_t           Tau_decaymode[9];   //[Tau_]
   Float_t         Tau_antiEleMVA6[9];   //[Tau_]
   Float_t         Tau_antiEleMVA6Cat[9];   //[Tau_]
   Float_t         Tau_rawMuonRejection[9];   //[Tau_]
   Float_t         Tau_rawIso3Hits[9];   //[Tau_]
   Float_t         Tau_rawIsoMVA3oldDMwoLT[9];   //[Tau_]
   Float_t         Tau_rawIsoMVA3oldDMwLT[9];   //[Tau_]
   Float_t         Tau_rawIsoMVA3newDMwoLT[9];   //[Tau_]
   Float_t         Tau_rawIsoMVA3newDMwLT[9];   //[Tau_]
   Float_t         Tau_puppiChHadIso[9];   //[Tau_]
   Float_t         Tau_puppiGammaIso[9];   //[Tau_]
   Float_t         Tau_puppiNeuHadIso[9];   //[Tau_]
   Float_t         Tau_puppiChHadIsoNoLep[9];   //[Tau_]
   Float_t         Tau_puppiGammaIsoNoLep[9];   //[Tau_]
   Float_t         Tau_puppiNeuHadIsoNoLep[9];   //[Tau_]
   ULong_t         Tau_hpsDisc[9];   //[Tau_]
 //bitset<256>     Tau_hltMatchBits[9];
   Int_t           Photon_;
   Float_t         Photon_pt[8];   //[Photon_]
   Float_t         Photon_eta[8];   //[Photon_]
   Float_t         Photon_phi[8];   //[Photon_]
   Float_t         Photon_scEt[8];   //[Photon_]
   Float_t         Photon_scEta[8];   //[Photon_]
   Float_t         Photon_scPhi[8];   //[Photon_]
   Float_t         Photon_trkIso[8];   //[Photon_]
   Float_t         Photon_ecalIso[8];   //[Photon_]
   Float_t         Photon_hcalIso[8];   //[Photon_]
   Float_t         Photon_chHadIso[8];   //[Photon_]
   Float_t         Photon_gammaIso[8];   //[Photon_]
   Float_t         Photon_neuHadIso[8];   //[Photon_]
   Float_t         Photon_mva[8];   //[Photon_]
   Float_t         Photon_hovere[8];   //[Photon_]
   Float_t         Photon_sthovere[8];   //[Photon_]
   Float_t         Photon_sieie[8];   //[Photon_]
   Float_t         Photon_sipip[8];   //[Photon_]
   Float_t         Photon_r9[8];   //[Photon_]
   UInt_t          Photon_fiducialBits[8];   //[Photon_]
   UInt_t          Photon_typeBits[8];   //[Photon_]
   Int_t           Photon_scID[8];   //[Photon_]
   Bool_t          Photon_hasPixelSeed[8];   //[Photon_]
   Bool_t          Photon_passElectronVeto[8];   //[Photon_]
   Bool_t          Photon_isConv[8];   //[Photon_]
 //bitset<256>     Photon_hltMatchBits[8];
   Int_t           PV_;
   UInt_t          PV_nTracksFit[84];   //[PV_]
   Float_t         PV_ndof[84];   //[PV_]
   Float_t         PV_chi2[84];   //[PV_]
   Float_t         PV_x[84];   //[PV_]
   Float_t         PV_y[84];   //[PV_]
   Float_t         PV_z[84];   //[PV_]
   Int_t           AK4CHS_;
   Float_t         AK4CHS_pt[17];   //[AK4CHS_]
   Float_t         AK4CHS_eta[17];   //[AK4CHS_]
   Float_t         AK4CHS_phi[17];   //[AK4CHS_]
   Float_t         AK4CHS_mass[17];   //[AK4CHS_]
   Float_t         AK4CHS_ptRaw[17];   //[AK4CHS_]
   Float_t         AK4CHS_unc[17];   //[AK4CHS_]
   Float_t         AK4CHS_area[17];   //[AK4CHS_]
   Float_t         AK4CHS_d0[17];   //[AK4CHS_]
   Float_t         AK4CHS_dz[17];   //[AK4CHS_]
   Float_t         AK4CHS_csv[17];   //[AK4CHS_]
   Float_t         AK4CHS_bmva[17];   //[AK4CHS_]
   Float_t         AK4CHS_cvb[17];   //[AK4CHS_]
   Float_t         AK4CHS_cvl[17];   //[AK4CHS_]
   Float_t         AK4CHS_qgid[17];   //[AK4CHS_]
   Float_t         AK4CHS_axis2[17];   //[AK4CHS_]
   Float_t         AK4CHS_ptD[17];   //[AK4CHS_]
   Int_t           AK4CHS_mult[17];   //[AK4CHS_]
   Float_t         AK4CHS_q[17];   //[AK4CHS_]
   Float_t         AK4CHS_mva[17];   //[AK4CHS_]
   Float_t         AK4CHS_beta[17];   //[AK4CHS_]
   Float_t         AK4CHS_betaStar[17];   //[AK4CHS_]
   Float_t         AK4CHS_dR2Mean[17];   //[AK4CHS_]
   Float_t         AK4CHS_pullY[17];   //[AK4CHS_]
   Float_t         AK4CHS_pullPhi[17];   //[AK4CHS_]
   Float_t         AK4CHS_chPullY[17];   //[AK4CHS_]
   Float_t         AK4CHS_chPullPhi[17];   //[AK4CHS_]
   Float_t         AK4CHS_neuPullY[17];   //[AK4CHS_]
   Float_t         AK4CHS_neuPullPhi[17];   //[AK4CHS_]
   Float_t         AK4CHS_chEmFrac[17];   //[AK4CHS_]
   Float_t         AK4CHS_neuEmFrac[17];   //[AK4CHS_]
   Float_t         AK4CHS_chHadFrac[17];   //[AK4CHS_]
   Float_t         AK4CHS_neuHadFrac[17];   //[AK4CHS_]
   Float_t         AK4CHS_muonFrac[17];   //[AK4CHS_]
   Float_t         AK4CHS_genpt[17];   //[AK4CHS_]
   Float_t         AK4CHS_geneta[17];   //[AK4CHS_]
   Float_t         AK4CHS_genphi[17];   //[AK4CHS_]
   Float_t         AK4CHS_genm[17];   //[AK4CHS_]
   Int_t           AK4CHS_partonFlavor[17];   //[AK4CHS_]
   Int_t           AK4CHS_hadronFlavor[17];   //[AK4CHS_]
   UInt_t          AK4CHS_nCharged[17];   //[AK4CHS_]
   UInt_t          AK4CHS_nNeutrals[17];   //[AK4CHS_]
   UInt_t          AK4CHS_nParticles[17];   //[AK4CHS_]
 //bitset<256>     AK4CHS_hltMatchBits[17];
   Int_t           AK8CHS_;
   Float_t         AK8CHS_pt[5];   //[AK8CHS_]
   Float_t         AK8CHS_eta[5];   //[AK8CHS_]
   Float_t         AK8CHS_phi[5];   //[AK8CHS_]
   Float_t         AK8CHS_mass[5];   //[AK8CHS_]
   Float_t         AK8CHS_ptRaw[5];   //[AK8CHS_]
   Float_t         AK8CHS_unc[5];   //[AK8CHS_]
   Float_t         AK8CHS_area[5];   //[AK8CHS_]
   Float_t         AK8CHS_d0[5];   //[AK8CHS_]
   Float_t         AK8CHS_dz[5];   //[AK8CHS_]
   Float_t         AK8CHS_csv[5];   //[AK8CHS_]
   Float_t         AK8CHS_bmva[5];   //[AK8CHS_]
   Float_t         AK8CHS_cvb[5];   //[AK8CHS_]
   Float_t         AK8CHS_cvl[5];   //[AK8CHS_]
   Float_t         AK8CHS_qgid[5];   //[AK8CHS_]
   Float_t         AK8CHS_axis2[5];   //[AK8CHS_]
   Float_t         AK8CHS_ptD[5];   //[AK8CHS_]
   Int_t           AK8CHS_mult[5];   //[AK8CHS_]
   Float_t         AK8CHS_q[5];   //[AK8CHS_]
   Float_t         AK8CHS_mva[5];   //[AK8CHS_]
   Float_t         AK8CHS_beta[5];   //[AK8CHS_]
   Float_t         AK8CHS_betaStar[5];   //[AK8CHS_]
   Float_t         AK8CHS_dR2Mean[5];   //[AK8CHS_]
   Float_t         AK8CHS_pullY[5];   //[AK8CHS_]
   Float_t         AK8CHS_pullPhi[5];   //[AK8CHS_]
   Float_t         AK8CHS_chPullY[5];   //[AK8CHS_]
   Float_t         AK8CHS_chPullPhi[5];   //[AK8CHS_]
   Float_t         AK8CHS_neuPullY[5];   //[AK8CHS_]
   Float_t         AK8CHS_neuPullPhi[5];   //[AK8CHS_]
   Float_t         AK8CHS_chEmFrac[5];   //[AK8CHS_]
   Float_t         AK8CHS_neuEmFrac[5];   //[AK8CHS_]
   Float_t         AK8CHS_chHadFrac[5];   //[AK8CHS_]
   Float_t         AK8CHS_neuHadFrac[5];   //[AK8CHS_]
   Float_t         AK8CHS_muonFrac[5];   //[AK8CHS_]
   Float_t         AK8CHS_genpt[5];   //[AK8CHS_]
   Float_t         AK8CHS_geneta[5];   //[AK8CHS_]
   Float_t         AK8CHS_genphi[5];   //[AK8CHS_]
   Float_t         AK8CHS_genm[5];   //[AK8CHS_]
   Int_t           AK8CHS_partonFlavor[5];   //[AK8CHS_]
   Int_t           AK8CHS_hadronFlavor[5];   //[AK8CHS_]
   UInt_t          AK8CHS_nCharged[5];   //[AK8CHS_]
   UInt_t          AK8CHS_nNeutrals[5];   //[AK8CHS_]
   UInt_t          AK8CHS_nParticles[5];   //[AK8CHS_]
 //bitset<256>     AK8CHS_hltMatchBits[5];
   Int_t           AddAK8CHS_;
   UInt_t          AddAK8CHS_index[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_mass_prun[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_mass_trim[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_mass_sd0[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_c2_0[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_c2_0P2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_c2_0P5[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_c2_1P0[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_c2_2P0[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e2_b1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_b1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_v1_b1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_v2_b1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e4_v1_b1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e4_v2_b1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e2_b2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_b2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_v1_b2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_v2_b2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e4_v1_b2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e4_v2_b2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e2_sdb1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_sdb1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_v1_sdb1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_v2_sdb1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e4_v1_sdb1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e4_v2_sdb1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e2_sdb2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_sdb2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_v1_sdb2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e3_v2_sdb2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e4_v1_sdb2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_e4_v2_sdb2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_qjet[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_tau1[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_tau2[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_tau3[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_tau4[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_doublecsv[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_Double_sub[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj1_pt[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj1_eta[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj1_phi[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj1_m[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj1_csv[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj1_qgid[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj1_q[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj2_pt[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj2_eta[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj2_phi[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj2_m[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj2_csv[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj2_qgid[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj2_q[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj3_pt[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj3_eta[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj3_phi[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj3_m[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj3_csv[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj3_qgid[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj3_q[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj4_pt[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj4_eta[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj4_phi[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj4_m[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj4_csv[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj4_qgid[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_sj4_q[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_pullAngle[5];   //[AddAK8CHS_]
   UInt_t          AddAK8CHS_topTagType[5];   //[AddAK8CHS_]
   UInt_t          AddAK8CHS_top_n_subjets[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_top_m_min[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_top_m_123[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_top_fRec[5];   //[AddAK8CHS_]
   Float_t         AddAK8CHS_topchi2[5];   //[AddAK8CHS_]
   Int_t           CA15CHS_;
   Float_t         CA15CHS_pt[13];   //[CA15CHS_]
   Float_t         CA15CHS_eta[13];   //[CA15CHS_]
   Float_t         CA15CHS_phi[13];   //[CA15CHS_]
   Float_t         CA15CHS_mass[13];   //[CA15CHS_]
   Float_t         CA15CHS_ptRaw[13];   //[CA15CHS_]
   Float_t         CA15CHS_unc[13];   //[CA15CHS_]
   Float_t         CA15CHS_area[13];   //[CA15CHS_]
   Float_t         CA15CHS_d0[13];   //[CA15CHS_]
   Float_t         CA15CHS_dz[13];   //[CA15CHS_]
   Float_t         CA15CHS_csv[13];   //[CA15CHS_]
   Float_t         CA15CHS_bmva[13];   //[CA15CHS_]
   Float_t         CA15CHS_cvb[13];   //[CA15CHS_]
   Float_t         CA15CHS_cvl[13];   //[CA15CHS_]
   Float_t         CA15CHS_qgid[13];   //[CA15CHS_]
   Float_t         CA15CHS_axis2[13];   //[CA15CHS_]
   Float_t         CA15CHS_ptD[13];   //[CA15CHS_]
   Int_t           CA15CHS_mult[13];   //[CA15CHS_]
   Float_t         CA15CHS_q[13];   //[CA15CHS_]
   Float_t         CA15CHS_mva[13];   //[CA15CHS_]
   Float_t         CA15CHS_beta[13];   //[CA15CHS_]
   Float_t         CA15CHS_betaStar[13];   //[CA15CHS_]
   Float_t         CA15CHS_dR2Mean[13];   //[CA15CHS_]
   Float_t         CA15CHS_pullY[13];   //[CA15CHS_]
   Float_t         CA15CHS_pullPhi[13];   //[CA15CHS_]
   Float_t         CA15CHS_chPullY[13];   //[CA15CHS_]
   Float_t         CA15CHS_chPullPhi[13];   //[CA15CHS_]
   Float_t         CA15CHS_neuPullY[13];   //[CA15CHS_]
   Float_t         CA15CHS_neuPullPhi[13];   //[CA15CHS_]
   Float_t         CA15CHS_chEmFrac[13];   //[CA15CHS_]
   Float_t         CA15CHS_neuEmFrac[13];   //[CA15CHS_]
   Float_t         CA15CHS_chHadFrac[13];   //[CA15CHS_]
   Float_t         CA15CHS_neuHadFrac[13];   //[CA15CHS_]
   Float_t         CA15CHS_muonFrac[13];   //[CA15CHS_]
   Float_t         CA15CHS_genpt[13];   //[CA15CHS_]
   Float_t         CA15CHS_geneta[13];   //[CA15CHS_]
   Float_t         CA15CHS_genphi[13];   //[CA15CHS_]
   Float_t         CA15CHS_genm[13];   //[CA15CHS_]
   Int_t           CA15CHS_partonFlavor[13];   //[CA15CHS_]
   Int_t           CA15CHS_hadronFlavor[13];   //[CA15CHS_]
   UInt_t          CA15CHS_nCharged[13];   //[CA15CHS_]
   UInt_t          CA15CHS_nNeutrals[13];   //[CA15CHS_]
   UInt_t          CA15CHS_nParticles[13];   //[CA15CHS_]
 //bitset<256>     CA15CHS_hltMatchBits[13];
   Int_t           AddCA15CHS_;
   UInt_t          AddCA15CHS_index[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_mass_prun[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_mass_trim[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_mass_sd0[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_c2_0[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_c2_0P2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_c2_0P5[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_c2_1P0[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_c2_2P0[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e2_b1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_b1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_v1_b1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_v2_b1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e4_v1_b1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e4_v2_b1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e2_b2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_b2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_v1_b2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_v2_b2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e4_v1_b2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e4_v2_b2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e2_sdb1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_sdb1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_v1_sdb1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_v2_sdb1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e4_v1_sdb1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e4_v2_sdb1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e2_sdb2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_sdb2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_v1_sdb2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e3_v2_sdb2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e4_v1_sdb2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_e4_v2_sdb2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_qjet[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_tau1[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_tau2[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_tau3[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_tau4[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_doublecsv[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_Double_sub[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj1_pt[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj1_eta[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj1_phi[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj1_m[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj1_csv[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj1_qgid[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj1_q[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj2_pt[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj2_eta[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj2_phi[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj2_m[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj2_csv[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj2_qgid[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj2_q[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj3_pt[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj3_eta[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj3_phi[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj3_m[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj3_csv[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj3_qgid[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj3_q[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj4_pt[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj4_eta[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj4_phi[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj4_m[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj4_csv[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj4_qgid[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_sj4_q[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_pullAngle[13];   //[AddCA15CHS_]
   UInt_t          AddCA15CHS_topTagType[13];   //[AddCA15CHS_]
   UInt_t          AddCA15CHS_top_n_subjets[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_top_m_min[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_top_m_123[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_top_fRec[13];   //[AddCA15CHS_]
   Float_t         AddCA15CHS_topchi2[13];   //[AddCA15CHS_]
   Int_t           AK4Puppi_;
   Float_t         AK4Puppi_pt[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_eta[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_phi[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_mass[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_ptRaw[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_unc[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_area[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_d0[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_dz[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_csv[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_bmva[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_cvb[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_cvl[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_qgid[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_axis2[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_ptD[12];   //[AK4Puppi_]
   Int_t           AK4Puppi_mult[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_q[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_mva[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_beta[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_betaStar[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_dR2Mean[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_pullY[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_pullPhi[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_chPullY[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_chPullPhi[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_neuPullY[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_neuPullPhi[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_chEmFrac[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_neuEmFrac[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_chHadFrac[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_neuHadFrac[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_muonFrac[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_genpt[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_geneta[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_genphi[12];   //[AK4Puppi_]
   Float_t         AK4Puppi_genm[12];   //[AK4Puppi_]
   Int_t           AK4Puppi_partonFlavor[12];   //[AK4Puppi_]
   Int_t           AK4Puppi_hadronFlavor[12];   //[AK4Puppi_]
   UInt_t          AK4Puppi_nCharged[12];   //[AK4Puppi_]
   UInt_t          AK4Puppi_nNeutrals[12];   //[AK4Puppi_]
   UInt_t          AK4Puppi_nParticles[12];   //[AK4Puppi_]
 //bitset<256>     AK4Puppi_hltMatchBits[12];
   Int_t           AK8Puppi_;
   Float_t         AK8Puppi_pt[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_eta[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_phi[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_mass[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_ptRaw[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_unc[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_area[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_d0[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_dz[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_csv[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_bmva[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_cvb[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_cvl[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_qgid[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_axis2[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_ptD[4];   //[AK8Puppi_]
   Int_t           AK8Puppi_mult[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_q[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_mva[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_beta[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_betaStar[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_dR2Mean[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_pullY[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_pullPhi[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_chPullY[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_chPullPhi[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_neuPullY[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_neuPullPhi[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_chEmFrac[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_neuEmFrac[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_chHadFrac[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_neuHadFrac[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_muonFrac[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_genpt[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_geneta[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_genphi[4];   //[AK8Puppi_]
   Float_t         AK8Puppi_genm[4];   //[AK8Puppi_]
   Int_t           AK8Puppi_partonFlavor[4];   //[AK8Puppi_]
   Int_t           AK8Puppi_hadronFlavor[4];   //[AK8Puppi_]
   UInt_t          AK8Puppi_nCharged[4];   //[AK8Puppi_]
   UInt_t          AK8Puppi_nNeutrals[4];   //[AK8Puppi_]
   UInt_t          AK8Puppi_nParticles[4];   //[AK8Puppi_]
 //bitset<256>     AK8Puppi_hltMatchBits[4];
   Int_t           AddAK8Puppi_;
   UInt_t          AddAK8Puppi_index[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_mass_prun[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_mass_trim[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_mass_sd0[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_c2_0[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_c2_0P2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_c2_0P5[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_c2_1P0[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_c2_2P0[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e2_b1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_b1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_v1_b1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_v2_b1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e4_v1_b1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e4_v2_b1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e2_b2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_b2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_v1_b2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_v2_b2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e4_v1_b2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e4_v2_b2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e2_sdb1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_sdb1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_v1_sdb1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_v2_sdb1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e4_v1_sdb1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e4_v2_sdb1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e2_sdb2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_sdb2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_v1_sdb2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e3_v2_sdb2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e4_v1_sdb2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_e4_v2_sdb2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_qjet[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_tau1[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_tau2[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_tau3[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_tau4[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_doublecsv[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_Double_sub[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj1_pt[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj1_eta[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj1_phi[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj1_m[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj1_csv[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj1_qgid[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj1_q[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj2_pt[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj2_eta[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj2_phi[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj2_m[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj2_csv[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj2_qgid[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj2_q[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj3_pt[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj3_eta[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj3_phi[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj3_m[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj3_csv[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj3_qgid[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj3_q[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj4_pt[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj4_eta[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj4_phi[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj4_m[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj4_csv[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj4_qgid[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_sj4_q[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_pullAngle[4];   //[AddAK8Puppi_]
   UInt_t          AddAK8Puppi_topTagType[4];   //[AddAK8Puppi_]
   UInt_t          AddAK8Puppi_top_n_subjets[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_top_m_min[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_top_m_123[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_top_fRec[4];   //[AddAK8Puppi_]
   Float_t         AddAK8Puppi_topchi2[4];   //[AddAK8Puppi_]
   Int_t           CA15Puppi_;
   Float_t         CA15Puppi_pt[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_eta[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_phi[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_mass[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_ptRaw[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_unc[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_area[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_d0[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_dz[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_csv[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_bmva[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_cvb[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_cvl[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_qgid[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_axis2[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_ptD[4];   //[CA15Puppi_]
   Int_t           CA15Puppi_mult[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_q[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_mva[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_beta[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_betaStar[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_dR2Mean[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_pullY[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_pullPhi[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_chPullY[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_chPullPhi[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_neuPullY[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_neuPullPhi[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_chEmFrac[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_neuEmFrac[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_chHadFrac[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_neuHadFrac[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_muonFrac[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_genpt[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_geneta[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_genphi[4];   //[CA15Puppi_]
   Float_t         CA15Puppi_genm[4];   //[CA15Puppi_]
   Int_t           CA15Puppi_partonFlavor[4];   //[CA15Puppi_]
   Int_t           CA15Puppi_hadronFlavor[4];   //[CA15Puppi_]
   UInt_t          CA15Puppi_nCharged[4];   //[CA15Puppi_]
   UInt_t          CA15Puppi_nNeutrals[4];   //[CA15Puppi_]
   UInt_t          CA15Puppi_nParticles[4];   //[CA15Puppi_]
 //bitset<256>     CA15Puppi_hltMatchBits[4];
   Int_t           AddCA15Puppi_;
   UInt_t          AddCA15Puppi_index[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_mass_prun[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_mass_trim[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_mass_sd0[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_c2_0[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_c2_0P2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_c2_0P5[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_c2_1P0[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_c2_2P0[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e2_b1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_b1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_v1_b1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_v2_b1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e4_v1_b1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e4_v2_b1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e2_b2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_b2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_v1_b2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_v2_b2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e4_v1_b2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e4_v2_b2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e2_sdb1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_sdb1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_v1_sdb1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_v2_sdb1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e4_v1_sdb1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e4_v2_sdb1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e2_sdb2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_sdb2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_v1_sdb2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e3_v2_sdb2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e4_v1_sdb2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_e4_v2_sdb2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_qjet[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_tau1[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_tau2[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_tau3[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_tau4[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_doublecsv[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_Double_sub[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj1_pt[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj1_eta[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj1_phi[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj1_m[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj1_csv[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj1_qgid[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj1_q[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj2_pt[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj2_eta[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj2_phi[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj2_m[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj2_csv[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj2_qgid[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj2_q[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj3_pt[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj3_eta[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj3_phi[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj3_m[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj3_csv[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj3_qgid[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj3_q[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj4_pt[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj4_eta[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj4_phi[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj4_m[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj4_csv[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj4_qgid[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_sj4_q[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_pullAngle[4];   //[AddCA15Puppi_]
   UInt_t          AddCA15Puppi_topTagType[4];   //[AddCA15Puppi_]
   UInt_t          AddCA15Puppi_top_n_subjets[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_top_m_min[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_top_m_123[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_top_fRec[4];   //[AddCA15Puppi_]
   Float_t         AddCA15Puppi_topchi2[4];   //[AddCA15Puppi_]

   // List of branches
   TBranch        *b_Info_runNum;   //!
   TBranch        *b_Info_evtNum;   //!
   TBranch        *b_Info_lumiSec;   //!
   TBranch        *b_Info_metFilterFailBits;   //!
   TBranch        *b_Info_nPU;   //!
   TBranch        *b_Info_nPUm;   //!
   TBranch        *b_Info_nPUp;   //!
   TBranch        *b_Info_nPUmean;   //!
   TBranch        *b_Info_nPUmeanm;   //!
   TBranch        *b_Info_nPUmeanp;   //!
   TBranch        *b_Info_pvx;   //!
   TBranch        *b_Info_pvy;   //!
   TBranch        *b_Info_pvz;   //!
   TBranch        *b_Info_bsx;   //!
   TBranch        *b_Info_bsy;   //!
   TBranch        *b_Info_bsz;   //!
   TBranch        *b_Info_caloMET;   //!
   TBranch        *b_Info_caloMETphi;   //!
   TBranch        *b_Info_pfMET;   //!
   TBranch        *b_Info_pfMETphi;   //!
   TBranch        *b_Info_pfMETCov00;   //!
   TBranch        *b_Info_pfMETCov01;   //!
   TBranch        *b_Info_pfMETCov11;   //!
   TBranch        *b_Info_pfMETC;   //!
   TBranch        *b_Info_pfMETCphi;   //!
   TBranch        *b_Info_pfMETCCov00;   //!
   TBranch        *b_Info_pfMETCCov01;   //!
   TBranch        *b_Info_pfMETCCov11;   //!
   TBranch        *b_Info_pfMETCjerup;   //!
   TBranch        *b_Info_pfMETCjerdn;   //!
   TBranch        *b_Info_pfMETCjenup;   //!
   TBranch        *b_Info_pfMETCjendn;   //!
   TBranch        *b_Info_pfMETCuncup;   //!
   TBranch        *b_Info_pfMETCuncdn;   //!
   TBranch        *b_Info_pfMETCjrsup;   //!
   TBranch        *b_Info_pfMETCjrsdn;   //!
   TBranch        *b_Info_pfMETCphijerup;   //!
   TBranch        *b_Info_pfMETCphijerdn;   //!
   TBranch        *b_Info_pfMETCphijenup;   //!
   TBranch        *b_Info_pfMETCphijendn;   //!
   TBranch        *b_Info_pfMETCphiuncup;   //!
   TBranch        *b_Info_pfMETCphiuncdn;   //!
   TBranch        *b_Info_pfMETCphijrsup;   //!
   TBranch        *b_Info_pfMETCphijrsdn;   //!
   TBranch        *b_Info_puppET;   //!
   TBranch        *b_Info_puppETphi;   //!
   TBranch        *b_Info_puppETCov00;   //!
   TBranch        *b_Info_puppETCov01;   //!
   TBranch        *b_Info_puppETCov11;   //!
   TBranch        *b_Info_puppETC;   //!
   TBranch        *b_Info_puppETCphi;   //!
   TBranch        *b_Info_puppETCCov00;   //!
   TBranch        *b_Info_puppETCCov01;   //!
   TBranch        *b_Info_puppETCCov11;   //!
   TBranch        *b_Info_alpacaMET;   //!
   TBranch        *b_Info_alpacaMETphi;   //!
   TBranch        *b_Info_pcpMET;   //!
   TBranch        *b_Info_pcpMETphi;   //!
   TBranch        *b_Info_trkMET;   //!
   TBranch        *b_Info_trkMETphi;   //!
   TBranch        *b_Info_rhoIso;   //!
   TBranch        *b_Info_rhoJet;   //!
   //TBranch	  *b_Info_triggerBits;
   TBranch        *b_Info_hasGoodPV;   //!
   TBranch        *b_GenEvtInfo_id_1;   //!
   TBranch        *b_GenEvtInfo_id_2;   //!
   TBranch        *b_GenEvtInfo_x_1;   //!
   TBranch        *b_GenEvtInfo_x_2;   //!
   TBranch        *b_GenEvtInfo_scalePDF;   //!
   TBranch        *b_GenEvtInfo_xs;   //!
   TBranch        *b_GenEvtInfo_weight;   //!
   TBranch        *b_GenParticle_;   //!
   TBranch        *b_GenParticle_parent;   //!
   TBranch        *b_GenParticle_pdgId;   //!
   TBranch        *b_GenParticle_status;   //!
   TBranch        *b_GenParticle_pt;   //!
   TBranch        *b_GenParticle_eta;   //!
   TBranch        *b_GenParticle_phi;   //!
   TBranch        *b_GenParticle_mass;   //!
   TBranch        *b_GenParticle_y;   //!
   TBranch        *b_Electron_;   //!
   TBranch        *b_Electron_pt;   //!
   TBranch        *b_Electron_eta;   //!
   TBranch        *b_Electron_phi;   //!
   TBranch        *b_Electron_scEt;   //!
   TBranch        *b_Electron_scEta;   //!
   TBranch        *b_Electron_scPhi;   //!
   TBranch        *b_Electron_ecalEnergy;   //!
   TBranch        *b_Electron_pfPt;   //!
   TBranch        *b_Electron_pfEta;   //!
   TBranch        *b_Electron_pfPhi;   //!
   TBranch        *b_Electron_trkIso;   //!
   TBranch        *b_Electron_ecalIso;   //!
   TBranch        *b_Electron_hcalIso;   //!
   TBranch        *b_Electron_hcalDepth1Iso;   //!
   TBranch        *b_Electron_chHadIso;   //!
   TBranch        *b_Electron_gammaIso;   //!
   TBranch        *b_Electron_neuHadIso;   //!
   TBranch        *b_Electron_puIso;   //!
   TBranch        *b_Electron_ecalPFClusIso;   //!
   TBranch        *b_Electron_hcalPFClusIso;   //!
   TBranch        *b_Electron_puppiChHadIso;   //!
   TBranch        *b_Electron_puppiGammaIso;   //!
   TBranch        *b_Electron_puppiNeuHadIso;   //!
   TBranch        *b_Electron_puppiChHadIsoNoLep;   //!
   TBranch        *b_Electron_puppiGammaIsoNoLep;   //!
   TBranch        *b_Electron_puppiNeuHadIsoNoLep;   //!
   TBranch        *b_Electron_d0;   //!
   TBranch        *b_Electron_dz;   //!
   TBranch        *b_Electron_sip3d;   //!
   TBranch        *b_Electron_sieie;   //!
   TBranch        *b_Electron_e1x5;   //!
   TBranch        *b_Electron_e2x5;   //!
   TBranch        *b_Electron_e5x5;   //!
   TBranch        *b_Electron_r9;   //!
   TBranch        *b_Electron_eoverp;   //!
   TBranch        *b_Electron_hovere;   //!
   TBranch        *b_Electron_fbrem;   //!
   TBranch        *b_Electron_dEtaInSeed;   //!
   TBranch        *b_Electron_dEtaIn;   //!
   TBranch        *b_Electron_dPhiIn;   //!
   TBranch        *b_Electron_mva;   //!
   TBranch        *b_Electron_q;   //!
   TBranch        *b_Electron_isConv;   //!
   TBranch        *b_Electron_nMissingHits;   //!
   TBranch        *b_Electron_typeBits;   //!
   TBranch        *b_Electron_fiducialBits;   //!
   TBranch        *b_Electron_classification;   //!
   TBranch        *b_Electron_scID;   //!
   TBranch        *b_Electron_trkID;   //!
   TBranch        *b_Muon_;   //!
   TBranch        *b_Muon_pt;   //!
   TBranch        *b_Muon_eta;   //!
   TBranch        *b_Muon_phi;   //!
   TBranch        *b_Muon_ptErr;   //!
   TBranch        *b_Muon_staPt;   //!
   TBranch        *b_Muon_staEta;   //!
   TBranch        *b_Muon_staPhi;   //!
   TBranch        *b_Muon_pfPt;   //!
   TBranch        *b_Muon_pfEta;   //!
   TBranch        *b_Muon_pfPhi;   //!
   TBranch        *b_Muon_trkIso;   //!
   TBranch        *b_Muon_ecalIso;   //!
   TBranch        *b_Muon_hcalIso;   //!
   TBranch        *b_Muon_chHadIso;   //!
   TBranch        *b_Muon_gammaIso;   //!
   TBranch        *b_Muon_neuHadIso;   //!
   TBranch        *b_Muon_puIso;   //!
   TBranch        *b_Muon_puppiChHadIso;   //!
   TBranch        *b_Muon_puppiGammaIso;   //!
   TBranch        *b_Muon_puppiNeuHadIso;   //!
   TBranch        *b_Muon_puppiChHadIsoNoLep;   //!
   TBranch        *b_Muon_puppiGammaIsoNoLep;   //!
   TBranch        *b_Muon_puppiNeuHadIsoNoLep;   //!
   TBranch        *b_Muon_d0;   //!
   TBranch        *b_Muon_dz;   //!
   TBranch        *b_Muon_sip3d;   //!
   TBranch        *b_Muon_tkNchi2;   //!
   TBranch        *b_Muon_muNchi2;   //!
   TBranch        *b_Muon_trkKink;   //!
   TBranch        *b_Muon_glbKink;   //!
   TBranch        *b_Muon_trkHitFrac;   //!
   TBranch        *b_Muon_chi2LocPos;   //!
   TBranch        *b_Muon_segComp;   //!
   TBranch        *b_Muon_caloComp;   //!
   TBranch        *b_Muon_q;   //!
   TBranch        *b_Muon_nValidHits;   //!
   TBranch        *b_Muon_typeBits;   //!
   TBranch        *b_Muon_selectorBits;   //!
   TBranch        *b_Muon_pogIDBits;   //!
   TBranch        *b_Muon_nTkHits;   //!
   TBranch        *b_Muon_nPixHits;   //!
   TBranch        *b_Muon_nTkLayers;   //!
   TBranch        *b_Muon_nPixLayers;   //!
   TBranch        *b_Muon_nMatchStn;   //!
   TBranch        *b_Muon_trkID;   //!
   TBranch        *b_Tau_;   //!
   TBranch        *b_Tau_pt;   //!
   TBranch        *b_Tau_eta;   //!
   TBranch        *b_Tau_phi;   //!
   TBranch        *b_Tau_m;   //!
   TBranch        *b_Tau_e;   //!
   TBranch        *b_Tau_q;   //!
   TBranch        *b_Tau_dzLeadChHad;   //!
   TBranch        *b_Tau_d0LeadChHad;   //!
   TBranch        *b_Tau_nSignalChHad;   //!
   TBranch        *b_Tau_nSignalGamma;   //!
   TBranch        *b_Tau_decaymode;   //!
   TBranch        *b_Tau_antiEleMVA6;   //!
   TBranch        *b_Tau_antiEleMVA6Cat;   //!
   TBranch        *b_Tau_rawMuonRejection;   //!
   TBranch        *b_Tau_rawIso3Hits;   //!
   TBranch        *b_Tau_rawIsoMVA3oldDMwoLT;   //!
   TBranch        *b_Tau_rawIsoMVA3oldDMwLT;   //!
   TBranch        *b_Tau_rawIsoMVA3newDMwoLT;   //!
   TBranch        *b_Tau_rawIsoMVA3newDMwLT;   //!
   TBranch        *b_Tau_puppiChHadIso;   //!
   TBranch        *b_Tau_puppiGammaIso;   //!
   TBranch        *b_Tau_puppiNeuHadIso;   //!
   TBranch        *b_Tau_puppiChHadIsoNoLep;   //!
   TBranch        *b_Tau_puppiGammaIsoNoLep;   //!
   TBranch        *b_Tau_puppiNeuHadIsoNoLep;   //!
   TBranch        *b_Tau_hpsDisc;   //!
   TBranch        *b_Photon_;   //!
   TBranch        *b_Photon_pt;   //!
   TBranch        *b_Photon_eta;   //!
   TBranch        *b_Photon_phi;   //!
   TBranch        *b_Photon_scEt;   //!
   TBranch        *b_Photon_scEta;   //!
   TBranch        *b_Photon_scPhi;   //!
   TBranch        *b_Photon_trkIso;   //!
   TBranch        *b_Photon_ecalIso;   //!
   TBranch        *b_Photon_hcalIso;   //!
   TBranch        *b_Photon_chHadIso;   //!
   TBranch        *b_Photon_gammaIso;   //!
   TBranch        *b_Photon_neuHadIso;   //!
   TBranch        *b_Photon_mva;   //!
   TBranch        *b_Photon_hovere;   //!
   TBranch        *b_Photon_sthovere;   //!
   TBranch        *b_Photon_sieie;   //!
   TBranch        *b_Photon_sipip;   //!
   TBranch        *b_Photon_r9;   //!
   TBranch        *b_Photon_fiducialBits;   //!
   TBranch        *b_Photon_typeBits;   //!
   TBranch        *b_Photon_scID;   //!
   TBranch        *b_Photon_hasPixelSeed;   //!
   TBranch        *b_Photon_passElectronVeto;   //!
   TBranch        *b_Photon_isConv;   //!
   TBranch        *b_PV_;   //!
   TBranch        *b_PV_nTracksFit;   //!
   TBranch        *b_PV_ndof;   //!
   TBranch        *b_PV_chi2;   //!
   TBranch        *b_PV_x;   //!
   TBranch        *b_PV_y;   //!
   TBranch        *b_PV_z;   //!
   TBranch        *b_AK4CHS_;   //!
   TBranch        *b_AK4CHS_pt;   //!
   TBranch        *b_AK4CHS_eta;   //!
   TBranch        *b_AK4CHS_phi;   //!
   TBranch        *b_AK4CHS_mass;   //!
   TBranch        *b_AK4CHS_ptRaw;   //!
   TBranch        *b_AK4CHS_unc;   //!
   TBranch        *b_AK4CHS_area;   //!
   TBranch        *b_AK4CHS_d0;   //!
   TBranch        *b_AK4CHS_dz;   //!
   TBranch        *b_AK4CHS_csv;   //!
   TBranch        *b_AK4CHS_bmva;   //!
   TBranch        *b_AK4CHS_cvb;   //!
   TBranch        *b_AK4CHS_cvl;   //!
   TBranch        *b_AK4CHS_qgid;   //!
   TBranch        *b_AK4CHS_axis2;   //!
   TBranch        *b_AK4CHS_ptD;   //!
   TBranch        *b_AK4CHS_mult;   //!
   TBranch        *b_AK4CHS_q;   //!
   TBranch        *b_AK4CHS_mva;   //!
   TBranch        *b_AK4CHS_beta;   //!
   TBranch        *b_AK4CHS_betaStar;   //!
   TBranch        *b_AK4CHS_dR2Mean;   //!
   TBranch        *b_AK4CHS_pullY;   //!
   TBranch        *b_AK4CHS_pullPhi;   //!
   TBranch        *b_AK4CHS_chPullY;   //!
   TBranch        *b_AK4CHS_chPullPhi;   //!
   TBranch        *b_AK4CHS_neuPullY;   //!
   TBranch        *b_AK4CHS_neuPullPhi;   //!
   TBranch        *b_AK4CHS_chEmFrac;   //!
   TBranch        *b_AK4CHS_neuEmFrac;   //!
   TBranch        *b_AK4CHS_chHadFrac;   //!
   TBranch        *b_AK4CHS_neuHadFrac;   //!
   TBranch        *b_AK4CHS_muonFrac;   //!
   TBranch        *b_AK4CHS_genpt;   //!
   TBranch        *b_AK4CHS_geneta;   //!
   TBranch        *b_AK4CHS_genphi;   //!
   TBranch        *b_AK4CHS_genm;   //!
   TBranch        *b_AK4CHS_partonFlavor;   //!
   TBranch        *b_AK4CHS_hadronFlavor;   //!
   TBranch        *b_AK4CHS_nCharged;   //!
   TBranch        *b_AK4CHS_nNeutrals;   //!
   TBranch        *b_AK4CHS_nParticles;   //!
   TBranch        *b_AK8CHS_;   //!
   TBranch        *b_AK8CHS_pt;   //!
   TBranch        *b_AK8CHS_eta;   //!
   TBranch        *b_AK8CHS_phi;   //!
   TBranch        *b_AK8CHS_mass;   //!
   TBranch        *b_AK8CHS_ptRaw;   //!
   TBranch        *b_AK8CHS_unc;   //!
   TBranch        *b_AK8CHS_area;   //!
   TBranch        *b_AK8CHS_d0;   //!
   TBranch        *b_AK8CHS_dz;   //!
   TBranch        *b_AK8CHS_csv;   //!
   TBranch        *b_AK8CHS_bmva;   //!
   TBranch        *b_AK8CHS_cvb;   //!
   TBranch        *b_AK8CHS_cvl;   //!
   TBranch        *b_AK8CHS_qgid;   //!
   TBranch        *b_AK8CHS_axis2;   //!
   TBranch        *b_AK8CHS_ptD;   //!
   TBranch        *b_AK8CHS_mult;   //!
   TBranch        *b_AK8CHS_q;   //!
   TBranch        *b_AK8CHS_mva;   //!
   TBranch        *b_AK8CHS_beta;   //!
   TBranch        *b_AK8CHS_betaStar;   //!
   TBranch        *b_AK8CHS_dR2Mean;   //!
   TBranch        *b_AK8CHS_pullY;   //!
   TBranch        *b_AK8CHS_pullPhi;   //!
   TBranch        *b_AK8CHS_chPullY;   //!
   TBranch        *b_AK8CHS_chPullPhi;   //!
   TBranch        *b_AK8CHS_neuPullY;   //!
   TBranch        *b_AK8CHS_neuPullPhi;   //!
   TBranch        *b_AK8CHS_chEmFrac;   //!
   TBranch        *b_AK8CHS_neuEmFrac;   //!
   TBranch        *b_AK8CHS_chHadFrac;   //!
   TBranch        *b_AK8CHS_neuHadFrac;   //!
   TBranch        *b_AK8CHS_muonFrac;   //!
   TBranch        *b_AK8CHS_genpt;   //!
   TBranch        *b_AK8CHS_geneta;   //!
   TBranch        *b_AK8CHS_genphi;   //!
   TBranch        *b_AK8CHS_genm;   //!
   TBranch        *b_AK8CHS_partonFlavor;   //!
   TBranch        *b_AK8CHS_hadronFlavor;   //!
   TBranch        *b_AK8CHS_nCharged;   //!
   TBranch        *b_AK8CHS_nNeutrals;   //!
   TBranch        *b_AK8CHS_nParticles;   //!
   TBranch        *b_AddAK8CHS_;   //!
   TBranch        *b_AddAK8CHS_index;   //!
   TBranch        *b_AddAK8CHS_mass_prun;   //!
   TBranch        *b_AddAK8CHS_mass_trim;   //!
   TBranch        *b_AddAK8CHS_mass_sd0;   //!
   TBranch        *b_AddAK8CHS_c2_0;   //!
   TBranch        *b_AddAK8CHS_c2_0P2;   //!
   TBranch        *b_AddAK8CHS_c2_0P5;   //!
   TBranch        *b_AddAK8CHS_c2_1P0;   //!
   TBranch        *b_AddAK8CHS_c2_2P0;   //!
   TBranch        *b_AddAK8CHS_e2_b1;   //!
   TBranch        *b_AddAK8CHS_e3_b1;   //!
   TBranch        *b_AddAK8CHS_e3_v1_b1;   //!
   TBranch        *b_AddAK8CHS_e3_v2_b1;   //!
   TBranch        *b_AddAK8CHS_e4_v1_b1;   //!
   TBranch        *b_AddAK8CHS_e4_v2_b1;   //!
   TBranch        *b_AddAK8CHS_e2_b2;   //!
   TBranch        *b_AddAK8CHS_e3_b2;   //!
   TBranch        *b_AddAK8CHS_e3_v1_b2;   //!
   TBranch        *b_AddAK8CHS_e3_v2_b2;   //!
   TBranch        *b_AddAK8CHS_e4_v1_b2;   //!
   TBranch        *b_AddAK8CHS_e4_v2_b2;   //!
   TBranch        *b_AddAK8CHS_e2_sdb1;   //!
   TBranch        *b_AddAK8CHS_e3_sdb1;   //!
   TBranch        *b_AddAK8CHS_e3_v1_sdb1;   //!
   TBranch        *b_AddAK8CHS_e3_v2_sdb1;   //!
   TBranch        *b_AddAK8CHS_e4_v1_sdb1;   //!
   TBranch        *b_AddAK8CHS_e4_v2_sdb1;   //!
   TBranch        *b_AddAK8CHS_e2_sdb2;   //!
   TBranch        *b_AddAK8CHS_e3_sdb2;   //!
   TBranch        *b_AddAK8CHS_e3_v1_sdb2;   //!
   TBranch        *b_AddAK8CHS_e3_v2_sdb2;   //!
   TBranch        *b_AddAK8CHS_e4_v1_sdb2;   //!
   TBranch        *b_AddAK8CHS_e4_v2_sdb2;   //!
   TBranch        *b_AddAK8CHS_qjet;   //!
   TBranch        *b_AddAK8CHS_tau1;   //!
   TBranch        *b_AddAK8CHS_tau2;   //!
   TBranch        *b_AddAK8CHS_tau3;   //!
   TBranch        *b_AddAK8CHS_tau4;   //!
   TBranch        *b_AddAK8CHS_doublecsv;   //!
   TBranch        *b_AddAK8CHS_Double_sub;   //!
   TBranch        *b_AddAK8CHS_sj1_pt;   //!
   TBranch        *b_AddAK8CHS_sj1_eta;   //!
   TBranch        *b_AddAK8CHS_sj1_phi;   //!
   TBranch        *b_AddAK8CHS_sj1_m;   //!
   TBranch        *b_AddAK8CHS_sj1_csv;   //!
   TBranch        *b_AddAK8CHS_sj1_qgid;   //!
   TBranch        *b_AddAK8CHS_sj1_q;   //!
   TBranch        *b_AddAK8CHS_sj2_pt;   //!
   TBranch        *b_AddAK8CHS_sj2_eta;   //!
   TBranch        *b_AddAK8CHS_sj2_phi;   //!
   TBranch        *b_AddAK8CHS_sj2_m;   //!
   TBranch        *b_AddAK8CHS_sj2_csv;   //!
   TBranch        *b_AddAK8CHS_sj2_qgid;   //!
   TBranch        *b_AddAK8CHS_sj2_q;   //!
   TBranch        *b_AddAK8CHS_sj3_pt;   //!
   TBranch        *b_AddAK8CHS_sj3_eta;   //!
   TBranch        *b_AddAK8CHS_sj3_phi;   //!
   TBranch        *b_AddAK8CHS_sj3_m;   //!
   TBranch        *b_AddAK8CHS_sj3_csv;   //!
   TBranch        *b_AddAK8CHS_sj3_qgid;   //!
   TBranch        *b_AddAK8CHS_sj3_q;   //!
   TBranch        *b_AddAK8CHS_sj4_pt;   //!
   TBranch        *b_AddAK8CHS_sj4_eta;   //!
   TBranch        *b_AddAK8CHS_sj4_phi;   //!
   TBranch        *b_AddAK8CHS_sj4_m;   //!
   TBranch        *b_AddAK8CHS_sj4_csv;   //!
   TBranch        *b_AddAK8CHS_sj4_qgid;   //!
   TBranch        *b_AddAK8CHS_sj4_q;   //!
   TBranch        *b_AddAK8CHS_pullAngle;   //!
   TBranch        *b_AddAK8CHS_topTagType;   //!
   TBranch        *b_AddAK8CHS_top_n_subjets;   //!
   TBranch        *b_AddAK8CHS_top_m_min;   //!
   TBranch        *b_AddAK8CHS_top_m_123;   //!
   TBranch        *b_AddAK8CHS_top_fRec;   //!
   TBranch        *b_AddAK8CHS_topchi2;   //!
   TBranch        *b_CA15CHS_;   //!
   TBranch        *b_CA15CHS_pt;   //!
   TBranch        *b_CA15CHS_eta;   //!
   TBranch        *b_CA15CHS_phi;   //!
   TBranch        *b_CA15CHS_mass;   //!
   TBranch        *b_CA15CHS_ptRaw;   //!
   TBranch        *b_CA15CHS_unc;   //!
   TBranch        *b_CA15CHS_area;   //!
   TBranch        *b_CA15CHS_d0;   //!
   TBranch        *b_CA15CHS_dz;   //!
   TBranch        *b_CA15CHS_csv;   //!
   TBranch        *b_CA15CHS_bmva;   //!
   TBranch        *b_CA15CHS_cvb;   //!
   TBranch        *b_CA15CHS_cvl;   //!
   TBranch        *b_CA15CHS_qgid;   //!
   TBranch        *b_CA15CHS_axis2;   //!
   TBranch        *b_CA15CHS_ptD;   //!
   TBranch        *b_CA15CHS_mult;   //!
   TBranch        *b_CA15CHS_q;   //!
   TBranch        *b_CA15CHS_mva;   //!
   TBranch        *b_CA15CHS_beta;   //!
   TBranch        *b_CA15CHS_betaStar;   //!
   TBranch        *b_CA15CHS_dR2Mean;   //!
   TBranch        *b_CA15CHS_pullY;   //!
   TBranch        *b_CA15CHS_pullPhi;   //!
   TBranch        *b_CA15CHS_chPullY;   //!
   TBranch        *b_CA15CHS_chPullPhi;   //!
   TBranch        *b_CA15CHS_neuPullY;   //!
   TBranch        *b_CA15CHS_neuPullPhi;   //!
   TBranch        *b_CA15CHS_chEmFrac;   //!
   TBranch        *b_CA15CHS_neuEmFrac;   //!
   TBranch        *b_CA15CHS_chHadFrac;   //!
   TBranch        *b_CA15CHS_neuHadFrac;   //!
   TBranch        *b_CA15CHS_muonFrac;   //!
   TBranch        *b_CA15CHS_genpt;   //!
   TBranch        *b_CA15CHS_geneta;   //!
   TBranch        *b_CA15CHS_genphi;   //!
   TBranch        *b_CA15CHS_genm;   //!
   TBranch        *b_CA15CHS_partonFlavor;   //!
   TBranch        *b_CA15CHS_hadronFlavor;   //!
   TBranch        *b_CA15CHS_nCharged;   //!
   TBranch        *b_CA15CHS_nNeutrals;   //!
   TBranch        *b_CA15CHS_nParticles;   //!
   TBranch        *b_AddCA15CHS_;   //!
   TBranch        *b_AddCA15CHS_index;   //!
   TBranch        *b_AddCA15CHS_mass_prun;   //!
   TBranch        *b_AddCA15CHS_mass_trim;   //!
   TBranch        *b_AddCA15CHS_mass_sd0;   //!
   TBranch        *b_AddCA15CHS_c2_0;   //!
   TBranch        *b_AddCA15CHS_c2_0P2;   //!
   TBranch        *b_AddCA15CHS_c2_0P5;   //!
   TBranch        *b_AddCA15CHS_c2_1P0;   //!
   TBranch        *b_AddCA15CHS_c2_2P0;   //!
   TBranch        *b_AddCA15CHS_e2_b1;   //!
   TBranch        *b_AddCA15CHS_e3_b1;   //!
   TBranch        *b_AddCA15CHS_e3_v1_b1;   //!
   TBranch        *b_AddCA15CHS_e3_v2_b1;   //!
   TBranch        *b_AddCA15CHS_e4_v1_b1;   //!
   TBranch        *b_AddCA15CHS_e4_v2_b1;   //!
   TBranch        *b_AddCA15CHS_e2_b2;   //!
   TBranch        *b_AddCA15CHS_e3_b2;   //!
   TBranch        *b_AddCA15CHS_e3_v1_b2;   //!
   TBranch        *b_AddCA15CHS_e3_v2_b2;   //!
   TBranch        *b_AddCA15CHS_e4_v1_b2;   //!
   TBranch        *b_AddCA15CHS_e4_v2_b2;   //!
   TBranch        *b_AddCA15CHS_e2_sdb1;   //!
   TBranch        *b_AddCA15CHS_e3_sdb1;   //!
   TBranch        *b_AddCA15CHS_e3_v1_sdb1;   //!
   TBranch        *b_AddCA15CHS_e3_v2_sdb1;   //!
   TBranch        *b_AddCA15CHS_e4_v1_sdb1;   //!
   TBranch        *b_AddCA15CHS_e4_v2_sdb1;   //!
   TBranch        *b_AddCA15CHS_e2_sdb2;   //!
   TBranch        *b_AddCA15CHS_e3_sdb2;   //!
   TBranch        *b_AddCA15CHS_e3_v1_sdb2;   //!
   TBranch        *b_AddCA15CHS_e3_v2_sdb2;   //!
   TBranch        *b_AddCA15CHS_e4_v1_sdb2;   //!
   TBranch        *b_AddCA15CHS_e4_v2_sdb2;   //!
   TBranch        *b_AddCA15CHS_qjet;   //!
   TBranch        *b_AddCA15CHS_tau1;   //!
   TBranch        *b_AddCA15CHS_tau2;   //!
   TBranch        *b_AddCA15CHS_tau3;   //!
   TBranch        *b_AddCA15CHS_tau4;   //!
   TBranch        *b_AddCA15CHS_doublecsv;   //!
   TBranch        *b_AddCA15CHS_Double_sub;   //!
   TBranch        *b_AddCA15CHS_sj1_pt;   //!
   TBranch        *b_AddCA15CHS_sj1_eta;   //!
   TBranch        *b_AddCA15CHS_sj1_phi;   //!
   TBranch        *b_AddCA15CHS_sj1_m;   //!
   TBranch        *b_AddCA15CHS_sj1_csv;   //!
   TBranch        *b_AddCA15CHS_sj1_qgid;   //!
   TBranch        *b_AddCA15CHS_sj1_q;   //!
   TBranch        *b_AddCA15CHS_sj2_pt;   //!
   TBranch        *b_AddCA15CHS_sj2_eta;   //!
   TBranch        *b_AddCA15CHS_sj2_phi;   //!
   TBranch        *b_AddCA15CHS_sj2_m;   //!
   TBranch        *b_AddCA15CHS_sj2_csv;   //!
   TBranch        *b_AddCA15CHS_sj2_qgid;   //!
   TBranch        *b_AddCA15CHS_sj2_q;   //!
   TBranch        *b_AddCA15CHS_sj3_pt;   //!
   TBranch        *b_AddCA15CHS_sj3_eta;   //!
   TBranch        *b_AddCA15CHS_sj3_phi;   //!
   TBranch        *b_AddCA15CHS_sj3_m;   //!
   TBranch        *b_AddCA15CHS_sj3_csv;   //!
   TBranch        *b_AddCA15CHS_sj3_qgid;   //!
   TBranch        *b_AddCA15CHS_sj3_q;   //!
   TBranch        *b_AddCA15CHS_sj4_pt;   //!
   TBranch        *b_AddCA15CHS_sj4_eta;   //!
   TBranch        *b_AddCA15CHS_sj4_phi;   //!
   TBranch        *b_AddCA15CHS_sj4_m;   //!
   TBranch        *b_AddCA15CHS_sj4_csv;   //!
   TBranch        *b_AddCA15CHS_sj4_qgid;   //!
   TBranch        *b_AddCA15CHS_sj4_q;   //!
   TBranch        *b_AddCA15CHS_pullAngle;   //!
   TBranch        *b_AddCA15CHS_topTagType;   //!
   TBranch        *b_AddCA15CHS_top_n_subjets;   //!
   TBranch        *b_AddCA15CHS_top_m_min;   //!
   TBranch        *b_AddCA15CHS_top_m_123;   //!
   TBranch        *b_AddCA15CHS_top_fRec;   //!
   TBranch        *b_AddCA15CHS_topchi2;   //!
   TBranch        *b_AK4Puppi_;   //!
   TBranch        *b_AK4Puppi_pt;   //!
   TBranch        *b_AK4Puppi_eta;   //!
   TBranch        *b_AK4Puppi_phi;   //!
   TBranch        *b_AK4Puppi_mass;   //!
   TBranch        *b_AK4Puppi_ptRaw;   //!
   TBranch        *b_AK4Puppi_unc;   //!
   TBranch        *b_AK4Puppi_area;   //!
   TBranch        *b_AK4Puppi_d0;   //!
   TBranch        *b_AK4Puppi_dz;   //!
   TBranch        *b_AK4Puppi_csv;   //!
   TBranch        *b_AK4Puppi_bmva;   //!
   TBranch        *b_AK4Puppi_cvb;   //!
   TBranch        *b_AK4Puppi_cvl;   //!
   TBranch        *b_AK4Puppi_qgid;   //!
   TBranch        *b_AK4Puppi_axis2;   //!
   TBranch        *b_AK4Puppi_ptD;   //!
   TBranch        *b_AK4Puppi_mult;   //!
   TBranch        *b_AK4Puppi_q;   //!
   TBranch        *b_AK4Puppi_mva;   //!
   TBranch        *b_AK4Puppi_beta;   //!
   TBranch        *b_AK4Puppi_betaStar;   //!
   TBranch        *b_AK4Puppi_dR2Mean;   //!
   TBranch        *b_AK4Puppi_pullY;   //!
   TBranch        *b_AK4Puppi_pullPhi;   //!
   TBranch        *b_AK4Puppi_chPullY;   //!
   TBranch        *b_AK4Puppi_chPullPhi;   //!
   TBranch        *b_AK4Puppi_neuPullY;   //!
   TBranch        *b_AK4Puppi_neuPullPhi;   //!
   TBranch        *b_AK4Puppi_chEmFrac;   //!
   TBranch        *b_AK4Puppi_neuEmFrac;   //!
   TBranch        *b_AK4Puppi_chHadFrac;   //!
   TBranch        *b_AK4Puppi_neuHadFrac;   //!
   TBranch        *b_AK4Puppi_muonFrac;   //!
   TBranch        *b_AK4Puppi_genpt;   //!
   TBranch        *b_AK4Puppi_geneta;   //!
   TBranch        *b_AK4Puppi_genphi;   //!
   TBranch        *b_AK4Puppi_genm;   //!
   TBranch        *b_AK4Puppi_partonFlavor;   //!
   TBranch        *b_AK4Puppi_hadronFlavor;   //!
   TBranch        *b_AK4Puppi_nCharged;   //!
   TBranch        *b_AK4Puppi_nNeutrals;   //!
   TBranch        *b_AK4Puppi_nParticles;   //!
   TBranch        *b_AK8Puppi_;   //!
   TBranch        *b_AK8Puppi_pt;   //!
   TBranch        *b_AK8Puppi_eta;   //!
   TBranch        *b_AK8Puppi_phi;   //!
   TBranch        *b_AK8Puppi_mass;   //!
   TBranch        *b_AK8Puppi_ptRaw;   //!
   TBranch        *b_AK8Puppi_unc;   //!
   TBranch        *b_AK8Puppi_area;   //!
   TBranch        *b_AK8Puppi_d0;   //!
   TBranch        *b_AK8Puppi_dz;   //!
   TBranch        *b_AK8Puppi_csv;   //!
   TBranch        *b_AK8Puppi_bmva;   //!
   TBranch        *b_AK8Puppi_cvb;   //!
   TBranch        *b_AK8Puppi_cvl;   //!
   TBranch        *b_AK8Puppi_qgid;   //!
   TBranch        *b_AK8Puppi_axis2;   //!
   TBranch        *b_AK8Puppi_ptD;   //!
   TBranch        *b_AK8Puppi_mult;   //!
   TBranch        *b_AK8Puppi_q;   //!
   TBranch        *b_AK8Puppi_mva;   //!
   TBranch        *b_AK8Puppi_beta;   //!
   TBranch        *b_AK8Puppi_betaStar;   //!
   TBranch        *b_AK8Puppi_dR2Mean;   //!
   TBranch        *b_AK8Puppi_pullY;   //!
   TBranch        *b_AK8Puppi_pullPhi;   //!
   TBranch        *b_AK8Puppi_chPullY;   //!
   TBranch        *b_AK8Puppi_chPullPhi;   //!
   TBranch        *b_AK8Puppi_neuPullY;   //!
   TBranch        *b_AK8Puppi_neuPullPhi;   //!
   TBranch        *b_AK8Puppi_chEmFrac;   //!
   TBranch        *b_AK8Puppi_neuEmFrac;   //!
   TBranch        *b_AK8Puppi_chHadFrac;   //!
   TBranch        *b_AK8Puppi_neuHadFrac;   //!
   TBranch        *b_AK8Puppi_muonFrac;   //!
   TBranch        *b_AK8Puppi_genpt;   //!
   TBranch        *b_AK8Puppi_geneta;   //!
   TBranch        *b_AK8Puppi_genphi;   //!
   TBranch        *b_AK8Puppi_genm;   //!
   TBranch        *b_AK8Puppi_partonFlavor;   //!
   TBranch        *b_AK8Puppi_hadronFlavor;   //!
   TBranch        *b_AK8Puppi_nCharged;   //!
   TBranch        *b_AK8Puppi_nNeutrals;   //!
   TBranch        *b_AK8Puppi_nParticles;   //!
   TBranch        *b_AddAK8Puppi_;   //!
   TBranch        *b_AddAK8Puppi_index;   //!
   TBranch        *b_AddAK8Puppi_mass_prun;   //!
   TBranch        *b_AddAK8Puppi_mass_trim;   //!
   TBranch        *b_AddAK8Puppi_mass_sd0;   //!
   TBranch        *b_AddAK8Puppi_c2_0;   //!
   TBranch        *b_AddAK8Puppi_c2_0P2;   //!
   TBranch        *b_AddAK8Puppi_c2_0P5;   //!
   TBranch        *b_AddAK8Puppi_c2_1P0;   //!
   TBranch        *b_AddAK8Puppi_c2_2P0;   //!
   TBranch        *b_AddAK8Puppi_e2_b1;   //!
   TBranch        *b_AddAK8Puppi_e3_b1;   //!
   TBranch        *b_AddAK8Puppi_e3_v1_b1;   //!
   TBranch        *b_AddAK8Puppi_e3_v2_b1;   //!
   TBranch        *b_AddAK8Puppi_e4_v1_b1;   //!
   TBranch        *b_AddAK8Puppi_e4_v2_b1;   //!
   TBranch        *b_AddAK8Puppi_e2_b2;   //!
   TBranch        *b_AddAK8Puppi_e3_b2;   //!
   TBranch        *b_AddAK8Puppi_e3_v1_b2;   //!
   TBranch        *b_AddAK8Puppi_e3_v2_b2;   //!
   TBranch        *b_AddAK8Puppi_e4_v1_b2;   //!
   TBranch        *b_AddAK8Puppi_e4_v2_b2;   //!
   TBranch        *b_AddAK8Puppi_e2_sdb1;   //!
   TBranch        *b_AddAK8Puppi_e3_sdb1;   //!
   TBranch        *b_AddAK8Puppi_e3_v1_sdb1;   //!
   TBranch        *b_AddAK8Puppi_e3_v2_sdb1;   //!
   TBranch        *b_AddAK8Puppi_e4_v1_sdb1;   //!
   TBranch        *b_AddAK8Puppi_e4_v2_sdb1;   //!
   TBranch        *b_AddAK8Puppi_e2_sdb2;   //!
   TBranch        *b_AddAK8Puppi_e3_sdb2;   //!
   TBranch        *b_AddAK8Puppi_e3_v1_sdb2;   //!
   TBranch        *b_AddAK8Puppi_e3_v2_sdb2;   //!
   TBranch        *b_AddAK8Puppi_e4_v1_sdb2;   //!
   TBranch        *b_AddAK8Puppi_e4_v2_sdb2;   //!
   TBranch        *b_AddAK8Puppi_qjet;   //!
   TBranch        *b_AddAK8Puppi_tau1;   //!
   TBranch        *b_AddAK8Puppi_tau2;   //!
   TBranch        *b_AddAK8Puppi_tau3;   //!
   TBranch        *b_AddAK8Puppi_tau4;   //!
   TBranch        *b_AddAK8Puppi_doublecsv;   //!
   TBranch        *b_AddAK8Puppi_Double_sub;   //!
   TBranch        *b_AddAK8Puppi_sj1_pt;   //!
   TBranch        *b_AddAK8Puppi_sj1_eta;   //!
   TBranch        *b_AddAK8Puppi_sj1_phi;   //!
   TBranch        *b_AddAK8Puppi_sj1_m;   //!
   TBranch        *b_AddAK8Puppi_sj1_csv;   //!
   TBranch        *b_AddAK8Puppi_sj1_qgid;   //!
   TBranch        *b_AddAK8Puppi_sj1_q;   //!
   TBranch        *b_AddAK8Puppi_sj2_pt;   //!
   TBranch        *b_AddAK8Puppi_sj2_eta;   //!
   TBranch        *b_AddAK8Puppi_sj2_phi;   //!
   TBranch        *b_AddAK8Puppi_sj2_m;   //!
   TBranch        *b_AddAK8Puppi_sj2_csv;   //!
   TBranch        *b_AddAK8Puppi_sj2_qgid;   //!
   TBranch        *b_AddAK8Puppi_sj2_q;   //!
   TBranch        *b_AddAK8Puppi_sj3_pt;   //!
   TBranch        *b_AddAK8Puppi_sj3_eta;   //!
   TBranch        *b_AddAK8Puppi_sj3_phi;   //!
   TBranch        *b_AddAK8Puppi_sj3_m;   //!
   TBranch        *b_AddAK8Puppi_sj3_csv;   //!
   TBranch        *b_AddAK8Puppi_sj3_qgid;   //!
   TBranch        *b_AddAK8Puppi_sj3_q;   //!
   TBranch        *b_AddAK8Puppi_sj4_pt;   //!
   TBranch        *b_AddAK8Puppi_sj4_eta;   //!
   TBranch        *b_AddAK8Puppi_sj4_phi;   //!
   TBranch        *b_AddAK8Puppi_sj4_m;   //!
   TBranch        *b_AddAK8Puppi_sj4_csv;   //!
   TBranch        *b_AddAK8Puppi_sj4_qgid;   //!
   TBranch        *b_AddAK8Puppi_sj4_q;   //!
   TBranch        *b_AddAK8Puppi_pullAngle;   //!
   TBranch        *b_AddAK8Puppi_topTagType;   //!
   TBranch        *b_AddAK8Puppi_top_n_subjets;   //!
   TBranch        *b_AddAK8Puppi_top_m_min;   //!
   TBranch        *b_AddAK8Puppi_top_m_123;   //!
   TBranch        *b_AddAK8Puppi_top_fRec;   //!
   TBranch        *b_AddAK8Puppi_topchi2;   //!
   TBranch        *b_CA15Puppi_;   //!
   TBranch        *b_CA15Puppi_pt;   //!
   TBranch        *b_CA15Puppi_eta;   //!
   TBranch        *b_CA15Puppi_phi;   //!
   TBranch        *b_CA15Puppi_mass;   //!
   TBranch        *b_CA15Puppi_ptRaw;   //!
   TBranch        *b_CA15Puppi_unc;   //!
   TBranch        *b_CA15Puppi_area;   //!
   TBranch        *b_CA15Puppi_d0;   //!
   TBranch        *b_CA15Puppi_dz;   //!
   TBranch        *b_CA15Puppi_csv;   //!
   TBranch        *b_CA15Puppi_bmva;   //!
   TBranch        *b_CA15Puppi_cvb;   //!
   TBranch        *b_CA15Puppi_cvl;   //!
   TBranch        *b_CA15Puppi_qgid;   //!
   TBranch        *b_CA15Puppi_axis2;   //!
   TBranch        *b_CA15Puppi_ptD;   //!
   TBranch        *b_CA15Puppi_mult;   //!
   TBranch        *b_CA15Puppi_q;   //!
   TBranch        *b_CA15Puppi_mva;   //!
   TBranch        *b_CA15Puppi_beta;   //!
   TBranch        *b_CA15Puppi_betaStar;   //!
   TBranch        *b_CA15Puppi_dR2Mean;   //!
   TBranch        *b_CA15Puppi_pullY;   //!
   TBranch        *b_CA15Puppi_pullPhi;   //!
   TBranch        *b_CA15Puppi_chPullY;   //!
   TBranch        *b_CA15Puppi_chPullPhi;   //!
   TBranch        *b_CA15Puppi_neuPullY;   //!
   TBranch        *b_CA15Puppi_neuPullPhi;   //!
   TBranch        *b_CA15Puppi_chEmFrac;   //!
   TBranch        *b_CA15Puppi_neuEmFrac;   //!
   TBranch        *b_CA15Puppi_chHadFrac;   //!
   TBranch        *b_CA15Puppi_neuHadFrac;   //!
   TBranch        *b_CA15Puppi_muonFrac;   //!
   TBranch        *b_CA15Puppi_genpt;   //!
   TBranch        *b_CA15Puppi_geneta;   //!
   TBranch        *b_CA15Puppi_genphi;   //!
   TBranch        *b_CA15Puppi_genm;   //!
   TBranch        *b_CA15Puppi_partonFlavor;   //!
   TBranch        *b_CA15Puppi_hadronFlavor;   //!
   TBranch        *b_CA15Puppi_nCharged;   //!
   TBranch        *b_CA15Puppi_nNeutrals;   //!
   TBranch        *b_CA15Puppi_nParticles;   //!
   TBranch        *b_AddCA15Puppi_;   //!
   TBranch        *b_AddCA15Puppi_index;   //!
   TBranch        *b_AddCA15Puppi_mass_prun;   //!
   TBranch        *b_AddCA15Puppi_mass_trim;   //!
   TBranch        *b_AddCA15Puppi_mass_sd0;   //!
   TBranch        *b_AddCA15Puppi_c2_0;   //!
   TBranch        *b_AddCA15Puppi_c2_0P2;   //!
   TBranch        *b_AddCA15Puppi_c2_0P5;   //!
   TBranch        *b_AddCA15Puppi_c2_1P0;   //!
   TBranch        *b_AddCA15Puppi_c2_2P0;   //!
   TBranch        *b_AddCA15Puppi_e2_b1;   //!
   TBranch        *b_AddCA15Puppi_e3_b1;   //!
   TBranch        *b_AddCA15Puppi_e3_v1_b1;   //!
   TBranch        *b_AddCA15Puppi_e3_v2_b1;   //!
   TBranch        *b_AddCA15Puppi_e4_v1_b1;   //!
   TBranch        *b_AddCA15Puppi_e4_v2_b1;   //!
   TBranch        *b_AddCA15Puppi_e2_b2;   //!
   TBranch        *b_AddCA15Puppi_e3_b2;   //!
   TBranch        *b_AddCA15Puppi_e3_v1_b2;   //!
   TBranch        *b_AddCA15Puppi_e3_v2_b2;   //!
   TBranch        *b_AddCA15Puppi_e4_v1_b2;   //!
   TBranch        *b_AddCA15Puppi_e4_v2_b2;   //!
   TBranch        *b_AddCA15Puppi_e2_sdb1;   //!
   TBranch        *b_AddCA15Puppi_e3_sdb1;   //!
   TBranch        *b_AddCA15Puppi_e3_v1_sdb1;   //!
   TBranch        *b_AddCA15Puppi_e3_v2_sdb1;   //!
   TBranch        *b_AddCA15Puppi_e4_v1_sdb1;   //!
   TBranch        *b_AddCA15Puppi_e4_v2_sdb1;   //!
   TBranch        *b_AddCA15Puppi_e2_sdb2;   //!
   TBranch        *b_AddCA15Puppi_e3_sdb2;   //!
   TBranch        *b_AddCA15Puppi_e3_v1_sdb2;   //!
   TBranch        *b_AddCA15Puppi_e3_v2_sdb2;   //!
   TBranch        *b_AddCA15Puppi_e4_v1_sdb2;   //!
   TBranch        *b_AddCA15Puppi_e4_v2_sdb2;   //!
   TBranch        *b_AddCA15Puppi_qjet;   //!
   TBranch        *b_AddCA15Puppi_tau1;   //!
   TBranch        *b_AddCA15Puppi_tau2;   //!
   TBranch        *b_AddCA15Puppi_tau3;   //!
   TBranch        *b_AddCA15Puppi_tau4;   //!
   TBranch        *b_AddCA15Puppi_doublecsv;   //!
   TBranch        *b_AddCA15Puppi_Double_sub;   //!
   TBranch        *b_AddCA15Puppi_sj1_pt;   //!
   TBranch        *b_AddCA15Puppi_sj1_eta;   //!
   TBranch        *b_AddCA15Puppi_sj1_phi;   //!
   TBranch        *b_AddCA15Puppi_sj1_m;   //!
   TBranch        *b_AddCA15Puppi_sj1_csv;   //!
   TBranch        *b_AddCA15Puppi_sj1_qgid;   //!
   TBranch        *b_AddCA15Puppi_sj1_q;   //!
   TBranch        *b_AddCA15Puppi_sj2_pt;   //!
   TBranch        *b_AddCA15Puppi_sj2_eta;   //!
   TBranch        *b_AddCA15Puppi_sj2_phi;   //!
   TBranch        *b_AddCA15Puppi_sj2_m;   //!
   TBranch        *b_AddCA15Puppi_sj2_csv;   //!
   TBranch        *b_AddCA15Puppi_sj2_qgid;   //!
   TBranch        *b_AddCA15Puppi_sj2_q;   //!
   TBranch        *b_AddCA15Puppi_sj3_pt;   //!
   TBranch        *b_AddCA15Puppi_sj3_eta;   //!
   TBranch        *b_AddCA15Puppi_sj3_phi;   //!
   TBranch        *b_AddCA15Puppi_sj3_m;   //!
   TBranch        *b_AddCA15Puppi_sj3_csv;   //!
   TBranch        *b_AddCA15Puppi_sj3_qgid;   //!
   TBranch        *b_AddCA15Puppi_sj3_q;   //!
   TBranch        *b_AddCA15Puppi_sj4_pt;   //!
   TBranch        *b_AddCA15Puppi_sj4_eta;   //!
   TBranch        *b_AddCA15Puppi_sj4_phi;   //!
   TBranch        *b_AddCA15Puppi_sj4_m;   //!
   TBranch        *b_AddCA15Puppi_sj4_csv;   //!
   TBranch        *b_AddCA15Puppi_sj4_qgid;   //!
   TBranch        *b_AddCA15Puppi_sj4_q;   //!
   TBranch        *b_AddCA15Puppi_pullAngle;   //!
   TBranch        *b_AddCA15Puppi_topTagType;   //!
   TBranch        *b_AddCA15Puppi_top_n_subjets;   //!
   TBranch        *b_AddCA15Puppi_top_m_min;   //!
   TBranch        *b_AddCA15Puppi_top_m_123;   //!
   TBranch        *b_AddCA15Puppi_top_fRec;   //!
   TBranch        *b_AddCA15Puppi_topchi2;   //!

   setInputTree(std::string inputTree);
   virtual ~setInputTree();
   Int_t    Cut(Long64_t entry);
   Int_t    GetEntry(Long64_t entry);
   Long64_t LoadTree(Long64_t entry);
   void     Init();
   //virtual void     Loop();
   Bool_t   Notify();
   void     Show(Long64_t entry = -1);
};

#endif
