xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_1.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_1.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_10.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_10.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_11.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_11.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_2.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_2.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_3.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_3.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_4.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_4.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_5.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_5.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_6.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_6.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_7.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_7.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_8.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_8.root
xrdcp -f /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/Samples/180622_201804/0000/Output_9.root /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Output_9.root



echo "-------------------------"
echo "ls /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8/ "
echo "eosrm -r /eos/uscms/store/user/lnujj/WpWm_aQGC_Ntuples_Ram/FirstStepOutput/BaconNtuples/DoublyChargedHiggsGMmodel_HWW_WWToLNuQQ_M600_13TeV-madgraph-pythia8//Samples "
