#include "../interface/setOutputTree.h"

setOutputTree::setOutputTree(TTree* outTree){
  fTree = outTree;
  fTree->SetAutoSave(500000000);
  setBranches();
}

setOutputTree::~setOutputTree(){
  delete fTree;
}

void setOutputTree::initializeVariables()
{
  LHEWeight[1163] = { };
  run		=-999;
  event		=-999;
  nTotEvents	=0;
  nTotNegEvents	=0;
  nEvents	=0;
  nNegEvents	=0;
  lumi		=-999;
  nPV		=-999;
  issignal	=0;
  issignal_PuppiAK8	=0;
  issignal_AK4jetjet	=0;
  issignal_PuppiAK4jetjet=0;
  isVBF		= 0;
  isPuppiVBF	= 0;
  wSampleWeight	=-999;
  genWeight	=1;
  top1_NNLO_Weight	=1.;
  top2_NNLO_Weight	=1.;
  trig_eff_Weight	=1.;
  trig_eff_Weight2	=1.;
  id_eff_Weight		=1.;
  id_eff_Weight2	=1.;
  gen_top1_pt		=-999;
  gen_top2_pt		=-999;
  totalEventWeight	=-999;
  totalEventWeight_2	=-999;
  totalEventWeight_3	=-999;
  totalEventWeight_2Lep	=-999;
  pu_Weight	=-999;
  pu_Weight_up	=-999;
  pu_Weight_down	=-999;
  pfMET		=-999;
  pfMET_jes_up	=-999;
  pfMET_jes_dn	=-999;
  pfMET_Phi	=-999;
  pfMET_Corr   =-999; 
  pfMET_Corr_phi   =-999; 
  pfMET_Corr_Cov00   =-999; 
  pfMET_Corr_Cov01   =-999; 
  pfMET_Corr_Cov11   =-999; 
  pfMET_Corr_jerup   =-999; 
  pfMET_Corr_jerdn   =-999; 
  pfMET_Corr_jenup   =-999; 
  pfMET_Corr_jendn   =-999; 
  pfMET_Corr_uncup   =-999; 
  pfMET_Corr_uncdn   =-999; 
  pfMET_Corr_jrsup   =-999; 
  pfMET_Corr_jrsdn   =-999; 
  pfMET_Corr_phijerup   =-999; 
  pfMET_Corr_phijerdn   =-999; 
  pfMET_Corr_phijenup   =-999; 
  pfMET_Corr_phijendn   =-999; 
  pfMET_Corr_phiuncup   =-999; 
  pfMET_Corr_phiuncdn   =-999; 
  pfMET_Corr_phijrsup   =-999; 
  pfMET_Corr_phijrsdn   =-999; 
  pfMETpuppi	=-999;
  pfMETpuppi_jes_up	=-999;
  pfMETpuppi_jes_dn	=-999;
  pfMETpuppi_jer	=-999;
  pfMETpuppi_jer_up	=-999;
  pfMETpuppi_jer_dn	=-999;
  pfMETpuppi_Phi	=-999;
  pfMETpuppi_Cov00   =-999; 
  pfMETpuppi_Cov01   =-999; 
  pfMETpuppi_Cov11   =-999; 
  pfMETpuppi_Corr   =-999; 
  pfMETpuppi_Corr_phi   =-999; 
  pfMETpuppi_Corr_Cov00   =-999; 
  pfMETpuppi_Corr_Cov01   =-999; 
  pfMETpuppi_Corr_Cov11   =-999; 
  nu_pz_type0	=-999;
  nu_pz_type2	=-999;
  nu_pz_run2	=-999;
  nu_pz_run2_oth	=-999;
  nu_pz_run2_type	=-999;
  nu_pz_isre	=1;
  type = -1;
  l_pt1		=-999;
  l_eta1       	=-999;
  l_phi1       	=-999;
  l_e1		=-999;
  l_charge1	=-999;
  l_iso1	=-999;
  l_pt2		=-999;
  l_eta2	=-999;
  l_phi2	=-999;
  l_e2		=-999;
  l_charge2	=-999;
  l_iso2	=-999;
  dilep_pt	=-999;
  dilep_eta	=-999;
  dilep_phi	=-999;
  dilep_m	=-999;
  isGen		=-999;
  lep_pt_gen	=-999;
  lep_eta_gen	=-999;
  W_pt_gen	=-999;
  W_pz_gen	=-999;
  W_rap_gen	=-999;
  nu_pz_gen	=-999;
  nu_pt_gen	=-999;
  nu_phi_gen	=-999;
  nu_eta_gen	=-999;
  hadW_pt_gen	=-999;
  hadW_eta_gen	=-999;
  hadW_phi_gen	=-999;
  hadW_e_gen	=-999;
  hadW_m_gen	=-999;
  lepW_pt_gen	=-999;
  lepW_eta_gen	=-999;
  lepW_phi_gen	=-999;
  lepW_e_gen	=-999;
  lepW_m_gen	=-999;
  WW_mass_gen	=-999.0;
  WW_mT_gen	=-999.0;
  WW_pT_gen	=-999.0;
  AK8_pt_gen	=-999;
  AK8_eta_gen	=-999;
  AK8_phi_gen	=-999;
  AK8_e_gen	=-999;
  AK8_mass_gen	=-999;
  AK8_pruned_mass_gen	=-999;
  AK8_softdrop_mass_gen	=-999;
  AK8_softdrop_pt_gen	=-999;
  deltaR_Wjet_GenReco	=-999;
  deltaR_lak8jet	=-999;
  deltaphi_METak8jet	=-999;
  deltaphi_Vak8jet	=-999;
  deltaR_lPuppiak8jet	=-999;
  deltaphi_METPuppiak8jet=-999;
  deltaphi_VPuppiak8jet	=-999;
  deltaR_lak4jetjet	=-999;
  deltaphi_METak4jetjet	=-999;
  deltaphi_Vak4jetjet	=-999;
  deltaR_lPuppiak4jetjet=-999;
  deltaphi_METPuppiak4jetjet	=-999;
  deltaphi_VPuppiak4jetjet	=-999;
  deltaR_l2Puppiak8jet  = -999;
  deltaR_VLepPuppiak8jet  = -999;
  v_pt_type2	=-999;
  v_pt_type0	=-999;
  v_pt_run2	=-999;
  v_eta_type2	=-999;
  v_eta_type0	=-999;
  v_eta_run2	=-999;
  v_phi		=-999;
  v_mt_type2	=-999;
  v_mt_type0	=-999;
  v_mt_run2	=-999;
  v_mass_type2	=-999;
  v_mass_type0	=-999;
  v_mass_run2	=-999;
  v_pt_type0_jer_up	= -999.;
  v_eta_type0_jer_up	= -999.;
  v_mt_type0_jer_up	= -999.;
  v_mass_type0_jer_up	= -999.;
  v_pt_type0_jer_dn	= -999.;
  v_eta_type0_jer_dn	= -999.;
  v_mt_type0_jer_dn	= -999.;
  v_mass_type0_jer_dn	= -999.;
  v_pt_type0_jes_up	= -999.;
  v_eta_type0_jes_up	= -999.;
  v_mt_type0_jes_up	= -999.;
  v_mass_type0_jes_up	= -999.;
  v_pt_type0_jes_dn	= -999.;
  v_eta_type0_jes_dn	= -999.;
  v_mt_type0_jes_dn	= -999.;
  v_mass_type0_jes_dn	= -999.;
  v_puppi_pt_type2	=-999;
  v_puppi_pt_type0	=-999;
  v_puppi_pt_run2	=-999;
  v_puppi_eta_type2	=-999;
  v_puppi_eta_type0	=-999;
  v_puppi_eta_run2	=-999;
  v_puppi_phi	=-999;
  v_puppi_mt_type2	=-999;
  v_puppi_mt_type0	=-999;
  v_puppi_mt_run2	=-999;
  v_puppi_mass_type2	=-999;
  v_puppi_mass_type0	=-999;
  v_puppi_mass_run2	=-999;
  mass_lvj_type0		=-999;
  mass_lvj_type0_met_jes_up	=-999;
  mass_lvj_type0_met_jes_dn	=-999;
  mass_lvj_type0_met_jer_up	=-999;
  mass_lvj_type0_met_jer_dn	=-999;
  mass_lvj_type0_met_jer	=-999;
  mass_lvj_type0_met_PuppiAK8_jes_up	=-999;
  mass_lvj_type0_met_PuppiAK8_jes_dn	=-999;
  mass_lvj_type2	=-999;
  mass_lvj_run2		=-999;
  mass_lvj_type0_PuppiAK8	=-999;
  mass_lvj_type2_PuppiAK8	=-999;
  mass_lvj_run2_PuppiAK8	=-999;
  mt_lvj_type0_PuppiAK8	=-999;
  mt_lvj_type2_PuppiAK8	=-999;
  mt_lvj_run2_PuppiAK8	=-999;
  pt_lvj_type0_PuppiAK8	=-999;
  pt_lvj_type2_PuppiAK8	=-999;
  pt_lvj_run2_PuppiAK8	=-999;
  eta_lvj_type0_PuppiAK8	=-999;
  eta_lvj_type2_PuppiAK8	=-999;
  eta_lvj_run2_PuppiAK8		=-999;
  rapidity_lvj_type0_PuppiAK8	=-999;
  rapidity_lvj_type2_PuppiAK8	=-999;
  rapidity_lvj_run2_PuppiAK8	=-999;
  phi_lvj_type0_PuppiAK8	=-999;
  phi_lvj_type2_PuppiAK8	=-999;
  phi_lvj_run2_PuppiAK8		=-999;
  energy_lvj_type0_PuppiAK8	=-999;
  energy_lvj_type2_PuppiAK8	=-999;
  energy_lvj_run2_PuppiAK8	=-999;
  mass_lvjj_type0_AK4		=-999;
  mass_lvjj_type0_met_jes_up_AK4	=-999;
  mass_lvjj_type0_met_jes_dn_AK4	=-999;
  mass_lvjj_type2_AK4		=-999;
  mass_lvjj_run2_AK4		=-999;
  mass_lvjj_type0_PuppiAK4	=-999;
  mass_lvjj_type0_met_jes_up_PuppiAK4	=-999;
  mass_lvjj_type0_met_jes_dn_PuppiAK4	=-999;
  mass_lvjj_type2_PuppiAK4	=-999;
  mass_lvjj_run2_PuppiAK4	=-999;
  mass_llj_PuppiAK8		=-999;
  pt_llj_PuppiAK8 = -999;
  eta_llj_PuppiAK8  = -999;
  phi_llj_PuppiAK8  = -999;
  njets			=0;
  njetsPuppi		=0;
  nGoodAK8jets		=0;
  njets_unmerged	=0;
  njetsPuppi_unmerged	=0;
  nBTagJet_loose	=0;
  nBTagJet_medium	=0;
  nBTagJet_tight	=0;
  nBTagJetPuppi_loose	=0;
  nBTagJetPuppi_medium	=0;
  nBTagJetPuppi_tight	=0;
  nBTagJet_loose_unmerged	=0;
  nBTagJet_medium_unmerged	=0;
  nBTagJet_tight_unmerged	=0;
  nBTagJetPuppi_loose_unmerged	=0;
  nBTagJetPuppi_medium_unmerged	=0;
  nBTagJetPuppi_tight_unmerged	=0;
  btag0Wgt			=-999.;
  btag1Wgt			=-999.;
  btag2Wgt			=-999.;
  btag0WgtUpHF			=-999.;
  btag0WgtDownHF		=-999.;
  btag0WgtUpLF			=-999.;
  btag0WgtDownLF		=-999.;
  btag1WgtUpHF			=-999.;
  btag1WgtDownHF		=-999.;
  btag1WgtUpLF			=-999.;
  btag1WgtDownLF		=-999.;
  ungroomed_AK8jet_pt		=-999;
  ungroomed_AK8jet_pt_jes_up	=-999;
  ungroomed_AK8jet_pt_jes_dn	=-999;
  ungroomed_AK8jet_pt_jer		=-999;
  ungroomed_AK8jet_pt_jer_up	=-999;
  ungroomed_AK8jet_pt_jer_dn	=-999;
  ungroomed_AK8jet_eta	=-999;
  ungroomed_AK8jet_eta_jes_up	=-999;
  ungroomed_AK8jet_eta_jes_dn	=-999;
  ungroomed_AK8jet_phi	=-999;
  ungroomed_AK8jet_phi_jes_dn	=-999;
  ungroomed_AK8jet_phi_jes_up	=-999;
  ungroomed_AK8jet_e	=-999;
  ungroomed_PuppiAK8_jet_charge	=-999;
  AK8jet_mass		=-999;
  ungroomed_AK8jet_mass_jes_up	=-999;
  ungroomed_AK8jet_mass_jes_dn	=-999;
  AK8jet_mass_pr	=-999;
  AK8jet_mass_pr_jes_up	=-999;
  AK8jet_mass_pr_jes_dn	=-999;
  AK8jet_mass_pr_jer	=-999;
  AK8jet_mass_pr_jer_up	=-999;
  AK8jet_mass_pr_jer_dn	=-999;
  AK8jet_mass_so	=-999;
  AK8jet_pt_so	=-999;
  AK8jet_mass_tr	=-999;
  AK8jet_mass_fi	=-999;
  AK8jet_tau2tau1	=-999;
  AK8jet_sj1_pt		=-999;
  AK8jet_sj1_eta	=-999;
  AK8jet_sj1_phi	=-999;
  AK8jet_sj1_m		=-999;
  AK8jet_sj1_q		=-999;
  AK8jet_sj2_pt		=-999;
  AK8jet_sj2_eta	=-999;
  AK8jet_sj2_phi	=-999;
  AK8jet_sj2_m		=-999;
  AK8jet_sj2_q		=-999;
  AK8_jetID_loose	=-999;
AK8jet_e3_b1  = -999;
AK8jet_e3_v1_b1  = -999;
AK8jet_e3_v2_b1  = -999;
AK8jet_e4_v1_b1  = -999;
AK8jet_e4_v2_b1  = -999;
AK8jet_e3_b2  = -999;
AK8jet_e3_v1_b2  = -999;
AK8jet_e3_v2_b2  = -999;
AK8jet_e4_v1_b2  = -999;
AK8jet_e4_v2_b2  = -999;
AK8jet_e2_sdb1  = -999;
AK8jet_e3_sdb1  = -999;
AK8jet_e3_v1_sdb1  = -999;
AK8jet_e3_v2_sdb1  = -999;
AK8jet_e4_v1_sdb1  = -999;
AK8jet_e4_v2_sdb1  = -999;
AK8jet_e2_sdb2  = -999;
AK8jet_e3_sdb2  = -999;
AK8jet_e3_v1_sdb2  = -999;
AK8jet_e3_v2_sdb2  = -999;
AK8jet_e4_v1_sdb2  = -999;
AK8jet_e4_v2_sdb2  = -999;
AK8jet_e2_sdb4  = -999;
AK8jet_e3_sdb4  = -999;
AK8jet_e3_v1_sdb4  = -999;
AK8jet_e3_v2_sdb4  = -999;
AK8jet_e4_v1_sdb4  = -999;
AK8jet_e4_v2_sdb4  = -999;
AK8jet_e2_sdb05  = -999;
AK8jet_e3_sdb05  = -999;
AK8jet_e3_v1_sdb05  = -999;
AK8jet_e3_v2_sdb05  = -999;
AK8jet_e4_v1_sdb05  = -999;
AK8jet_e4_v2_sdb05  = -999;
AK8jet_qjet  = -999;
  AK4_jetjet_pt	=-999;
  AK4_jetjet_mass	=-999;
  AK4_jetjet_deltaeta	=-999;
  AK4_jetjet_deltaphi	=-999;
  AK4_jetjet_deltar	=-999;
  PuppiAK4_jetjet_pt	=-999;
  PuppiAK4_jetjet_mass	=-999;
  PuppiAK4_jetjet_deltaeta	=-999;
  PuppiAK4_jetjet_deltaphi	=-999;
  PuppiAK4_jetjet_deltar	=-999;
  ungroomed_PuppiAK8_jet_pt	=-999;
  ungroomed_PuppiAK8_jet_pt_jes_up	=-999;
  ungroomed_PuppiAK8_jet_pt_jes_dn	=-999;
  ungroomed_PuppiAK8_jet_pt_jer		=-999;
  ungroomed_PuppiAK8_jet_pt_jer_up	=-999;
  ungroomed_PuppiAK8_jet_pt_jer_dn	=-999;
  ungroomed_PuppiAK8_jet_eta	=-999;
  ungroomed_PuppiAK8_jet_eta_jes_up	=-999;
  ungroomed_PuppiAK8_jet_eta_jes_dn	=-999;
  ungroomed_PuppiAK8_jet_phi	=-999;
  ungroomed_PuppiAK8_jet_phi_jes_up	=-999;
  ungroomed_PuppiAK8_jet_phi_jes_dn	=-999;
  ungroomed_PuppiAK8_jet_e	=-999;
  ungroomed_PuppiAK8_jet_charge	=-999;
  PuppiAK8_jet_mass		=-999;
  ungroomed_PuppiAK8_jet_mass_jes_up	=-999;
  ungroomed_PuppiAK8_jet_mass_jes_dn	=-999;
  PuppiAK8_jet_mass_pr		=-999;
  PuppiAK8_jet_mass_pr_jes_up	=-999;
  PuppiAK8_jet_mass_pr_jes_dn	=-999;
  PuppiAK8_jet_mass_pr_jer	=-999;
  PuppiAK8_jet_mass_pr_jer_up	=-999;
  PuppiAK8_jet_mass_pr_jer_dn	=-999;
  PuppiAK8_jet_mass_so		=-999;
  PuppiAK8_jet_mass_so_corr	=-999;
  PuppiAK8_jet_pt_so		=-999;
  PuppiAK8_jet_mass_tr	=-999;
  PuppiAK8_jet_mass_fi	=-999;
  PuppiAK8_jet_tau2tau1	=-999;
  PuppiAK8_jet_sj1_pt   =-999;
  PuppiAK8_jet_sj1_eta  =-999;
  PuppiAK8_jet_sj1_phi  =-999;
  PuppiAK8_jet_sj1_m    =-999;
  PuppiAK8_jet_sj1_q    =-999;
  PuppiAK8_jet_sj2_pt   =-999;
  PuppiAK8_jet_sj2_eta  =-999;
  PuppiAK8_jet_sj2_phi  =-999;
  PuppiAK8_jet_sj2_m    =-999;
  PuppiAK8_jet_sj2_q    =-999;
  PuppiAK8_jetID_loose  =0;
PuppiAK8jet_e3_b1  = -999;
PuppiAK8jet_e3_v1_b1  = -999;
PuppiAK8jet_e3_v2_b1  = -999;
PuppiAK8jet_e4_v1_b1  = -999;
PuppiAK8jet_e4_v2_b1  = -999;
PuppiAK8jet_e3_b2  = -999;
PuppiAK8jet_e3_v1_b2  = -999;
PuppiAK8jet_e3_v2_b2  = -999;
PuppiAK8jet_e4_v1_b2  = -999;
PuppiAK8jet_e4_v2_b2  = -999;
PuppiAK8jet_e2_sdb1  = -999;
PuppiAK8jet_e3_sdb1  = -999;
PuppiAK8jet_e3_v1_sdb1  = -999;
PuppiAK8jet_e3_v2_sdb1  = -999;
PuppiAK8jet_e4_v1_sdb1  = -999;
PuppiAK8jet_e4_v2_sdb1  = -999;
PuppiAK8jet_e2_sdb2  = -999;
PuppiAK8jet_e3_sdb2  = -999;
PuppiAK8jet_e3_v1_sdb2  = -999;
PuppiAK8jet_e3_v2_sdb2  = -999;
PuppiAK8jet_e4_v1_sdb2  = -999;
PuppiAK8jet_e4_v2_sdb2  = -999;
PuppiAK8jet_e2_sdb4  = -999;
PuppiAK8jet_e3_sdb4  = -999;
PuppiAK8jet_e3_v1_sdb4  = -999;
PuppiAK8jet_e3_v2_sdb4  = -999;
PuppiAK8jet_e4_v1_sdb4  = -999;
PuppiAK8jet_e4_v2_sdb4  = -999;
PuppiAK8jet_e2_sdb05  = -999;
PuppiAK8jet_e3_sdb05  = -999;
PuppiAK8jet_e3_v1_sdb05  = -999;
PuppiAK8jet_e3_v2_sdb05  = -999;
PuppiAK8jet_e4_v1_sdb05  = -999;
PuppiAK8jet_e4_v2_sdb05  = -999;
PuppiAK8jet_qjet  = -999;
  AK4_jet1_pt		=-999;
  AK4_jet1_pt_jes_up	=-999;
  AK4_jet1_pt_jes_dn	=-999;
  AK4_jet1_pt_jer	=-999;
  AK4_jet1_pt_jer_up	=-999;
  AK4_jet1_pt_jer_dn	=-999;
  AK4_jet1_eta		=-999;
  AK4_jet1_phi		=-999;
  AK4_jet1_e		=-999;
  AK4_jet2_pt		=-999;
  AK4_jet2_pt_jes_up	=-999;
  AK4_jet2_pt_jes_dn	=-999;
  AK4_jet2_pt_jer	=-999;
  AK4_jet2_pt_jer_up	=-999;
  AK4_jet2_pt_jer_dn	=-999;
  AK4_jet2_eta		=-999;
  AK4_jet2_phi		=-999;
  AK4_jet2_e		=-999;
  PuppiAK4_jet1_pt	=-999;
  PuppiAK4_jet1_pt_jes_up	=-999;
  PuppiAK4_jet1_pt_jes_dn	=-999;
  PuppiAK4_jet1_pt_jer		=-999;
  PuppiAK4_jet1_pt_jer_up	=-999;
  PuppiAK4_jet1_pt_jer_dn	=-999;
  PuppiAK4_jet1_eta	=-999;
  PuppiAK4_jet1_phi	=-999;
  PuppiAK4_jet1_e	=-999;
  PuppiAK4_jet2_pt	=-999;
  PuppiAK4_jet2_pt_jes_up	=-999;
  PuppiAK4_jet2_pt_jes_dn	=-999;
  PuppiAK4_jet2_pt_jer		=-999;
  PuppiAK4_jet2_pt_jer_up	=-999;
  PuppiAK4_jet2_pt_jer_dn	=-999;
  PuppiAK4_jet2_eta	=-999;
  PuppiAK4_jet2_phi	=-999;
  PuppiAK4_jet2_e	=-999;
  ttb_ungroomed_jet_pt	=-999;
  ttb_ungroomed_jet_eta	=-999;
  ttb_ungroomed_jet_phi	=-999;
  ttb_ungroomed_jet_e	=-999;
  ttb_jet_mass_pr	=-999;
  ttb_jet_mass_so	=-999;
  ttb_jet_pt_so		=-999;
  ttb_jet_mass_tr	=-999;
  ttb_jet_mass_fi	=-999;
  ttb_jet_tau2tau1	=-999;
  ttb_deltaeta_lak8jet	=-999;
  mass_leptonic_closerjet	=-999;
  mass_ungroomedjet_closerjet	=-999;
  AK8_closerjet_pt	=-999;
  AK8_closerjet_eta	=-999;
  AK8_closerjet_phi	=-999;
  AK8_closerjet_e	=-999;
  vbf_maxpt_j1_pt	=-999; 
  vbf_maxpt_j1_pt_jes_up	=-999;
  vbf_maxpt_j1_pt_jes_dn	=-999;
  vbf_maxpt_j1_pt_jer		=-999;
  vbf_maxpt_j1_pt_jer_up	=-999;
  vbf_maxpt_j1_pt_jer_dn	=-999;
  vbf_maxpt_j1_eta		=-999;
  vbf_maxpt_j1_eta_jes_up	=-999;
  vbf_maxpt_j1_eta_jes_dn	=-999;
  vbf_maxpt_j1_eta_jer		=-999;
  vbf_maxpt_j1_eta_jer_up	=-999;
  vbf_maxpt_j1_eta_jer_dn	=-999;
  vbf_maxpt_j1_phi		=-999;
  vbf_maxpt_j1_phi_jes_up	=-999;
  vbf_maxpt_j1_phi_jes_dn	=-999;
  vbf_maxpt_j1_e		=-999;
  vbf_maxpt_j1_mass		=-999;
  vbf_maxpt_j1_mass_jes_up	=-999;
  vbf_maxpt_j1_mass_jes_dn	=-999;
  vbf_maxpt_j1_bDiscriminatorCSV	=-999;
  vbf_maxpt_j1_charge		=-999;
  vbf_maxpt_j2_pt		=-999;
  vbf_maxpt_j2_pt_jes_up	=-999;
  vbf_maxpt_j2_pt_jes_dn	=-999;
  vbf_maxpt_j2_pt_jer		=-999;
  vbf_maxpt_j2_pt_jer_up	=-999;
  vbf_maxpt_j2_pt_jer_dn	=-999;
  vbf_maxpt_j2_eta		=-999;
  vbf_maxpt_j2_eta_jes_up	=-999;
  vbf_maxpt_j2_eta_jes_dn	=-999;
  vbf_maxpt_j2_eta_jer		=-999;
  vbf_maxpt_j2_eta_jer_up	=-999;
  vbf_maxpt_j2_eta_jer_dn	=-999;
  vbf_maxpt_j2_phi		=-999;
  vbf_maxpt_j2_phi_jes_up	=-999;
  vbf_maxpt_j2_phi_jes_dn	=-999;
  vbf_maxpt_j2_e		=-999;
  vbf_maxpt_j2_mass		=-999;
  vbf_maxpt_j2_mass_jes_up	=-999;
  vbf_maxpt_j2_mass_jes_dn	=-999;
  vbf_maxpt_j2_bDiscriminatorCSV	=-999;
  vbf_maxpt_j2_charge		=-999;
  vbfPuppi_maxpt_j1_ID		=-999;
  vbfPuppi_maxpt_j2_ID		=-999;
  vbf_maxpt_jj_pt		=-999;
  vbf_maxpt_jj_pt_jes_up	=-999;
  vbf_maxpt_jj_pt_jes_dn	=-999;
  vbf_maxpt_jj_eta		=-999;
  vbf_maxpt_jj_phi		=-999;
  vbf_maxpt_jj_m		=-999;
  vbf_maxpt_jj_m_jes_up		=-999;
  vbf_maxpt_jj_m_jes_dn		=-999;
  vbf_maxpt_jj_Deta		=-999;
  vbf_maxpt_jj_Deta_jes_up	=-999;
  vbf_maxpt_jj_Deta_jes_dn	=-999;
  vbf_maxpt_deltaR 	=-999;
  deltaphi_METvbfJ1	=-999;
  deltaphi_METvbfJ2	=-999;
  deltaphi_METmin	=-999;
  vbfPuppi_maxpt_j1_pt	=-999; 
  vbfPuppi_maxpt_j1_pt_jes_up	=-999;
  vbfPuppi_maxpt_j1_pt_jes_dn	=-999;
  vbfPuppi_maxpt_j1_pt_jer		=-999;
  vbfPuppi_maxpt_j1_pt_jer_up	=-999;
  vbfPuppi_maxpt_j1_pt_jer_dn	=-999;
  vbfPuppi_maxpt_j1_eta		=-999;
  vbfPuppi_maxpt_j1_eta_jes_up	=-999;
  vbfPuppi_maxpt_j1_eta_jes_dn	=-999;
  vbfPuppi_maxpt_j1_eta_jer		=-999;
  vbfPuppi_maxpt_j1_eta_jer_up	=-999;
  vbfPuppi_maxpt_j1_eta_jer_dn	=-999;
  vbfPuppi_maxpt_j1_phi		=-999;
  vbfPuppi_maxpt_j1_e		=-999;
  vbfPuppi_maxpt_j1_bDiscriminatorCSV	=-999;
  vbfPuppi_maxpt_j2_pt		=-999;
  vbfPuppi_maxpt_j2_pt_jes_up	=-999;
  vbfPuppi_maxpt_j2_pt_jes_dn	=-999;
  vbfPuppi_maxpt_j2_pt_jer		=-999;
  vbfPuppi_maxpt_j2_pt_jer_up	=-999;
  vbfPuppi_maxpt_j2_pt_jer_dn	=-999;
  vbfPuppi_maxpt_j2_eta		=-999;
  vbfPuppi_maxpt_j2_eta_jes_up	=-999;
  vbfPuppi_maxpt_j2_eta_jes_dn	=-999;
  vbfPuppi_maxpt_j2_eta_jer		=-999;
  vbfPuppi_maxpt_j2_eta_jer_up	=-999;
  vbfPuppi_maxpt_j2_eta_jer_dn	=-999;
  vbfPuppi_maxpt_j2_phi		=-999;
  vbfPuppi_maxpt_j2_e		=-999;
  vbfPuppi_maxpt_j2_bDiscriminatorCSV	=-999;
  vbfPuppi_maxpt_jj_pt		=-999;
  vbfPuppi_maxpt_jj_eta		=-999;
  vbfPuppi_maxpt_jj_phi		=-999;
  vbfPuppi_maxpt_jj_m		=-999;
  vbfPuppi_maxpt_jj_Deta		=-999;
  vbfPuppi_maxpt_deltaR 	=-999;
  jet2_pt	=0;
  jet2_eta	=0;
  jet2_phi	=0;
  jet2_e	=0;
  jet2_btag	=0;
  jet3_pt	=0;
  jet3_eta	=0;
  jet3_phi	=0;
  jet3_e	=0;
  jet3_btag	=0;
  deltaR_AK8_closestBtagJet		=0;
  deltaR_AK8_closestBtagJet_loose	=0;
  ////
  costheta1Puppi_type0	=-999;
  costheta2Puppi_type0	=-999;
  costhetastarPuppi_type0	=-999;
  phiPuppi_type0		=-999;
  phi1Puppi_type0		=-999;
  VBSCentralityPuppi_type0	=-999;
  costheta1Puppi_type2	=-999;
  costheta2Puppi_type2	=-999;
  costhetastarPuppi_type2	=-999;
  phiPuppi_type2		=-999;
  phi1Puppi_type2		=-999;
  VBSCentralityPuppi_type2	=-999;
  costheta1Puppi_run2	=-999;
  costheta2Puppi_run2	=-999;
  costhetastarPuppi_run2	=-999;
  phiPuppi_run2		=-999;
  phi1Puppi_run2		=-999;
  VBSCentralityPuppi_run2	=-999;
  RpTPuppi_type0 		=-999.0;
  ZeppenfeldWLPuppi_type0 	=-999.0;
  LeptonProjectionPuppi_type0 =-999.0;
  RpTPuppi_type2 		=-999.0;
  ZeppenfeldWLPuppi_type2 	=-999.0;
  LeptonProjectionPuppi_type2=-999.0;
  RpTPuppi_run2 		=-999.0;
  ZeppenfeldWLPuppi_type2 	=-999.0;
  LeptonProjectionPuppi_type2=-999.0;
  ////
  costheta1_type0	=-999;
  costheta2_type0	=-999;
  costhetastar_type0	=-999;
  phi_type0		=-999;
  phi1_type0		=-999;
  VBSCentrality_type0	=-999;
  costheta1_type2	=-999;
  costheta2_type2	=-999;
  costhetastar_type2	=-999;
  phi_type2		=-999;
  phi1_type2		=-999;
  VBSCentrality_type2	=-999;
  costheta1_run2	=-999;
  costheta2_run2	=-999;
  costhetastar_run2	=-999;
  phi_run2		=-999;
  phi1_run2		=-999;
  VBSCentrality_run2	=-999;
  RpT_type0 		=-999.0;
  ZeppenfeldWL_type0 	=-999.0;
ZeppenfeldWL_type0_jes_up	=-999;
ZeppenfeldWL_type0_jes_dn	=-999;
ZeppenfeldWL_type0_jer_up	=-999;
ZeppenfeldWL_type0_jer_dn	=-999;
  LeptonProjection_type0 =-999.0;
  RpT_type2 		=-999.0;
  ZeppenfeldWL_type2 	=-999.0;
  LeptonProjection_type2=-999.0;
  RpT_run2 		=-999.0;
  ZeppenfeldWL_type2 	=-999.0;
  LeptonProjection_type2=-999.0;
  LepWEta 		=-999;
  LepWRapidity 	=-999;
  HadWEta 		=-999;
  HadWRapidity 	=-999;
  WWEta 		=-999;
  WWRapidity 	=-999;
  ZeppenfeldWH 		=-999.0;
ZeppenfeldWH_jes_up	=-999;
ZeppenfeldWH_jes_dn	=-999;
  ZeppenfeldWHPuppi	=-999.0;
  AK4_1_pt_gen		=-999;
  AK4_1_eta_gen		=-999;
  AK4_1_phi_gen		=-999;
  AK4_1_e_gen		=-999;
  AK4_1_mass_gen	=-999;
  AK4_2_pt_gen		=-999;
  AK4_2_eta_gen		=-999;
  AK4_2_phi_gen		=-999;
  AK4_2_e_gen		=-999;
  AK4_2_mass_gen	=-999;
  AK4_jj_DeltaEta_gen	=-999;
  AK4_jj_mass_gen	=-999;
  AK4_DR_GENRECO_11	= -999.;
  AK4_DR_GENRECO_12	= -999.;
  AK4_DR_GENRECO_21	= -999.;
  AK4_DR_GENRECO_22	= -999.;
  AK4Puppi_DR_GENRECO_11	= -999.;
  AK4Puppi_DR_GENRECO_12	= -999.;
  AK4Puppi_DR_GENRECO_21	= -999.;
  AK4Puppi_DR_GENRECO_22	= -999.;
  //AK4_BIG_gen_mass=-999;
  //deltaR_AK4=-999;
  PtBalance_type0		=-999.;
PtBalance_type0_jes_up	=-999;
PtBalance_type0_jes_dn	=-999;
PtBalance_type0_jer_up	=-999;
PtBalance_type0_jer_dn	=-999;
  PtBalance_type2		=-999.;
  PtBalance_run2		=-999.;
  BosonCentrality_type0		=-999.;
BosonCentrality_type0_jes_up	=-999;
BosonCentrality_type0_jes_dn	=-999;
BosonCentrality_type0_jer_up	=-999;
BosonCentrality_type0_jer_dn	=-999;
  BosonCentrality_type2		=-999.;
  BosonCentrality_run2		=-999.;
  BosonCentralityPuppi_type0	=-999.;
  BosonCentralityPuppi_type2	=-999.;
  BosonCentralityPuppi_run2	=-999.;
  PtBalance_2Lep  = -999;
BosonCentrality_2Lep  = -999;
BosonCentrality_2Lep_jes_up	=-999;
BosonCentrality_2Lep_jes_dn	=-999;
costheta1_2Lep  = -999;
costheta2_2Lep  = -999;
costhetastar_2Lep = -999;
phi_2Lep  = -999;
phi1_2Lep = -999;
VBSCentrality_2Lep  = -999;
RpT_2Lep  = -999;
ZeppenfeldWL_2Lep = -999;
ZeppenfeldWL_2Lep_jes_up	=-999;
ZeppenfeldWL_2Lep_jes_dn	=-999;
LeptonProjection_2Lep = -999;

}

void setOutputTree::setBranches()
{
  fTree->Branch("LHEWeight",&LHEWeight[0],"LHEWeight[1164]/F");
  fTree->Branch("run",&run,"run/I");
  fTree->Branch("event",&event,"event/I");
  fTree->Branch("nTotEvents",&nTotEvents,"nTotEvents/I");
  fTree->Branch("nTotNegEvents",&nTotNegEvents,"nTotNegEvents/I");
  fTree->Branch("nEvents",&nEvents,"nEvents/I");
  fTree->Branch("nNegEvents",&nNegEvents,"nNegEvents/I");
  fTree->Branch("lumi",&lumi,"lumi/I");
  fTree->Branch("nPV",&nPV,"nPV/I");
  fTree->Branch("issignal",&issignal,"issignal/I");
  fTree->Branch("issignal_PuppiAK8",&issignal_PuppiAK8,"issignal_PuppiAK8/I");
  fTree->Branch("issignal_AK4jetjet",&issignal_AK4jetjet,"issignal_AK4jetjet/I");
  fTree->Branch("issignal_PuppiAK4jetjet",&issignal_PuppiAK4jetjet,"issignal_PuppiAK4jetjet/I");
  fTree->Branch("isVBF",&isVBF,"isVBF/I");
  fTree->Branch("isPuppiVBF",&isPuppiVBF,"isPuppiVBF/I");
  fTree->Branch("wSampleWeight",&wSampleWeight,"wSampleWeight/F");
  fTree->Branch("genWeight",&genWeight,"genWeight/F");
  fTree->Branch("top1_NNLO_Weight",&top1_NNLO_Weight,"top1_NNLO_Weight/F");
  fTree->Branch("top2_NNLO_Weight",&top2_NNLO_Weight,"top2_NNLO_Weight/F");
  fTree->Branch("gen_top1_pt",&gen_top1_pt,"gen_top1_pt/F");
  fTree->Branch("gen_top2_pt",&gen_top2_pt,"gen_top2_pt/F");
  fTree->Branch("trig_eff_Weight",&trig_eff_Weight,"trig_eff_Weight/F");
  fTree->Branch("trig_eff_Weight2",&trig_eff_Weight2,"trig_eff_Weight2/F");
  fTree->Branch("id_eff_Weight",&id_eff_Weight,"id_eff_Weight/F");
  fTree->Branch("id_eff_Weight2",&id_eff_Weight2,"id_eff_Weight2/F");
  fTree->Branch("totalEventWeight",&totalEventWeight,"totalEventWeight/F");
  fTree->Branch("pu_Weight",&pu_Weight,"pu_Weight/F");
  fTree->Branch("totalEventWeight_2",&totalEventWeight_2,"totalEventWeight_2/F");
  fTree->Branch("pu_Weight_up",&pu_Weight_up,"pu_Weight_up/F");
  fTree->Branch("totalEventWeight_3",&totalEventWeight_3,"totalEventWeight_3/F");
  fTree->Branch("totalEventWeight_2Lep", &totalEventWeight_2Lep, "totalEventWeight_2Lep/F");
  fTree->Branch("pu_Weight_down",&pu_Weight_down,"pu_Weight_down/F");
  fTree->Branch("pfMET",&pfMET,"pfMET/F");
  fTree->Branch("pfMET_jes_up",&pfMET_jes_up,"pfMET_jes_up/F");
  fTree->Branch("pfMET_jes_dn",&pfMET_jes_dn,"pfMET_jes_dn/F");
  fTree->Branch("pfMET_Phi",&pfMET_Phi,"pfMET_Phi/F");
  fTree->Branch("pfMET_Corr",&pfMET_Corr,"pfMET_Corr/F");
  fTree->Branch("pfMET_Corr_phi",&pfMET_Corr_phi,"pfMET_Corr_phi/F");
  fTree->Branch("pfMET_Corr_Cov00",&pfMET_Corr_Cov00,"pfMET_Corr_Cov00/F");
  fTree->Branch("pfMET_Corr_Cov01",&pfMET_Corr_Cov01,"pfMET_Corr_Cov01/F");
  fTree->Branch("pfMET_Corr_Cov11",&pfMET_Corr_Cov11,"pfMET_Corr_Cov11/F");
  fTree->Branch("pfMET_Corr_jerup",&pfMET_Corr_jerup,"pfMET_Corr_jerup/F");
  fTree->Branch("pfMET_Corr_jerdn",&pfMET_Corr_jerdn,"pfMET_Corr_jerdn/F");
  fTree->Branch("pfMET_Corr_jenup",&pfMET_Corr_jenup,"pfMET_Corr_jenup/F");
  fTree->Branch("pfMET_Corr_jendn",&pfMET_Corr_jendn,"pfMET_Corr_jendn/F");
  fTree->Branch("pfMET_Corr_uncup",&pfMET_Corr_uncup,"pfMET_Corr_uncup/F");
  fTree->Branch("pfMET_Corr_uncdn",&pfMET_Corr_uncdn,"pfMET_Corr_uncdn/F");
  fTree->Branch("pfMET_Corr_jrsup",&pfMET_Corr_jrsup,"pfMET_Corr_jrsup/F");
  fTree->Branch("pfMET_Corr_jrsdn",&pfMET_Corr_jrsdn,"pfMET_Corr_jrsdn/F");
  fTree->Branch("pfMET_Corr_phijerup",&pfMET_Corr_phijerup,"pfMET_Corr_phijerup/F");
  fTree->Branch("pfMET_Corr_phijerdn",&pfMET_Corr_phijerdn,"pfMET_Corr_phijerdn/F");
  fTree->Branch("pfMET_Corr_phijenup",&pfMET_Corr_phijenup,"pfMET_Corr_phijenup/F");
  fTree->Branch("pfMET_Corr_phijendn",&pfMET_Corr_phijendn,"pfMET_Corr_phijendn/F");
  fTree->Branch("pfMET_Corr_phiuncup",&pfMET_Corr_phiuncup,"pfMET_Corr_phiuncup/F");
  fTree->Branch("pfMET_Corr_phiuncdn",&pfMET_Corr_phiuncdn,"pfMET_Corr_phiuncdn/F");
  fTree->Branch("pfMET_Corr_phijrsup",&pfMET_Corr_phijrsup,"pfMET_Corr_phijrsup/F");
  fTree->Branch("pfMET_Corr_phijrsdn",&pfMET_Corr_phijrsdn,"pfMET_Corr_phijrsdn/F");
  fTree->Branch("pfMETpuppi",&pfMETpuppi,"pfMETpuppi/F");
  fTree->Branch("pfMETpuppi_jes_up",&pfMETpuppi_jes_up,"pfMETpuppi_jes_up/F");
  fTree->Branch("pfMETpuppi_jes_dn",&pfMETpuppi_jes_dn,"pfMETpuppi_jes_dn/F");
  fTree->Branch("pfMETpuppi_jer",&pfMETpuppi_jer,"pfMETpuppi_jer/F");
  fTree->Branch("pfMETpuppi_jer_up",&pfMETpuppi_jer_up,"pfMETpuppi_jer_up/F");
  fTree->Branch("pfMETpuppi_jer_dn",&pfMETpuppi_jer_dn,"pfMETpuppi_jer_dn/F");
  fTree->Branch("pfMETpuppi_Phi",&pfMETpuppi_Phi,"pfMETpuppi_Phi/F");
  fTree->Branch("pfMETpuppi_Cov00",&pfMETpuppi_Cov00,"pfMETpuppi_Cov00/F");
  fTree->Branch("pfMETpuppi_Cov01",&pfMETpuppi_Cov01,"pfMETpuppi_Cov01/F");
  fTree->Branch("pfMETpuppi_Cov11",&pfMETpuppi_Cov11,"pfMETpuppi_Cov11/F");
  fTree->Branch("pfMETpuppi_Corr",	&pfMETpuppi_Corr,	"pfMETpuppi_Corr/F");
  fTree->Branch("pfMETpuppi_Corr_phi",	&pfMETpuppi_Corr_phi,	"pfMETpuppi_Corr_phi/F");
  fTree->Branch("pfMETpuppi_Corr_Cov00",&pfMETpuppi_Corr_Cov00,	"pfMETpuppi_Corr_Cov00/F");
  fTree->Branch("pfMETpuppi_Corr_Cov01",&pfMETpuppi_Corr_Cov01,	"pfMETpuppi_Corr_Cov01/F");
  fTree->Branch("pfMETpuppi_Corr_Cov11",&pfMETpuppi_Corr_Cov11,	"pfMETpuppi_Corr_Cov11/F");
  fTree->Branch("nu_pz_type0",&nu_pz_type0,"nu_pz_type0/F");
  fTree->Branch("nu_pz_type2",&nu_pz_type2,"nu_pz_type2/F");
  fTree->Branch("nu_pz_run2",&nu_pz_run2,"nu_pz_run2/F");
  fTree->Branch("nu_pz_run2_oth",&nu_pz_run2_oth,"nu_pz_run2_oth/F");
  fTree->Branch("nu_pz_run2_type",&nu_pz_run2_type,"nu_pz_run2_type/I");
  fTree->Branch("nu_pz_isre",&nu_pz_isre,"nu_pz_isre/I");
  fTree->Branch("type",&type,"type/I");
  fTree->Branch("l_pt1",&l_pt1,"l_pt1/F");
  fTree->Branch("l_eta1",&l_eta1,"l_eta1/F");
  fTree->Branch("l_phi1",&l_phi1,"l_phi1/F");
  fTree->Branch("l_e1",&l_e1,"l_e1/F");
  fTree->Branch("l_charge1",&l_charge1,"l_charge1/F");
  fTree->Branch("l_iso1",&l_iso1,"l_iso1/F");
  fTree->Branch("l_pt2",&l_pt2,"l_pt2/F");
  fTree->Branch("l_eta2",&l_eta2,"l_eta2/F");
  fTree->Branch("l_phi2",&l_phi2,"l_phi2/F");
  fTree->Branch("l_e2",&l_e2,"l_e2/F");
  fTree->Branch("dilep_pt",&dilep_pt,"dilep_pt/F");
  fTree->Branch("dilep_eta",&dilep_eta,"dilep_eta/F");
  fTree->Branch("dilep_phi",&dilep_phi,"dilep_phi/F");
  fTree->Branch("dilep_m",&dilep_m,"dilep_m/F");
  fTree->Branch("l_charge2",&l_charge2,"l_charge2/F");
  fTree->Branch("l_iso2",&l_iso2,"l_iso2/F");
  fTree->Branch("ungroomed_AK8jet_pt",&ungroomed_AK8jet_pt,"ungroomed_AK8jet_pt/F");
  fTree->Branch("ungroomed_AK8jet_pt_jes_up",&ungroomed_AK8jet_pt_jes_up,"ungroomed_AK8jet_pt_jes_up/F");
  fTree->Branch("ungroomed_AK8jet_pt_jes_dn",&ungroomed_AK8jet_pt_jes_dn,"ungroomed_AK8jet_pt_jes_dn/F");
  fTree->Branch("ungroomed_AK8jet_pt_jer",&ungroomed_AK8jet_pt_jer,"ungroomed_AK8jet_pt_jer/F");
  fTree->Branch("ungroomed_AK8jet_pt_jer_up",&ungroomed_AK8jet_pt_jer_up,"ungroomed_AK8jet_pt_jer_up/F");
  fTree->Branch("ungroomed_AK8jet_pt_jer_dn",&ungroomed_AK8jet_pt_jer_dn,"ungroomed_AK8jet_pt_jer_dn/F");
  fTree->Branch("ungroomed_AK8jet_eta",&ungroomed_AK8jet_eta,"ungroomed_AK8jet_eta/F");
  fTree->Branch("ungroomed_AK8jet_eta_jes_up",&ungroomed_AK8jet_eta_jes_up,"ungroomed_AK8jet_eta_jes_up/F");
  fTree->Branch("ungroomed_AK8jet_eta_jes_dn",&ungroomed_AK8jet_eta_jes_dn,"ungroomed_AK8jet_eta_jes_dn/F");
  fTree->Branch("ungroomed_AK8jet_phi",&ungroomed_AK8jet_phi,"ungroomed_AK8jet_phi/F");
  fTree->Branch("ungroomed_AK8jet_phi_jes_up",&ungroomed_AK8jet_phi_jes_up,"ungroomed_AK8jet_phi_jes_up/F");
  fTree->Branch("ungroomed_AK8jet_phi_jes_dn",&ungroomed_AK8jet_phi_jes_dn,"ungroomed_AK8jet_phi_jes_dn/F");
  fTree->Branch("ungroomed_AK8jet_e",&ungroomed_AK8jet_e,"ungroomed_AK8jet_e/F");
  fTree->Branch("ungroomed_AK8jet_charge",&ungroomed_AK8jet_charge,"ungroomed_AK8jet_charge/F");
  fTree->Branch("AK8jet_mass",&AK8jet_mass,"AK8jet_mass");
  fTree->Branch("ungroomed_AK8jet_mass_jes_up",&ungroomed_AK8jet_mass_jes_up,"ungroomed_AK8jet_mass_jes_up/F");
  fTree->Branch("ungroomed_AK8jet_mass_jes_dn",&ungroomed_AK8jet_mass_jes_dn,"ungroomed_AK8jet_mass_jes_dn/F");
  fTree->Branch("AK8jet_mass_pr",&AK8jet_mass_pr,"AK8jet_mass_pr");
  fTree->Branch("AK8jet_mass_pr_jes_up",&AK8jet_mass_pr_jes_up,"AK8jet_mass_pr_jes_up/F");
  fTree->Branch("AK8jet_mass_pr_jes_dn",&AK8jet_mass_pr_jes_dn,"AK8jet_mass_pr_jes_dn/F");
  fTree->Branch("AK8jet_mass_pr_jer",&AK8jet_mass_pr_jer,"AK8jet_mass_pr_jer/F");
  fTree->Branch("AK8jet_mass_pr_jer_up",&AK8jet_mass_pr_jer_up,"AK8jet_mass_pr_jer_up/F");
  fTree->Branch("AK8jet_mass_pr_jer_dn",&AK8jet_mass_pr_jer_dn,"AK8jet_mass_pr_jer_dn/F");
  fTree->Branch("AK8jet_mass_so",&AK8jet_mass_so,"AK8jet_mass_so");
  fTree->Branch("AK8jet_pt_so",&AK8jet_pt_so,"AK8jet_pt_so");
  fTree->Branch("AK8jet_mass_tr",&AK8jet_mass_tr,"AK8jet_mass_tr");
  fTree->Branch("AK8jet_mass_fi",&AK8jet_mass_fi,"AK8jet_mass_fi");
  fTree->Branch("AK8jet_tau2tau1",&AK8jet_tau2tau1,"AK8jet_tau2tau1");
  fTree->Branch("AK8jet_sj1_pt",&AK8jet_sj1_pt,"AK8jet_sj1_pt");
  fTree->Branch("AK8jet_sj1_eta",&AK8jet_sj1_eta,"AK8jet_sj1_eta");
  fTree->Branch("AK8jet_sj1_phi",&AK8jet_sj1_phi,"AK8jet_sj1_phi");
  fTree->Branch("AK8jet_sj1_m",&AK8jet_sj1_m,"AK8jet_sj1_m");
  fTree->Branch("AK8jet_sj1_q",&AK8jet_sj1_q,"AK8jet_sj1_q");
  fTree->Branch("AK8jet_sj2_pt",&AK8jet_sj2_pt,"AK8jet_sj2_pt");
  fTree->Branch("AK8jet_sj2_eta",&AK8jet_sj2_eta,"AK8jet_sj2_eta");
  fTree->Branch("AK8jet_sj2_phi",&AK8jet_sj2_phi,"AK8jet_sj2_phi");
  fTree->Branch("AK8jet_sj2_m",&AK8jet_sj2_m,"AK8jet_sj2_m");
  fTree->Branch("AK8jet_sj2_q",&AK8jet_sj2_q,"AK8jet_sj2_q");
  fTree->Branch("AK8_jetID_loose",&AK8_jetID_loose,"AK8_jetID_loose");
fTree->Branch("AK8jet_e3_b1",&AK8jet_e3_b1,"AK8jet_e3_b1");
fTree->Branch("AK8jet_e3_v1_b1",&AK8jet_e3_v1_b1,"AK8jet_e3_v1_b1");
fTree->Branch("AK8jet_e3_v2_b1",&AK8jet_e3_v2_b1,"AK8jet_e3_v2_b1");
fTree->Branch("AK8jet_e4_v1_b1",&AK8jet_e4_v1_b1,"AK8jet_e4_v1_b1");
fTree->Branch("AK8jet_e4_v2_b1",&AK8jet_e4_v2_b1,"AK8jet_e4_v2_b1");
fTree->Branch("AK8jet_e3_b2",&AK8jet_e3_b2,"AK8jet_e3_b2");
fTree->Branch("AK8jet_e3_v1_b2",&AK8jet_e3_v1_b2,"AK8jet_e3_v1_b2");
fTree->Branch("AK8jet_e3_v2_b2",&AK8jet_e3_v2_b2,"AK8jet_e3_v2_b2");
fTree->Branch("AK8jet_e4_v1_b2",&AK8jet_e4_v1_b2,"AK8jet_e4_v1_b2");
fTree->Branch("AK8jet_e4_v2_b2",&AK8jet_e4_v2_b2,"AK8jet_e4_v2_b2");
fTree->Branch("AK8jet_e2_sdb1",&AK8jet_e2_sdb1,"AK8jet_e2_sdb1");
fTree->Branch("AK8jet_e3_sdb1",&AK8jet_e3_sdb1,"AK8jet_e3_sdb1");
fTree->Branch("AK8jet_e3_v1_sdb1",&AK8jet_e3_v1_sdb1,"AK8jet_e3_v1_sdb1");
fTree->Branch("AK8jet_e3_v2_sdb1",&AK8jet_e3_v2_sdb1,"AK8jet_e3_v2_sdb1");
fTree->Branch("AK8jet_e4_v1_sdb1",&AK8jet_e4_v1_sdb1,"AK8jet_e4_v1_sdb1");
fTree->Branch("AK8jet_e4_v2_sdb1",&AK8jet_e4_v2_sdb1,"AK8jet_e4_v2_sdb1");
fTree->Branch("AK8jet_e2_sdb2",&AK8jet_e2_sdb2,"AK8jet_e2_sdb2");
fTree->Branch("AK8jet_e3_sdb2",&AK8jet_e3_sdb2,"AK8jet_e3_sdb2");
fTree->Branch("AK8jet_e3_v1_sdb2",&AK8jet_e3_v1_sdb2,"AK8jet_e3_v1_sdb2");
fTree->Branch("AK8jet_e3_v2_sdb2",&AK8jet_e3_v2_sdb2,"AK8jet_e3_v2_sdb2");
fTree->Branch("AK8jet_e4_v1_sdb2",&AK8jet_e4_v1_sdb2,"AK8jet_e4_v1_sdb2");
fTree->Branch("AK8jet_e4_v2_sdb2",&AK8jet_e4_v2_sdb2,"AK8jet_e4_v2_sdb2");
fTree->Branch("AK8jet_e2_sdb4",&AK8jet_e2_sdb4,"AK8jet_e2_sdb4");
fTree->Branch("AK8jet_e3_sdb4",&AK8jet_e3_sdb4,"AK8jet_e3_sdb4");
fTree->Branch("AK8jet_e3_v1_sdb4",&AK8jet_e3_v1_sdb4,"AK8jet_e3_v1_sdb4");
fTree->Branch("AK8jet_e3_v2_sdb4",&AK8jet_e3_v2_sdb4,"AK8jet_e3_v2_sdb4");
fTree->Branch("AK8jet_e4_v1_sdb4",&AK8jet_e4_v1_sdb4,"AK8jet_e4_v1_sdb4");
fTree->Branch("AK8jet_e4_v2_sdb4",&AK8jet_e4_v2_sdb4,"AK8jet_e4_v2_sdb4");
fTree->Branch("AK8jet_e2_sdb05",&AK8jet_e2_sdb05,"AK8jet_e2_sdb05");
fTree->Branch("AK8jet_e3_sdb05",&AK8jet_e3_sdb05,"AK8jet_e3_sdb05");
fTree->Branch("AK8jet_e3_v1_sdb05",&AK8jet_e3_v1_sdb05,"AK8jet_e3_v1_sdb05");
fTree->Branch("AK8jet_e3_v2_sdb05",&AK8jet_e3_v2_sdb05,"AK8jet_e3_v2_sdb05");
fTree->Branch("AK8jet_e4_v1_sdb05",&AK8jet_e4_v1_sdb05,"AK8jet_e4_v1_sdb05");
fTree->Branch("AK8jet_e4_v2_sdb05",&AK8jet_e4_v2_sdb05,"AK8jet_e4_v2_sdb05");
fTree->Branch("AK8jet_qjet",&AK8jet_qjet,"AK8jet_qjet");
  fTree->Branch("AK4_jetjet_pt",&AK4_jetjet_pt,"AK4_jetjet_pt");
  fTree->Branch("AK4_jetjet_mass",&AK4_jetjet_mass,"AK4_jetjet_mass");
  fTree->Branch("AK4_jetjet_deltaeta",&AK4_jetjet_deltaeta,"AK4_jetjet_deltaeta");
  fTree->Branch("AK4_jetjet_deltaphi",&AK4_jetjet_deltaphi,"AK4_jetjet_deltaphi");
  fTree->Branch("AK4_jetjet_deltar",&AK4_jetjet_deltar,"AK4_jetjet_deltar");
  fTree->Branch("PuppiAK4_jetjet_pt",&PuppiAK4_jetjet_pt,"PuppiAK4_jetjet_pt");
  fTree->Branch("PuppiAK4_jetjet_mass",&PuppiAK4_jetjet_mass,"PuppiAK4_jetjet_mass");
  fTree->Branch("PuppiAK4_jetjet_deltaeta",&PuppiAK4_jetjet_deltaeta,"PuppiAK4_jetjet_deltaeta");
  fTree->Branch("PuppiAK4_jetjet_deltaphi",&PuppiAK4_jetjet_deltaphi,"PuppiAK4_jetjet_deltaphi");
  fTree->Branch("PuppiAK4_jetjet_deltar",&PuppiAK4_jetjet_deltar,"PuppiAK4_jetjet_deltar");
  fTree->Branch("ungroomed_PuppiAK8_jet_pt",&ungroomed_PuppiAK8_jet_pt,"ungroomed_PuppiAK8_jet_pt/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_pt_jes_up",&ungroomed_PuppiAK8_jet_pt_jes_up,"ungroomed_PuppiAK8_jet_pt_jes_up/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_pt_jes_dn",&ungroomed_PuppiAK8_jet_pt_jes_dn,"ungroomed_PuppiAK8_jet_pt_jes_dn/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_pt_jer",&ungroomed_PuppiAK8_jet_pt_jer,"ungroomed_PuppiAK8_jet_pt_jer/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_pt_jer_up",&ungroomed_PuppiAK8_jet_pt_jer_up,"ungroomed_PuppiAK8_jet_pt_jer_up/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_pt_jer_dn",&ungroomed_PuppiAK8_jet_pt_jer_dn,"ungroomed_PuppiAK8_jet_pt_jer_dn/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_eta",&ungroomed_PuppiAK8_jet_eta,"ungroomed_PuppiAK8_jet_eta/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_eta_jes_up",&ungroomed_PuppiAK8_jet_eta_jes_up,"ungroomed_PuppiAK8_jet_eta_jes_up/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_eta_jes_dn",&ungroomed_PuppiAK8_jet_eta_jes_dn,"ungroomed_PuppiAK8_jet_eta_jes_dn/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_phi",&ungroomed_PuppiAK8_jet_phi,"ungroomed_PuppiAK8_jet_phi/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_phi_jes_up",&ungroomed_PuppiAK8_jet_phi_jes_up,"ungroomed_PuppiAK8_jet_phi_jes_up/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_phi_jes_dn",&ungroomed_PuppiAK8_jet_phi_jes_dn,"ungroomed_PuppiAK8_jet_phi_jes_dn/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_e",&ungroomed_PuppiAK8_jet_e,"ungroomed_PuppiAK8_jet_e/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_charge",&ungroomed_PuppiAK8_jet_charge,"ungroomed_PuppiAK8_jet_charge/F");
  fTree->Branch("PuppiAK8_jet_mass",&PuppiAK8_jet_mass,"PuppiAK8_jet_mass");
  fTree->Branch("ungroomed_PuppiAK8_jet_mass_jes_up",&ungroomed_PuppiAK8_jet_mass_jes_up,"ungroomed_PuppiAK8_jet_mass_jes_up/F");
  fTree->Branch("ungroomed_PuppiAK8_jet_mass_jes_dn",&ungroomed_PuppiAK8_jet_mass_jes_dn,"ungroomed_PuppiAK8_jet_mass_jes_dn/F");
  fTree->Branch("PuppiAK8_jet_mass_pr",&PuppiAK8_jet_mass_pr,"PuppiAK8_jet_mass_pr");
  fTree->Branch("PuppiAK8_jet_mass_pr_jes_up",&PuppiAK8_jet_mass_pr_jes_up,"PuppiAK8_jet_mass_pr_jes_up/F");
  fTree->Branch("PuppiAK8_jet_mass_pr_jes_dn",&PuppiAK8_jet_mass_pr_jes_dn,"PuppiAK8_jet_mass_pr_jes_dn/F");
  fTree->Branch("PuppiAK8_jet_mass_pr_jer",&PuppiAK8_jet_mass_pr_jer,"PuppiAK8_jet_mass_pr_jer/F");
  fTree->Branch("PuppiAK8_jet_mass_pr_jer_up",&PuppiAK8_jet_mass_pr_jer_up,"PuppiAK8_jet_mass_pr_jer_up/F");
  fTree->Branch("PuppiAK8_jet_mass_pr_jer_dn",&PuppiAK8_jet_mass_pr_jer_dn,"PuppiAK8_jet_mass_pr_jer_dn/F");
  fTree->Branch("PuppiAK8_jet_mass_so",&PuppiAK8_jet_mass_so,"PuppiAK8_jet_mass_so");
  fTree->Branch("PuppiAK8_jet_mass_so_corr",&PuppiAK8_jet_mass_so_corr,"PuppiAK8_jet_mass_so_corr");
  fTree->Branch("PuppiAK8_jet_pt_so",&PuppiAK8_jet_pt_so,"PuppiAK8_jet_pt_so");
  fTree->Branch("PuppiAK8_jet_mass_tr",&PuppiAK8_jet_mass_tr,"PuppiAK8_jet_mass_tr");
  fTree->Branch("PuppiAK8_jet_mass_fi",&PuppiAK8_jet_mass_fi,"PuppiAK8_jet_mass_fi");
  fTree->Branch("PuppiAK8_jet_tau2tau1",&PuppiAK8_jet_tau2tau1,"PuppiAK8_jet_tau2tau1");
  fTree->Branch("PuppiAK8_jet_sj1_pt" ,&PuppiAK8_jet_sj1_pt ,"PuppiAK8_jet_sj1_pt");
  fTree->Branch("PuppiAK8_jet_sj1_eta",&PuppiAK8_jet_sj1_eta,"PuppiAK8_jet_sj1_eta");
  fTree->Branch("PuppiAK8_jet_sj1_phi",&PuppiAK8_jet_sj1_phi,"PuppiAK8_jet_sj1_phi");
  fTree->Branch("PuppiAK8_jet_sj1_m"  ,&PuppiAK8_jet_sj1_m  ,"PuppiAK8_jet_sj1_m");
  fTree->Branch("PuppiAK8_jet_sj1_q"  ,&PuppiAK8_jet_sj1_q  ,"PuppiAK8_jet_sj1_q");
  fTree->Branch("PuppiAK8_jet_sj2_pt" ,&PuppiAK8_jet_sj2_pt ,"PuppiAK8_jet_sj2_pt");
  fTree->Branch("PuppiAK8_jet_sj2_eta",&PuppiAK8_jet_sj2_eta,"PuppiAK8_jet_sj2_eta");
  fTree->Branch("PuppiAK8_jet_sj2_phi",&PuppiAK8_jet_sj2_phi,"PuppiAK8_jet_sj2_phi");
  fTree->Branch("PuppiAK8_jet_sj2_m"  ,&PuppiAK8_jet_sj2_m  ,"PuppiAK8_jet_sj2_m");
  fTree->Branch("PuppiAK8_jet_sj2_q"  ,&PuppiAK8_jet_sj2_q  ,"PuppiAK8_jet_sj2_q");
  fTree->Branch("PuppiAK8_jetID_loose",&PuppiAK8_jetID_loose,"PuppiAK8_jetID_loose");
fTree->Branch("PuppiAK8jet_e3_b1",&PuppiAK8jet_e3_b1,"PuppiAK8jet_e3_b1");
fTree->Branch("PuppiAK8jet_e3_v1_b1",&PuppiAK8jet_e3_v1_b1,"PuppiAK8jet_e3_v1_b1");
fTree->Branch("PuppiAK8jet_e3_v2_b1",&PuppiAK8jet_e3_v2_b1,"PuppiAK8jet_e3_v2_b1");
fTree->Branch("PuppiAK8jet_e4_v1_b1",&PuppiAK8jet_e4_v1_b1,"PuppiAK8jet_e4_v1_b1");
fTree->Branch("PuppiAK8jet_e4_v2_b1",&PuppiAK8jet_e4_v2_b1,"PuppiAK8jet_e4_v2_b1");
fTree->Branch("PuppiAK8jet_e3_b2",&PuppiAK8jet_e3_b2,"PuppiAK8jet_e3_b2");
fTree->Branch("PuppiAK8jet_e3_v1_b2",&PuppiAK8jet_e3_v1_b2,"PuppiAK8jet_e3_v1_b2");
fTree->Branch("PuppiAK8jet_e3_v2_b2",&PuppiAK8jet_e3_v2_b2,"PuppiAK8jet_e3_v2_b2");
fTree->Branch("PuppiAK8jet_e4_v1_b2",&PuppiAK8jet_e4_v1_b2,"PuppiAK8jet_e4_v1_b2");
fTree->Branch("PuppiAK8jet_e4_v2_b2",&PuppiAK8jet_e4_v2_b2,"PuppiAK8jet_e4_v2_b2");
fTree->Branch("PuppiAK8jet_e2_sdb1",&PuppiAK8jet_e2_sdb1,"PuppiAK8jet_e2_sdb1");
fTree->Branch("PuppiAK8jet_e3_sdb1",&PuppiAK8jet_e3_sdb1,"PuppiAK8jet_e3_sdb1");
fTree->Branch("PuppiAK8jet_e3_v1_sdb1",&PuppiAK8jet_e3_v1_sdb1,"PuppiAK8jet_e3_v1_sdb1");
fTree->Branch("PuppiAK8jet_e3_v2_sdb1",&PuppiAK8jet_e3_v2_sdb1,"PuppiAK8jet_e3_v2_sdb1");
fTree->Branch("PuppiAK8jet_e4_v1_sdb1",&PuppiAK8jet_e4_v1_sdb1,"PuppiAK8jet_e4_v1_sdb1");
fTree->Branch("PuppiAK8jet_e4_v2_sdb1",&PuppiAK8jet_e4_v2_sdb1,"PuppiAK8jet_e4_v2_sdb1");
fTree->Branch("PuppiAK8jet_e2_sdb2",&PuppiAK8jet_e2_sdb2,"PuppiAK8jet_e2_sdb2");
fTree->Branch("PuppiAK8jet_e3_sdb2",&PuppiAK8jet_e3_sdb2,"PuppiAK8jet_e3_sdb2");
fTree->Branch("PuppiAK8jet_e3_v1_sdb2",&PuppiAK8jet_e3_v1_sdb2,"PuppiAK8jet_e3_v1_sdb2");
fTree->Branch("PuppiAK8jet_e3_v2_sdb2",&PuppiAK8jet_e3_v2_sdb2,"PuppiAK8jet_e3_v2_sdb2");
fTree->Branch("PuppiAK8jet_e4_v1_sdb2",&PuppiAK8jet_e4_v1_sdb2,"PuppiAK8jet_e4_v1_sdb2");
fTree->Branch("PuppiAK8jet_e4_v2_sdb2",&PuppiAK8jet_e4_v2_sdb2,"PuppiAK8jet_e4_v2_sdb2");
fTree->Branch("PuppiAK8jet_e2_sdb4",&PuppiAK8jet_e2_sdb4,"PuppiAK8jet_e2_sdb4");
fTree->Branch("PuppiAK8jet_e3_sdb4",&PuppiAK8jet_e3_sdb4,"PuppiAK8jet_e3_sdb4");
fTree->Branch("PuppiAK8jet_e3_v1_sdb4",&PuppiAK8jet_e3_v1_sdb4,"PuppiAK8jet_e3_v1_sdb4");
fTree->Branch("PuppiAK8jet_e3_v2_sdb4",&PuppiAK8jet_e3_v2_sdb4,"PuppiAK8jet_e3_v2_sdb4");
fTree->Branch("PuppiAK8jet_e4_v1_sdb4",&PuppiAK8jet_e4_v1_sdb4,"PuppiAK8jet_e4_v1_sdb4");
fTree->Branch("PuppiAK8jet_e4_v2_sdb4",&PuppiAK8jet_e4_v2_sdb4,"PuppiAK8jet_e4_v2_sdb4");
fTree->Branch("PuppiAK8jet_e2_sdb05",&PuppiAK8jet_e2_sdb05,"PuppiAK8jet_e2_sdb05");
fTree->Branch("PuppiAK8jet_e3_sdb05",&PuppiAK8jet_e3_sdb05,"PuppiAK8jet_e3_sdb05");
fTree->Branch("PuppiAK8jet_e3_v1_sdb05",&PuppiAK8jet_e3_v1_sdb05,"PuppiAK8jet_e3_v1_sdb05");
fTree->Branch("PuppiAK8jet_e3_v2_sdb05",&PuppiAK8jet_e3_v2_sdb05,"PuppiAK8jet_e3_v2_sdb05");
fTree->Branch("PuppiAK8jet_e4_v1_sdb05",&PuppiAK8jet_e4_v1_sdb05,"PuppiAK8jet_e4_v1_sdb05");
fTree->Branch("PuppiAK8jet_e4_v2_sdb05",&PuppiAK8jet_e4_v2_sdb05,"PuppiAK8jet_e4_v2_sdb05");
fTree->Branch("PuppiAK8jet_qjet",&PuppiAK8jet_qjet,"PuppiAK8jet_qjet");
  fTree->Branch("AK4_jet1_pt",&AK4_jet1_pt,"AK4_jet1_pt/F");
  fTree->Branch("AK4_jet1_pt_jes_up",&AK4_jet1_pt_jes_up,"AK4_jet1_pt_jes_up/F");
  fTree->Branch("AK4_jet1_pt_jes_dn",&AK4_jet1_pt_jes_dn,"AK4_jet1_pt_jes_dn/F");
  fTree->Branch("AK4_jet1_pt_jer",&AK4_jet1_pt_jer,"AK4_jet1_pt_jer/F");
  fTree->Branch("AK4_jet1_pt_jer_up",&AK4_jet1_pt_jer_up,"AK4_jet1_pt_jer_up/F");
  fTree->Branch("AK4_jet1_pt_jer_dn",&AK4_jet1_pt_jer_dn,"AK4_jet1_pt_jer_dn/F");
  fTree->Branch("AK4_jet1_eta",&AK4_jet1_eta,"AK4_jet1_eta/F");
  fTree->Branch("AK4_jet1_phi",&AK4_jet1_phi,"AK4_jet1_phi/F");
  fTree->Branch("AK4_jet1_e",&AK4_jet1_e,"AK4_jet1_e/F");
  fTree->Branch("AK4_jet2_pt",&AK4_jet2_pt,"AK4_jet2_pt/F");
  fTree->Branch("AK4_jet2_pt_jes_up",&AK4_jet2_pt_jes_up,"AK4_jet2_pt_jes_up/F");
  fTree->Branch("AK4_jet2_pt_jes_dn",&AK4_jet2_pt_jes_dn,"AK4_jet2_pt_jes_dn/F");
  fTree->Branch("AK4_jet2_pt_jer",&AK4_jet2_pt_jer,"AK4_jet2_pt_jer/F");
  fTree->Branch("AK4_jet2_pt_jer_up",&AK4_jet2_pt_jer_up,"AK4_jet2_pt_jer_up/F");
  fTree->Branch("AK4_jet2_pt_jer_dn",&AK4_jet2_pt_jer_dn,"AK4_jet2_pt_jer_dn/F");
  fTree->Branch("AK4_jet2_eta",&AK4_jet2_eta,"AK4_jet2_eta/F");
  fTree->Branch("AK4_jet2_phi",&AK4_jet2_phi,"AK4_jet2_phi/F");
  fTree->Branch("AK4_jet2_e",&AK4_jet2_e,"AK4_jet2_e/F");
  fTree->Branch("PuppiAK4_jet1_pt",&PuppiAK4_jet1_pt,"PuppiAK4_jet1_pt/F");
  fTree->Branch("PuppiAK4_jet1_pt_jes_up",&PuppiAK4_jet1_pt_jes_up,"PuppiAK4_jet1_pt_jes_up/F");
  fTree->Branch("PuppiAK4_jet1_pt_jes_dn",&PuppiAK4_jet1_pt_jes_dn,"PuppiAK4_jet1_pt_jes_dn/F");
  fTree->Branch("PuppiAK4_jet1_pt_jer",&PuppiAK4_jet1_pt_jer,"PuppiAK4_jet1_pt_jer/F");
  fTree->Branch("PuppiAK4_jet1_pt_jer_up",&PuppiAK4_jet1_pt_jer_up,"PuppiAK4_jet1_pt_jer_up/F");
  fTree->Branch("PuppiAK4_jet1_pt_jer_dn",&PuppiAK4_jet1_pt_jer_dn,"PuppiAK4_jet1_pt_jer_dn/F");
  fTree->Branch("PuppiAK4_jet1_eta",&PuppiAK4_jet1_eta,"PuppiAK4_jet1_eta/F");
  fTree->Branch("PuppiAK4_jet1_phi",&PuppiAK4_jet1_phi,"PuppiAK4_jet1_phi/F");
  fTree->Branch("PuppiAK4_jet1_e",&PuppiAK4_jet1_e,"PuppiAK4_jet1_e/F");
  fTree->Branch("PuppiAK4_jet2_pt",&PuppiAK4_jet2_pt,"PuppiAK4_jet2_pt/F");
  fTree->Branch("PuppiAK4_jet2_pt_jes_up",&PuppiAK4_jet2_pt_jes_up,"PuppiAK4_jet2_pt_jes_up/F");
  fTree->Branch("PuppiAK4_jet2_pt_jes_dn",&PuppiAK4_jet2_pt_jes_dn,"PuppiAK4_jet2_pt_jes_dn/F");
  fTree->Branch("PuppiAK4_jet2_pt_jer",&PuppiAK4_jet2_pt_jer,"PuppiAK4_jet2_pt_jer/F");
  fTree->Branch("PuppiAK4_jet2_pt_jer_up",&PuppiAK4_jet2_pt_jer_up,"PuppiAK4_jet2_pt_jer_up/F");
  fTree->Branch("PuppiAK4_jet2_pt_jer_dn",&PuppiAK4_jet2_pt_jer_dn,"PuppiAK4_jet2_pt_jer_dn/F");
  fTree->Branch("PuppiAK4_jet2_eta",&PuppiAK4_jet2_eta,"PuppiAK4_jet2_eta/F");
  fTree->Branch("PuppiAK4_jet2_phi",&PuppiAK4_jet2_phi,"PuppiAK4_jet2_phi/F");
  fTree->Branch("PuppiAK4_jet2_e",&PuppiAK4_jet2_e,"PuppiAK4_jet2_e/F");
  fTree->Branch("ttb_ungroomed_jet_pt",&ttb_ungroomed_jet_pt,"ttb_ungroomed_jet_pt/F");
  fTree->Branch("ttb_ungroomed_jet_eta",&ttb_ungroomed_jet_eta,"ttb_ungroomed_jet_eta/F");
  fTree->Branch("ttb_ungroomed_jet_phi",&ttb_ungroomed_jet_phi,"ttb_ungroomed_jet_phi/F");
  fTree->Branch("ttb_ungroomed_jet_e",&ttb_ungroomed_jet_e,"ttb_ungroomed_jet_e/F");
  fTree->Branch("ttb_jet_mass_pr",&ttb_jet_mass_pr,"ttb_jet_mass_pr");
  fTree->Branch("ttb_jet_mass_so",&ttb_jet_mass_so,"ttb_jet_mass_so");
  fTree->Branch("ttb_jet_pt_so",&ttb_jet_pt_so,"ttb_jet_pt_so");
  fTree->Branch("ttb_jet_mass_tr",&ttb_jet_mass_tr,"ttb_jet_mass_tr");
  fTree->Branch("ttb_jet_mass_fi",&ttb_jet_mass_fi,"ttb_jet_mass_fi");
  fTree->Branch("ttb_jet_tau2tau1",&ttb_jet_tau2tau1,"ttb_jet_tau2tau1");
  fTree->Branch("ttb_deltaeta_lak8jet",&ttb_deltaeta_lak8jet,"ttb_deltaeta_lak8jet/F");
  fTree->Branch("isGen",&isGen,"isGen/F");
  fTree->Branch("lep_pt_gen",&lep_pt_gen,"lep_pt_gen");
  fTree->Branch("lep_eta_gen",&lep_eta_gen,"lep_eta_gen");
  fTree->Branch("W_pt_gen",&W_pt_gen,"W_pt_gen");
  fTree->Branch("W_pz_gen",&W_pz_gen,"W_pz_gen");
  fTree->Branch("W_rap_gen",&W_rap_gen,"W_rap_gen");
  fTree->Branch("nu_pz_gen",&nu_pz_gen,"nu_pz_gen");
  fTree->Branch("nu_pt_gen",&nu_pt_gen,"nu_pt_gen");
  fTree->Branch("nu_phi_gen",&nu_phi_gen,"nu_phi_gen");
  fTree->Branch("nu_eta_gen",&nu_eta_gen,"nu_eta_gen");
  fTree->Branch("hadW_pt_gen",&hadW_pt_gen,"hadW_pt_gen");
  fTree->Branch("hadW_eta_gen",&hadW_eta_gen,"hadW_eta_gen");
  fTree->Branch("hadW_phi_gen",&hadW_phi_gen,"hadW_phi_gen");
  fTree->Branch("hadW_e_gen",&hadW_e_gen,"hadW_e_gen");
  fTree->Branch("hadW_m_gen",&hadW_m_gen,"hadW_m_gen");
  fTree->Branch("lepW_pt_gen",&lepW_pt_gen,"lepW_pt_gen");
  fTree->Branch("lepW_eta_gen",&lepW_eta_gen,"lepW_eta_gen");
  fTree->Branch("lepW_phi_gen",&lepW_phi_gen,"lepW_phi_gen");
  fTree->Branch("lepW_e_gen",&lepW_e_gen,"lepW_e_gen");
  fTree->Branch("lepW_m_gen",&lepW_m_gen,"lepW_m_gen");
  fTree->Branch("WW_mass_gen",&WW_mass_gen,"WW_mass_gen");
  fTree->Branch("WW_mT_gen",&WW_mT_gen,"WW_mT_gen");
  fTree->Branch("WW_pT_gen",&WW_pT_gen,"WW_pT_gen");
  fTree->Branch("AK8_pt_gen",&AK8_pt_gen,"AK8_pt_gen");
  fTree->Branch("AK8_eta_gen",&AK8_eta_gen,"AK8_eta_gen");
  fTree->Branch("AK8_phi_gen",&AK8_phi_gen,"AK8_phi_gen");
  fTree->Branch("AK8_e_gen",&AK8_e_gen,"AK8_e_gen");
  fTree->Branch("AK8_mass_gen",&AK8_mass_gen,"AK8_mass_gen");
  fTree->Branch("AK8_pruned_mass_gen",&AK8_pruned_mass_gen,"AK8_pruned_mass_gen");
  fTree->Branch("AK8_softdrop_mass_gen",&AK8_softdrop_mass_gen,"AK8_softdrop_mass_gen");
  fTree->Branch("AK8_softdrop_pt_gen",&AK8_softdrop_pt_gen,"AK8_softdrop_pt_gen");
  fTree->Branch("AK4_1_pt_gen",&AK4_1_pt_gen,"AK4_1_pt_gen/F");
  fTree->Branch("AK4_1_eta_gen",&AK4_1_eta_gen,"AK4_1_eta_gen/F");
  fTree->Branch("AK4_1_phi_gen",&AK4_1_phi_gen,"AK4_1_phi_gen/F");
  fTree->Branch("AK4_1_e_gen",&AK4_1_e_gen,"AK4_1_e_gen/F");
  fTree->Branch("AK4_1_mass_gen",&AK4_1_mass_gen,"AK4_1_mass_gen/F");
  fTree->Branch("AK4_2_pt_gen",&AK4_2_pt_gen,"AK4_2_pt_gen/F");
  fTree->Branch("AK4_2_eta_gen",&AK4_2_eta_gen,"AK4_2_eta_gen/F");
  fTree->Branch("AK4_2_phi_gen",&AK4_2_phi_gen,"AK4_2_phi_gen/F");
  fTree->Branch("AK4_2_e_gen",&AK4_2_e_gen,"AK4_2_e_gen/F");
  fTree->Branch("AK4_2_mass_gen",&AK4_2_mass_gen,"AK4_2_mass_gen/F");
  fTree->Branch("AK4_jj_DeltaEta_gen",&AK4_jj_DeltaEta_gen,"AK4_jj_DeltaEta_gen/F");
  fTree->Branch("AK4_jj_mass_gen",&AK4_jj_mass_gen,"AK4_jj_mass_gen/F");
  fTree->Branch("AK4_DR_GENRECO_11", &AK4_DR_GENRECO_11 , "AK4_DR_GENRECO_11/F");
  fTree->Branch("AK4_DR_GENRECO_12", &AK4_DR_GENRECO_12 , "AK4_DR_GENRECO_12/F");
  fTree->Branch("AK4_DR_GENRECO_21", &AK4_DR_GENRECO_21 , "AK4_DR_GENRECO_21/F");
  fTree->Branch("AK4_DR_GENRECO_22", &AK4_DR_GENRECO_22 , "AK4_DR_GENRECO_22/F");
  fTree->Branch("AK4Puppi_DR_GENRECO_11", &AK4Puppi_DR_GENRECO_11 , "AK4Puppi_DR_GENRECO_11/F");
  fTree->Branch("AK4Puppi_DR_GENRECO_12", &AK4Puppi_DR_GENRECO_12 , "AK4Puppi_DR_GENRECO_12/F");
  fTree->Branch("AK4Puppi_DR_GENRECO_21", &AK4Puppi_DR_GENRECO_21 , "AK4Puppi_DR_GENRECO_21/F");
  fTree->Branch("AK4Puppi_DR_GENRECO_22", &AK4Puppi_DR_GENRECO_22 , "AK4Puppi_DR_GENRECO_22/F");
//  fTree->Branch("AK4_BIG_gen_mass",&AK4_BIG_gen_mass,"AK4_BIG_gen_mass/F");
  fTree->Branch("deltaR_Wjet_GenReco",&deltaR_Wjet_GenReco,"deltaR_Wjet_GenReco/F");
  fTree->Branch("deltaR_lak8jet",&deltaR_lak8jet,"deltaR_lak8jet/F");
  fTree->Branch("deltaphi_METak8jet",&deltaphi_METak8jet,"deltaphi_METak8jet/F");
  fTree->Branch("deltaphi_Vak8jet",&deltaphi_Vak8jet,"deltaphi_Vak8jet/F");
  fTree->Branch("deltaR_lPuppiak8jet",&deltaR_lPuppiak8jet,"deltaR_lPuppiak8jet/F");
  fTree->Branch("deltaphi_METPuppiak8jet",&deltaphi_METPuppiak8jet,"deltaphi_METPuppiak8jet/F");
  fTree->Branch("deltaphi_VPuppiak8jet",&deltaphi_VPuppiak8jet,"deltaphi_VPuppiak8jet/F");
  fTree->Branch("deltaR_lak4jetjet",&deltaR_lak4jetjet,"deltaR_lak4jetjet/F");
  fTree->Branch("deltaphi_METak4jetjet",&deltaphi_METak4jetjet,"deltaphi_METak4jetjet/F");
  fTree->Branch("deltaphi_Vak4jetjet",&deltaphi_Vak4jetjet,"deltaphi_Vak4jetjet/F");
  fTree->Branch("deltaR_lPuppiak4jetjet",&deltaR_lPuppiak4jetjet,"deltaR_lPuppiak4jetjet/F");
  fTree->Branch("deltaphi_METPuppiak4jetjet",&deltaphi_METPuppiak4jetjet,"deltaphi_METPuppiak4jetjet/F");
  fTree->Branch("deltaphi_VPuppiak4jetjet",&deltaphi_VPuppiak4jetjet,"deltaphi_VPuppiak4jetjet/F");
  fTree->Branch("deltaR_l2Puppiak8jet",&deltaR_l2Puppiak8jet,"deltaR_l2Puppiak8jet/F");
  fTree->Branch("deltaR_VLepPuppiak8jet",&deltaR_VLepPuppiak8jet,"deltaR_VLepPuppiak8jet/F");
  fTree->Branch("v_pt_type0",&v_pt_type0,"v_pt_type0/F");
  fTree->Branch("v_pt_type2",&v_pt_type2,"v_pt_type2/F");
  fTree->Branch("v_pt_run2",&v_pt_run2,"v_pt_run2/F");
  fTree->Branch("v_eta_type2",&v_eta_type2,"v_eta_type2/F");
  fTree->Branch("v_eta_type0",&v_eta_type0,"v_eta_type0/F");
  fTree->Branch("v_eta_run2",&v_eta_run2,"v_eta_run2/F");
  fTree->Branch("v_phi",&v_phi,"v_phi/F");
  fTree->Branch("v_mt_type2",&v_mt_type2,"v_mt_type2/F");
  fTree->Branch("v_mt_type0",&v_mt_type0,"v_mt_type0/F");
  fTree->Branch("v_mt_run2",&v_mt_run2,"v_mt_run2/F");
  fTree->Branch("v_mass_type2", &v_mass_type2, "v_mass_type2/F");
  fTree->Branch("v_mass_type0", &v_mass_type0, "v_mass_type0/F");
  fTree->Branch("v_mass_run2", &v_mass_run2, "v_mass_run2/F");
  fTree->Branch("v_pt_type0_jer_up",&v_pt_type0_jer_up,"v_pt_type0_jer_up/F");
  fTree->Branch("v_eta_type0_jer_up",&v_eta_type0_jer_up,"v_eta_type0_jer_up/F");
  fTree->Branch("v_mt_type0_jer_up",&v_mt_type0_jer_up,"v_mt_type0_jer_up/F");
  fTree->Branch("v_mass_type0_jer_up",&v_mass_type0_jer_up,"v_mass_type0_jer_up/F");
  fTree->Branch("v_pt_type0_jer_dn",&v_pt_type0_jer_dn,"v_pt_type0_jer_dn/F");
  fTree->Branch("v_eta_type0_jer_dn",&v_eta_type0_jer_dn,"v_eta_type0_jer_dn/F");
  fTree->Branch("v_mt_type0_jer_dn",&v_mt_type0_jer_dn,"v_mt_type0_jer_dn/F");
  fTree->Branch("v_mass_type0_jer_dn",&v_mass_type0_jer_dn,"v_mass_type0_jer_dn/F");
  fTree->Branch("v_pt_type0_jes_up",&v_pt_type0_jes_up,"v_pt_type0_jes_up/F");
  fTree->Branch("v_eta_type0_jes_up",&v_eta_type0_jes_up,"v_eta_type0_jes_up/F");
  fTree->Branch("v_mt_type0_jes_up",&v_mt_type0_jes_up,"v_mt_type0_jes_up/F");
  fTree->Branch("v_mass_type0_jes_up",&v_mass_type0_jes_up,"v_mass_type0_jes_up/F");
  fTree->Branch("v_pt_type0_jes_dn",&v_pt_type0_jes_dn,"v_pt_type0_jes_dn/F");
  fTree->Branch("v_eta_type0_jes_dn",&v_eta_type0_jes_dn,"v_eta_type0_jes_dn/F");
  fTree->Branch("v_mt_type0_jes_dn",&v_mt_type0_jes_dn,"v_mt_type0_jes_dn/F");
  fTree->Branch("v_mass_type0_jes_dn",&v_mass_type0_jes_dn,"v_mass_type0_jes_dn/F");
  fTree->Branch("v_puppi_pt_type2",&v_puppi_pt_type2,"v_puppi_pt_type2/F");
  fTree->Branch("v_puppi_pt_type0",&v_puppi_pt_type0,"v_puppi_pt_type0/F");
  fTree->Branch("v_puppi_pt_run2",&v_puppi_pt_run2,"v_puppi_pt_run2/F");
  fTree->Branch("v_puppi_eta_type2",&v_puppi_eta_type2,"v_puppi_eta_type2/F");
  fTree->Branch("v_puppi_eta_type0",&v_puppi_eta_type0,"v_puppi_eta_type0/F");
  fTree->Branch("v_puppi_eta_run2",&v_puppi_eta_run2,"v_puppi_eta_run2/F");
  fTree->Branch("v_puppi_phi",&v_puppi_phi,"v_puppi_phi/F");
  fTree->Branch("v_puppi_mt_type2",&v_puppi_mt_type2,"v_puppi_mt_type2/F");
  fTree->Branch("v_puppi_mt_type0",&v_puppi_mt_type0,"v_puppi_mt_type0/F");
  fTree->Branch("v_puppi_mt_run2",&v_puppi_mt_run2,"v_puppi_mt_run2/F");
  fTree->Branch("v_puppi_mass_type2", &v_puppi_mass_type2, "v_puppi_mass_type2/F");
  fTree->Branch("v_puppi_mass_type0", &v_puppi_mass_type0, "v_puppi_mass_type0/F");
  fTree->Branch("v_puppi_mass_run2", &v_puppi_mass_run2, "v_puppi_mass_run2/F");
  fTree->Branch("mass_lvj_type0",&mass_lvj_type0,"mass_lvj_type0/F");
  fTree->Branch("mass_lvj_type0_met_jes_up",&mass_lvj_type0_met_jes_up,"mass_lvj_type0_met_jes_up/F");
  fTree->Branch("mass_lvj_type0_met_jes_dn",&mass_lvj_type0_met_jes_dn,"mass_lvj_type0_met_jes_dn/F");
  fTree->Branch("mass_lvj_type0_met_jer_up",&mass_lvj_type0_met_jer_up,"mass_lvj_type0_met_jer_up/F");
  fTree->Branch("mass_lvj_type0_met_jer_dn",&mass_lvj_type0_met_jer_dn,"mass_lvj_type0_met_jer_dn/F");
  fTree->Branch("mass_lvj_type0_met_jer",&mass_lvj_type0_met_jer,"mass_lvj_type0_met_jer/F");
  fTree->Branch("mass_lvj_type0_met_PuppiAK8_jes_up",&mass_lvj_type0_met_PuppiAK8_jes_up,"mass_lvj_type0_met_PuppiAK8_jes_up/F");
  fTree->Branch("mass_lvj_type0_met_PuppiAK8_jes_dn",&mass_lvj_type0_met_PuppiAK8_jes_dn,"mass_lvj_type0_met_PuppiAK8_jes_dn/F");
  fTree->Branch("mass_lvj_type2",&mass_lvj_type2,"mass_lvj_type2/F");
  fTree->Branch("mass_lvj_run2",&mass_lvj_run2,"mass_lvj_run2/F");
  fTree->Branch("mass_lvj_type0_PuppiAK8",&mass_lvj_type0_PuppiAK8,"mass_lvj_type0_PuppiAK8/F");
  fTree->Branch("mass_lvj_type2_PuppiAK8",&mass_lvj_type2_PuppiAK8,"mass_lvj_type2_PuppiAK8/F");
  fTree->Branch("mass_lvj_run2_PuppiAK8",&mass_lvj_run2_PuppiAK8,"mass_lvj_run2_PuppiAK8/F");
  fTree->Branch("mt_lvj_type0_PuppiAK8",&mt_lvj_type0_PuppiAK8,"mt_lvj_type0_PuppiAK8/F");
  fTree->Branch("mt_lvj_type2_PuppiAK8",&mt_lvj_type2_PuppiAK8,"mt_lvj_type2_PuppiAK8/F");
  fTree->Branch("mt_lvj_run2_PuppiAK8", &mt_lvj_run2_PuppiAK8, "mt_lvj_run2_PuppiAK8/F");
  fTree->Branch("pt_lvj_type0_PuppiAK8",&pt_lvj_type0_PuppiAK8,"pt_lvj_type0_PuppiAK8/F");
  fTree->Branch("pt_lvj_type2_PuppiAK8",&pt_lvj_type2_PuppiAK8,"pt_lvj_type2_PuppiAK8/F");
  fTree->Branch("pt_lvj_run2_PuppiAK8", &pt_lvj_run2_PuppiAK8, "pt_lvj_run2_PuppiAK8/F");
  fTree->Branch("eta_lvj_type0_PuppiAK8",&eta_lvj_type0_PuppiAK8,"eta_lvj_type0_PuppiAK8/F");
  fTree->Branch("eta_lvj_type2_PuppiAK8",&eta_lvj_type2_PuppiAK8,"eta_lvj_type2_PuppiAK8/F");
  fTree->Branch("eta_lvj_run2_PuppiAK8", &eta_lvj_run2_PuppiAK8, "eta_lvj_run2_PuppiAK8/F");
  fTree->Branch("rapidity_lvj_type0_PuppiAK8",&rapidity_lvj_type0_PuppiAK8,"rapidity_lvj_type0_PuppiAK8/F");
  fTree->Branch("rapidity_lvj_type2_PuppiAK8",&rapidity_lvj_type2_PuppiAK8,"rapidity_lvj_type2_PuppiAK8/F");
  fTree->Branch("rapidity_lvj_run2_PuppiAK8", &rapidity_lvj_run2_PuppiAK8, "rapidity_lvj_run2_PuppiAK8/F");
  fTree->Branch("phi_lvj_type0_PuppiAK8",&phi_lvj_type0_PuppiAK8,"phi_lvj_type0_PuppiAK8/F");
  fTree->Branch("phi_lvj_type2_PuppiAK8",&phi_lvj_type2_PuppiAK8,"phi_lvj_type2_PuppiAK8/F");
  fTree->Branch("phi_lvj_run2_PuppiAK8", &phi_lvj_run2_PuppiAK8, "phi_lvj_run2_PuppiAK8/F");
  fTree->Branch("energy_lvj_type0_PuppiAK8",&energy_lvj_type0_PuppiAK8,"energy_lvj_type0_PuppiAK8/F");
  fTree->Branch("energy_lvj_type2_PuppiAK8",&energy_lvj_type2_PuppiAK8,"energy_lvj_type2_PuppiAK8/F");
  fTree->Branch("energy_lvj_run2_PuppiAK8", &energy_lvj_run2_PuppiAK8, "energy_lvj_run2_PuppiAK8/F");
  fTree->Branch("mass_lvjj_type0_AK4",&mass_lvjj_type0_AK4,"mass_lvjj_type0_AK4/F");
  fTree->Branch("mass_lvjj_type0_met_jes_up_AK4",&mass_lvjj_type0_met_jes_up_AK4,"mass_lvjj_type0_met_jes_up_AK4/F");
  fTree->Branch("mass_lvjj_type0_met_jes_dn_AK4",&mass_lvjj_type0_met_jes_dn_AK4,"mass_lvjj_type0_met_jes_dn_AK4/F");
  fTree->Branch("mass_lvjj_type2_AK4",&mass_lvjj_type2_AK4,"mass_lvjj_type2_AK4/F");
  fTree->Branch("mass_lvjj_run2_AK4",&mass_lvjj_run2_AK4,"mass_lvjj_run2_AK4/F");
  fTree->Branch("mass_lvjj_type0_PuppiAK4",&mass_lvjj_type0_PuppiAK4,"mass_lvjj_type0_PuppiAK4/F");
  fTree->Branch("mass_lvjj_type0_met_jes_up_PuppiAK4",&mass_lvjj_type0_met_jes_up_PuppiAK4,"mass_lvjj_type0_met_jes_up_PuppiAK4/F");
  fTree->Branch("mass_lvjj_type0_met_jes_dn_PuppiAK4",&mass_lvjj_type0_met_jes_dn_PuppiAK4,"mass_lvjj_type0_met_jes_dn_PuppiAK4/F");
  fTree->Branch("mass_lvjj_type2_PuppiAK4",&mass_lvjj_type2_PuppiAK4,"mass_lvjj_type2_PuppiAK4/F");
  fTree->Branch("mass_lvjj_run2_PuppiAK4",&mass_lvjj_run2_PuppiAK4,"mass_lvjj_run2_PuppiAK4/F");
  fTree->Branch("mass_llj_PuppiAK8",&mass_llj_PuppiAK8,"mass_llj_PuppiAK8/F");
  fTree->Branch("pt_llj_PuppiAK8",&pt_llj_PuppiAK8,"pt_llj_PuppiAK8/F");
  fTree->Branch("eta_llj_PuppiAK8",&eta_llj_PuppiAK8,"eta_llj_PuppiAK8/F");
  fTree->Branch("phi_llj_PuppiAK8",&phi_llj_PuppiAK8,"phi_llj_PuppiAK8/F");
  fTree->Branch("njets",&njets,"njets/I");
  fTree->Branch("njetsPuppi",&njetsPuppi,"njetsPuppi/I");
  fTree->Branch("nGoodAK8jets",&nGoodAK8jets,"nGoodAK8jets/I");
  fTree->Branch("njets_unmerged",&njets_unmerged,"njets_unmerged/I");
  fTree->Branch("njetsPuppi_unmerged",&njetsPuppi_unmerged,"njetsPuppi_unmerged/I");
  fTree->Branch("nBTagJet_loose",&nBTagJet_loose,"nBTagJet_loose/I");
  fTree->Branch("nBTagJet_medium",&nBTagJet_medium,"nBTagJet_medium/I");
  fTree->Branch("nBTagJet_tight",&nBTagJet_tight,"nBTagJet_tight/I");
  fTree->Branch("nBTagJetPuppi_loose",&nBTagJetPuppi_loose,"nBTagJetPuppi_loose/I");
  fTree->Branch("nBTagJetPuppi_medium",&nBTagJetPuppi_medium,"nBTagJetPuppi_medium/I");
  fTree->Branch("nBTagJetPuppi_tight",&nBTagJetPuppi_tight,"nBTagJetPuppi_tight/I");
  fTree->Branch("nBTagJet_loose_unmerged",&nBTagJet_loose_unmerged,"nBTagJet_loose_unmerged/I");
  fTree->Branch("nBTagJet_medium_unmerged",&nBTagJet_medium_unmerged,"nBTagJet_medium_unmerged/I");
  fTree->Branch("nBTagJet_tight_unmerged",&nBTagJet_tight_unmerged,"nBTagJet_tight_unmerged/I");
  fTree->Branch("nBTagJetPuppi_loose_unmerged",&nBTagJetPuppi_loose_unmerged,"nBTagJetPuppi_loose_unmerged/I");
  fTree->Branch("nBTagJetPuppi_medium_unmerged",&nBTagJetPuppi_medium_unmerged,"nBTagJetPuppi_medium_unmerged/I");
  fTree->Branch("nBTagJetPuppi_tight_unmerged",&nBTagJetPuppi_tight_unmerged,"nBTagJetPuppi_tight_unmerged/I");
  fTree->Branch("btag0Wgt",&btag0Wgt,"btag0Wgt/F");
  fTree->Branch("btag1Wgt",&btag1Wgt,"btag1Wgt/F");
  fTree->Branch("btag2Wgt",&btag2Wgt,"btag2Wgt/F");
  fTree->Branch("btag0WgtUpHF",&btag0WgtUpHF,"btag0WgtUpHF/F");
  fTree->Branch("btag0WgtDownHF",&btag0WgtDownHF,"btag0WgtDownHF/F");
  fTree->Branch("btag0WgtUpLF",&btag0WgtUpLF,"btag0WgtUpLF/F");
  fTree->Branch("btag0WgtDownLF",&btag0WgtDownLF,"btag0WgtDownLF/F");
  fTree->Branch("btag1WgtUpHF",&btag1WgtUpHF,"btag1WgtUpHF/F");
  fTree->Branch("btag1WgtDownHF",&btag1WgtDownHF,"btag1WgtDownHF/F");
  fTree->Branch("btag1WgtUpLF",&btag1WgtUpLF,"btag1WgtUpLF/F");
  fTree->Branch("btag1WgtDownLF",&btag1WgtDownLF,"btag1WgtDownLF/F");
  fTree->Branch("mass_leptonic_closerjet",&mass_leptonic_closerjet,"mass_leptonic_closerjet/F");
  fTree->Branch("mass_ungroomedjet_closerjet",&mass_ungroomedjet_closerjet,"mass_ungroomedjet_closerjet/F");
  fTree->Branch("AK8_closerjet_pt",&AK8_closerjet_pt,"AK8_closerjet_pt/F");
  fTree->Branch("AK8_closerjet_eta",&AK8_closerjet_eta,"AK8_closerjet_eta/F");
  fTree->Branch("AK8_closerjet_phi",&AK8_closerjet_phi,"AK8_closerjet_phi/F");
  fTree->Branch("AK8_closerjet_e",&AK8_closerjet_e,"AK8_closerjet_e/F");
  fTree->Branch("vbf_maxpt_j1_pt",&vbf_maxpt_j1_pt,"vbf_maxpt_j1_pt/F");
  fTree->Branch("vbf_maxpt_j1_pt_jes_up",&vbf_maxpt_j1_pt_jes_up,"vbf_maxpt_j1_pt_jes_up/F");
  fTree->Branch("vbf_maxpt_j1_pt_jes_dn",&vbf_maxpt_j1_pt_jes_dn,"vbf_maxpt_j1_pt_jes_dn/F");
  fTree->Branch("vbf_maxpt_j1_pt_jer",&vbf_maxpt_j1_pt_jer,"vbf_maxpt_j1_pt_jer/F");
  fTree->Branch("vbf_maxpt_j1_pt_jer_up",&vbf_maxpt_j1_pt_jer_up,"vbf_maxpt_j1_pt_jer_up/F");
  fTree->Branch("vbf_maxpt_j1_pt_jer_dn",&vbf_maxpt_j1_pt_jer_dn,"vbf_maxpt_j1_pt_jer_dn/F");
  fTree->Branch("vbf_maxpt_j1_eta",&vbf_maxpt_j1_eta,"vbf_maxpt_j1_eta/F");
  fTree->Branch("vbf_maxpt_j1_eta_jes_up",&vbf_maxpt_j1_eta_jes_up,"vbf_maxpt_j1_eta_jes_up/F");
  fTree->Branch("vbf_maxpt_j1_eta_jes_dn",&vbf_maxpt_j1_eta_jes_dn,"vbf_maxpt_j1_eta_jes_dn/F");
  fTree->Branch("vbf_maxpt_j1_eta_jer",&vbf_maxpt_j1_eta_jer,"vbf_maxpt_j1_eta_jer/F");
  fTree->Branch("vbf_maxpt_j1_eta_jer_up",&vbf_maxpt_j1_eta_jer_up,"vbf_maxpt_j1_eta_jer_up/F");
  fTree->Branch("vbf_maxpt_j1_eta_jer_dn",&vbf_maxpt_j1_eta_jer_dn,"vbf_maxpt_j1_eta_jer_dn/F");
  fTree->Branch("vbf_maxpt_j1_phi",&vbf_maxpt_j1_phi,"vbf_maxpt_j1_phi/F");
  fTree->Branch("vbf_maxpt_j1_phi_jes_up",&vbf_maxpt_j1_phi_jes_up,"vbf_maxpt_j1_phi_jes_up/F");
  fTree->Branch("vbf_maxpt_j1_phi_jes_dn",&vbf_maxpt_j1_phi_jes_dn,"vbf_maxpt_j1_phi_jes_dn/F");
  fTree->Branch("vbf_maxpt_j1_e",&vbf_maxpt_j1_e,"vbf_maxpt_j1_e/F");
  fTree->Branch("vbf_maxpt_j1_mass",&vbf_maxpt_j1_mass,"vbf_maxpt_j1_mass/F");
  fTree->Branch("vbf_maxpt_j1_mass_jes_up",&vbf_maxpt_j1_mass_jes_up,"vbf_maxpt_j1_mass_jes_up/F");
  fTree->Branch("vbf_maxpt_j1_mass_jes_dn",&vbf_maxpt_j1_mass_jes_dn,"vbf_maxpt_j1_mass_jes_dn/F");
  fTree->Branch("vbf_maxpt_j1_bDiscriminatorCSV",&vbf_maxpt_j1_bDiscriminatorCSV,"vbf_maxpt_j1_bDiscriminatorCSV/F");
  fTree->Branch("vbf_maxpt_j1_charge",&vbf_maxpt_j1_charge,"vbf_maxpt_j1_charge/F");
  fTree->Branch("vbf_maxpt_j2_pt",&vbf_maxpt_j2_pt,"vbf_maxpt_j2_pt/F");
  fTree->Branch("vbf_maxpt_j2_pt_jes_up",&vbf_maxpt_j2_pt_jes_up,"vbf_maxpt_j2_pt_jes_up/F");
  fTree->Branch("vbf_maxpt_j2_pt_jes_dn",&vbf_maxpt_j2_pt_jes_dn,"vbf_maxpt_j2_pt_jes_dn/F");
  fTree->Branch("vbf_maxpt_j2_pt_jer",&vbf_maxpt_j2_pt_jer,"vbf_maxpt_j2_pt_jer/F");
  fTree->Branch("vbf_maxpt_j2_pt_jer_up",&vbf_maxpt_j2_pt_jer_up,"vbf_maxpt_j2_pt_jer_up/F");
  fTree->Branch("vbf_maxpt_j2_pt_jer_dn",&vbf_maxpt_j2_pt_jer_dn,"vbf_maxpt_j2_pt_jer_dn/F");
  fTree->Branch("vbf_maxpt_j2_eta",&vbf_maxpt_j2_eta,"vbf_maxpt_j2_eta/F");
  fTree->Branch("vbf_maxpt_j2_eta_jes_up",&vbf_maxpt_j2_eta_jes_up,"vbf_maxpt_j2_eta_jes_up/F");
  fTree->Branch("vbf_maxpt_j2_eta_jes_dn",&vbf_maxpt_j2_eta_jes_dn,"vbf_maxpt_j2_eta_jes_dn/F");
  fTree->Branch("vbf_maxpt_j2_eta_jer",&vbf_maxpt_j2_eta_jer,"vbf_maxpt_j2_eta_jer/F");
  fTree->Branch("vbf_maxpt_j2_eta_jer_up",&vbf_maxpt_j2_eta_jer_up,"vbf_maxpt_j2_eta_jer_up/F");
  fTree->Branch("vbf_maxpt_j2_eta_jer_dn",&vbf_maxpt_j2_eta_jer_dn,"vbf_maxpt_j2_eta_jer_dn/F");
  fTree->Branch("vbf_maxpt_j2_phi",&vbf_maxpt_j2_phi,"vbf_maxpt_j2_phi/F");
  fTree->Branch("vbf_maxpt_j2_phi_jes_up",&vbf_maxpt_j2_phi_jes_up,"vbf_maxpt_j2_phi_jes_up/F");
  fTree->Branch("vbf_maxpt_j2_phi_jes_dn",&vbf_maxpt_j2_phi_jes_dn,"vbf_maxpt_j2_phi_jes_dn/F");
  fTree->Branch("vbf_maxpt_j2_e",&vbf_maxpt_j2_e,"vbf_maxpt_j2_e/F");
  fTree->Branch("vbf_maxpt_j2_mass",&vbf_maxpt_j2_mass,"vbf_maxpt_j2_mass/F");
  fTree->Branch("vbf_maxpt_j2_mass_jes_up",&vbf_maxpt_j2_mass_jes_up,"vbf_maxpt_j2_mass_jes_up/F");
  fTree->Branch("vbf_maxpt_j2_mass_jes_dn",&vbf_maxpt_j2_mass_jes_dn,"vbf_maxpt_j2_mass_jes_dn/F");
  fTree->Branch("vbf_maxpt_j2_bDiscriminatorCSV",&vbf_maxpt_j2_bDiscriminatorCSV,"vbf_maxpt_j2_bDiscriminatorCSV/F");
  fTree->Branch("vbf_maxpt_j2_charge",&vbf_maxpt_j2_charge,"vbf_maxpt_j2_charge/F");
  fTree->Branch("vbfPuppi_maxpt_j1_ID",&vbfPuppi_maxpt_j1_ID,"vbfPuppi_maxpt_j1_ID/F");
  fTree->Branch("vbfPuppi_maxpt_j2_ID",&vbfPuppi_maxpt_j2_ID,"vbfPuppi_maxpt_j2_ID/F");
  fTree->Branch("vbf_maxpt_jj_pt",&vbf_maxpt_jj_pt,"vbf_maxpt_jj_pt/F");
  fTree->Branch("vbf_maxpt_jj_pt_jes_up",&vbf_maxpt_jj_pt_jes_up,"vbf_maxpt_jj_pt_jes_up/F");
  fTree->Branch("vbf_maxpt_jj_pt_jes_dn",&vbf_maxpt_jj_pt_jes_dn,"vbf_maxpt_jj_pt_jes_dn/F");
  fTree->Branch("vbf_maxpt_jj_eta",&vbf_maxpt_jj_eta,"vbf_maxpt_jj_eta/F");
  fTree->Branch("vbf_maxpt_jj_phi",&vbf_maxpt_jj_phi,"vbf_maxpt_jj_phi/F");
  fTree->Branch("vbf_maxpt_jj_m",&vbf_maxpt_jj_m,"vbf_maxpt_jj_m/F");
  fTree->Branch("vbf_maxpt_jj_m_jes_up",&vbf_maxpt_jj_m_jes_up,"vbf_maxpt_jj_m_jes_up/F");
  fTree->Branch("vbf_maxpt_jj_m_jes_dn",&vbf_maxpt_jj_m_jes_dn,"vbf_maxpt_jj_m_jes_dn/F");
  fTree->Branch("vbf_maxpt_jj_Deta",&vbf_maxpt_jj_Deta,"vbf_maxpt_jj_Deta/F");
  fTree->Branch("vbf_maxpt_jj_Deta_jes_up",&vbf_maxpt_jj_Deta_jes_up,"vbf_maxpt_jj_Deta_jes_up/F");
  fTree->Branch("vbf_maxpt_jj_Deta_jes_dn",&vbf_maxpt_jj_Deta_jes_dn,"vbf_maxpt_jj_Deta_jes_dn/F");
  fTree->Branch("vbf_maxpt_deltaR",&vbf_maxpt_deltaR,"vbf_maxpt_deltaR/F");
  fTree->Branch("deltaphi_METvbfJ1",&deltaphi_METvbfJ1,"deltaphi_METvbfJ1/F");
  fTree->Branch("deltaphi_METvbfJ2",&deltaphi_METvbfJ2,"deltaphi_METvbfJ2/F");
  fTree->Branch("deltaphi_METmin",&deltaphi_METmin,"deltaphi_METmin/F");
  fTree->Branch("vbfPuppi_maxpt_j1_pt",&vbfPuppi_maxpt_j1_pt,"vbfPuppi_maxpt_j1_pt/F");
  fTree->Branch("vbfPuppi_maxpt_j1_pt_jes_up",&vbfPuppi_maxpt_j1_pt_jes_up,"vbfPuppi_maxpt_j1_pt_jes_up/F");
  fTree->Branch("vbfPuppi_maxpt_j1_pt_jes_dn",&vbfPuppi_maxpt_j1_pt_jes_dn,"vbfPuppi_maxpt_j1_pt_jes_dn/F");
  fTree->Branch("vbfPuppi_maxpt_j1_pt_jer",&vbfPuppi_maxpt_j1_pt_jer,"vbfPuppi_maxpt_j1_pt_jer/F");
  fTree->Branch("vbfPuppi_maxpt_j1_pt_jer_up",&vbfPuppi_maxpt_j1_pt_jer_up,"vbfPuppi_maxpt_j1_pt_jer_up/F");
  fTree->Branch("vbfPuppi_maxpt_j1_pt_jer_dn",&vbfPuppi_maxpt_j1_pt_jer_dn,"vbfPuppi_maxpt_j1_pt_jer_dn/F");
  fTree->Branch("vbfPuppi_maxpt_j1_eta",&vbfPuppi_maxpt_j1_eta,"vbfPuppi_maxpt_j1_eta/F");
  fTree->Branch("vbfPuppi_maxpt_j1_eta_jes_up",&vbfPuppi_maxpt_j1_eta_jes_up,"vbfPuppi_maxpt_j1_eta_jes_up/F");
  fTree->Branch("vbfPuppi_maxpt_j1_eta_jes_dn",&vbfPuppi_maxpt_j1_eta_jes_dn,"vbfPuppi_maxpt_j1_eta_jes_dn/F");
  fTree->Branch("vbfPuppi_maxpt_j1_eta_jer",&vbfPuppi_maxpt_j1_eta_jer,"vbfPuppi_maxpt_j1_eta_jer/F");
  fTree->Branch("vbfPuppi_maxpt_j1_eta_jer_up",&vbfPuppi_maxpt_j1_eta_jer_up,"vbfPuppi_maxpt_j1_eta_jer_up/F");
  fTree->Branch("vbfPuppi_maxpt_j1_eta_jer_dn",&vbfPuppi_maxpt_j1_eta_jer_dn,"vbfPuppi_maxpt_j1_eta_jer_dn/F");
  fTree->Branch("vbfPuppi_maxpt_j1_phi",&vbfPuppi_maxpt_j1_phi,"vbfPuppi_maxpt_j1_phi/F");
  fTree->Branch("vbfPuppi_maxpt_j1_e",&vbfPuppi_maxpt_j1_e,"vbfPuppi_maxpt_j1_e/F");
  fTree->Branch("vbfPuppi_maxpt_j1_bDiscriminatorCSV",&vbfPuppi_maxpt_j1_bDiscriminatorCSV,"vbfPuppi_maxpt_j1_bDiscriminatorCSV/F");
  fTree->Branch("vbfPuppi_maxpt_j2_pt",&vbfPuppi_maxpt_j2_pt,"vbfPuppi_maxpt_j2_pt/F");
  fTree->Branch("vbfPuppi_maxpt_j2_pt_jes_up",&vbfPuppi_maxpt_j2_pt_jes_up,"vbfPuppi_maxpt_j2_pt_jes_up/F");
  fTree->Branch("vbfPuppi_maxpt_j2_pt_jes_dn",&vbfPuppi_maxpt_j2_pt_jes_dn,"vbfPuppi_maxpt_j2_pt_jes_dn/F");
  fTree->Branch("vbfPuppi_maxpt_j2_pt_jer",&vbfPuppi_maxpt_j2_pt_jer,"vbfPuppi_maxpt_j2_pt_jer/F");
  fTree->Branch("vbfPuppi_maxpt_j2_pt_jer_up",&vbfPuppi_maxpt_j2_pt_jer_up,"vbfPuppi_maxpt_j2_pt_jer_up/F");
  fTree->Branch("vbfPuppi_maxpt_j2_pt_jer_dn",&vbfPuppi_maxpt_j2_pt_jer_dn,"vbfPuppi_maxpt_j2_pt_jer_dn/F");
  fTree->Branch("vbfPuppi_maxpt_j2_eta",&vbfPuppi_maxpt_j2_eta,"vbfPuppi_maxpt_j2_eta/F");
  fTree->Branch("vbfPuppi_maxpt_j2_eta_jes_up",&vbfPuppi_maxpt_j2_eta_jes_up,"vbfPuppi_maxpt_j2_eta_jes_up/F");
  fTree->Branch("vbfPuppi_maxpt_j2_eta_jes_dn",&vbfPuppi_maxpt_j2_eta_jes_dn,"vbfPuppi_maxpt_j2_eta_jes_dn/F");
  fTree->Branch("vbfPuppi_maxpt_j2_eta_jer",&vbfPuppi_maxpt_j2_eta_jer,"vbfPuppi_maxpt_j2_eta_jer/F");
  fTree->Branch("vbfPuppi_maxpt_j2_eta_jer_up",&vbfPuppi_maxpt_j2_eta_jer_up,"vbfPuppi_maxpt_j2_eta_jer_up/F");
  fTree->Branch("vbfPuppi_maxpt_j2_eta_jer_dn",&vbfPuppi_maxpt_j2_eta_jer_dn,"vbfPuppi_maxpt_j2_eta_jer_dn/F");
  fTree->Branch("vbfPuppi_maxpt_j2_phi",&vbfPuppi_maxpt_j2_phi,"vbfPuppi_maxpt_j2_phi/F");
  fTree->Branch("vbfPuppi_maxpt_j2_e",&vbfPuppi_maxpt_j2_e,"vbfPuppi_maxpt_j2_e/F");
  fTree->Branch("vbfPuppi_maxpt_j2_bDiscriminatorCSV",&vbfPuppi_maxpt_j2_bDiscriminatorCSV,"vbfPuppi_maxpt_j2_bDiscriminatorCSV/F");
  fTree->Branch("vbfPuppi_maxpt_jj_pt",&vbfPuppi_maxpt_jj_pt,"vbfPuppi_maxpt_jj_pt/F");
  fTree->Branch("vbfPuppi_maxpt_jj_eta",&vbfPuppi_maxpt_jj_eta,"vbfPuppi_maxpt_jj_eta/F");
  fTree->Branch("vbfPuppi_maxpt_jj_phi",&vbfPuppi_maxpt_jj_phi,"vbfPuppi_maxpt_jj_phi/F");
  fTree->Branch("vbfPuppi_maxpt_jj_m",&vbfPuppi_maxpt_jj_m,"vbfPuppi_maxpt_jj_m/F");
  fTree->Branch("vbfPuppi_maxpt_jj_Deta",&vbfPuppi_maxpt_jj_Deta,"vbfPuppi_maxpt_jj_Deta/F");
  fTree->Branch("vbfPuppi_maxpt_deltaR",&vbfPuppi_maxpt_deltaR,"vbfPuppi_maxpt_deltaR/F");
  fTree->Branch("jet2_pt",&jet2_pt,"jet2_pt/F");
  fTree->Branch("jet2_eta",&jet2_eta,"jet2_eta/F");
  fTree->Branch("jet2_phi",&jet2_phi,"jet2_phi/F");
  fTree->Branch("jet2_e",&jet2_e,"jet2_e/F");
  fTree->Branch("jet2_btag",&jet2_btag,"jet2_btag/F");
  fTree->Branch("jet3_pt",&jet3_pt,"jet3_pt/F");
  fTree->Branch("jet3_eta",&jet3_eta,"jet3_eta/F");
  fTree->Branch("jet3_phi",&jet3_phi,"jet3_phi/F");
  fTree->Branch("jet3_e",&jet3_e,"jet3_e/F");
  fTree->Branch("jet3_btag",&jet3_btag,"jet3_btag/F");
  fTree->Branch("deltaR_AK8_closestBtagJet",&deltaR_AK8_closestBtagJet,"deltaR_AK8_closestBtagJet/F");
  fTree->Branch("deltaR_AK8_closestBtagJet_loose",&deltaR_AK8_closestBtagJet_loose,"deltaR_AK8_closestBtagJet_loose/F");
  fTree->Branch("LepWEta", &LepWEta , "LepWEta/F");
  fTree->Branch("LepWRapidity", &LepWRapidity , "LepWRapidity/F");
  fTree->Branch("HadWEta", &HadWEta , "HadWEta/F");
  fTree->Branch("HadWRapidity", &HadWRapidity , "HadWRapidity/F");
  fTree->Branch("WWEta", &WWEta , "WWEta/F");
  fTree->Branch("WWRapidity", &WWRapidity , "WWRapidity/F");
  fTree->Branch("ZeppenfeldWH", &ZeppenfeldWH , "ZeppenfeldWH/F");
fTree->Branch("ZeppenfeldWH_jes_up", &ZeppenfeldWH_jes_up, "ZeppenfeldWH_jes_up/F");
fTree->Branch("ZeppenfeldWH_jes_dn", &ZeppenfeldWH_jes_dn, "ZeppenfeldWH_jes_dn/F");
  fTree->Branch("ZeppenfeldWHPuppi", &ZeppenfeldWHPuppi , "ZeppenfeldWHPuppi/F");
  ////
  fTree->Branch("costheta1Puppi_type0",&costheta1Puppi_type0 ,"costheta1Puppi_type0/F");
  fTree->Branch("costheta2Puppi_type0",&costheta2Puppi_type0 ,"costheta2Puppi_type0/F");
  fTree->Branch("costhetastarPuppi_type0",&costhetastarPuppi_type0 ,"costhetastarPuppi_type0/F");
  fTree->Branch("phiPuppi_type0",&phiPuppi_type0 ,"phiPuppi_type0/F");
  fTree->Branch("phi1Puppi_type0",&phi1Puppi_type0 ,"phi1Puppi_type0/F");
  fTree->Branch("VBSCentralityPuppi_type0",&VBSCentralityPuppi_type0 ,"VBSCentralityPuppi_type0/F");
  fTree->Branch("costheta1Puppi_type2",&costheta1Puppi_type2 ,"costheta1Puppi_type2/F");
  fTree->Branch("costheta2Puppi_type2",&costheta2Puppi_type2 ,"costheta2Puppi_type2/F");
  fTree->Branch("costhetastarPuppi_type2",&costhetastarPuppi_type2 ,"costhetastarPuppi_type2/F");
  fTree->Branch("phiPuppi_type2",&phiPuppi_type2 ,"phiPuppi_type2/F");
  fTree->Branch("phi1Puppi_type2",&phi1Puppi_type2 ,"phi1Puppi_type2/F");
  fTree->Branch("VBSCentralityPuppi_type2",&VBSCentralityPuppi_type2 ,"VBSCentralityPuppi_type2/F");
  fTree->Branch("costheta1Puppi_run2",&costheta1Puppi_run2 ,"costheta1Puppi_run2/F");
  fTree->Branch("costheta2Puppi_run2",&costheta2Puppi_run2 ,"costheta2Puppi_run2/F");
  fTree->Branch("costhetastarPuppi_run2",&costhetastarPuppi_run2 ,"costhetastarPuppi_run2/F");
  fTree->Branch("phiPuppi_run2",&phiPuppi_run2 ,"phiPuppi_run2/F");
  fTree->Branch("phi1Puppi_run2",&phi1Puppi_run2 ,"phi1Puppi_run2/F");
  fTree->Branch("VBSCentralityPuppi_run2",&VBSCentralityPuppi_run2 ,"VBSCentralityPuppi_run2/F");
  fTree->Branch("RpTPuppi_type0", &RpTPuppi_type0 , "RpTPuppi_type0/F");
  fTree->Branch("ZeppenfeldWLPuppi_type0", &ZeppenfeldWLPuppi_type0 , "ZeppenfeldWLPuppi_type0/F");
  fTree->Branch("LeptonProjectionPuppi_type0", &LeptonProjectionPuppi_type0 , "LeptonProjectionPuppi_type0/F");
  fTree->Branch("RpTPuppi_type2", &RpTPuppi_type2 , "RpTPuppi_type2/F");
  fTree->Branch("ZeppenfeldWLPuppi_type2", &ZeppenfeldWLPuppi_type2 , "ZeppenfeldWLPuppi_type2/F");
  fTree->Branch("LeptonProjectionPuppi_type2", &LeptonProjectionPuppi_type2 , "LeptonProjectionPuppi_type2/F");
  fTree->Branch("RpTPuppi_run2", &RpTPuppi_run2 , "RpTPuppi_run2/F");
  fTree->Branch("ZeppenfeldWLPuppi_run2", &ZeppenfeldWLPuppi_run2 , "ZeppenfeldWLPuppi_run2/F");
  fTree->Branch("LeptonProjectionPuppi_run2", &LeptonProjectionPuppi_run2 , "LeptonProjectionPuppi_run2/F");
  fTree->Branch("PtBalancePuppi_type0", &PtBalancePuppi_type0 , "PtBalancePuppi_type0/F");
  fTree->Branch("PtBalancePuppi_type2", &PtBalancePuppi_type2 , "PtBalancePuppi_type2/F");
  fTree->Branch("PtBalancePuppi_run2", &PtBalancePuppi_run2 , "PtBalancePuppi_run2/F");
  ///
  fTree->Branch("costheta1_type0",&costheta1_type0 ,"costheta1_type0/F");
  fTree->Branch("costheta2_type0",&costheta2_type0 ,"costheta2_type0/F");
  fTree->Branch("costhetastar_type0",&costhetastar_type0 ,"costhetastar_type0/F");
  fTree->Branch("phi_type0",&phi_type0 ,"phi_type0/F");
  fTree->Branch("phi1_type0",&phi1_type0 ,"phi1_type0/F");
  fTree->Branch("VBSCentrality_type0",&VBSCentrality_type0 ,"VBSCentrality_type0/F");
  fTree->Branch("costheta1_type2",&costheta1_type2 ,"costheta1_type2/F");
  fTree->Branch("costheta2_type2",&costheta2_type2 ,"costheta2_type2/F");
  fTree->Branch("costhetastar_type2",&costhetastar_type2 ,"costhetastar_type2/F");
  fTree->Branch("phi_type2",&phi_type2 ,"phi_type2/F");
  fTree->Branch("phi1_type2",&phi1_type2 ,"phi1_type2/F");
  fTree->Branch("VBSCentrality_type2",&VBSCentrality_type2 ,"VBSCentrality_type2/F");
  fTree->Branch("costheta1_run2",&costheta1_run2 ,"costheta1_run2/F");
  fTree->Branch("costheta2_run2",&costheta2_run2 ,"costheta2_run2/F");
  fTree->Branch("costhetastar_run2",&costhetastar_run2 ,"costhetastar_run2/F");
  fTree->Branch("phi_run2",&phi_run2 ,"phi_run2/F");
  fTree->Branch("phi1_run2",&phi1_run2 ,"phi1_run2/F");
  fTree->Branch("VBSCentrality_run2",&VBSCentrality_run2 ,"VBSCentrality_run2/F");
  fTree->Branch("RpT_type0", &RpT_type0 , "RpT_type0/F");
  fTree->Branch("ZeppenfeldWL_type0", &ZeppenfeldWL_type0 , "ZeppenfeldWL_type0/F");
fTree->Branch("ZeppenfeldWL_type0_jes_up", &ZeppenfeldWL_type0_jes_up, "ZeppenfeldWL_type0_jes_up/F");
fTree->Branch("ZeppenfeldWL_type0_jes_dn", &ZeppenfeldWL_type0_jes_dn, "ZeppenfeldWL_type0_jes_dn/F");
fTree->Branch("ZeppenfeldWL_type0_jer_up", &ZeppenfeldWL_type0_jer_up, "ZeppenfeldWL_type0_jer_up/F");
fTree->Branch("ZeppenfeldWL_type0_jer_dn", &ZeppenfeldWL_type0_jer_dn, "ZeppenfeldWL_type0_jer_dn/F");
  fTree->Branch("LeptonProjection_type0", &LeptonProjection_type0 , "LeptonProjection_type0/F");
  fTree->Branch("RpT_type2", &RpT_type2 , "RpT_type2/F");
  fTree->Branch("ZeppenfeldWL_type2", &ZeppenfeldWL_type2 , "ZeppenfeldWL_type2/F");
  fTree->Branch("LeptonProjection_type2", &LeptonProjection_type2 , "LeptonProjection_type2/F");
  fTree->Branch("RpT_run2", &RpT_run2 , "RpT_run2/F");
  fTree->Branch("ZeppenfeldWL_run2", &ZeppenfeldWL_run2 , "ZeppenfeldWL_run2/F");
  fTree->Branch("LeptonProjection_run2", &LeptonProjection_run2 , "LeptonProjection_run2/F");
  fTree->Branch("PtBalance_type0", &PtBalance_type0 , "PtBalance_type0/F");
fTree->Branch("PtBalance_type0_jes_up", &PtBalance_type0_jes_up, "PtBalance_type0_jes_up/F");
fTree->Branch("PtBalance_type0_jes_dn", &PtBalance_type0_jes_dn, "PtBalance_type0_jes_dn/F");
fTree->Branch("PtBalance_type0_jer_up", &PtBalance_type0_jer_up, "PtBalance_type0_jer_up/F");
fTree->Branch("PtBalance_type0_jer_dn", &PtBalance_type0_jer_dn, "PtBalance_type0_jer_dn/F");
  fTree->Branch("PtBalance_type2", &PtBalance_type2 , "PtBalance_type2/F");
  fTree->Branch("PtBalance_run2", &PtBalance_run2 , "PtBalance_run2/F");
  ////
  fTree->Branch("BosonCentrality_type0", &BosonCentrality_type0 , "BosonCentrality_type0/F");
fTree->Branch("BosonCentrality_type0_jes_up", &BosonCentrality_type0_jes_up, "BosonCentrality_type0_jes_up/F");
fTree->Branch("BosonCentrality_type0_jes_dn", &BosonCentrality_type0_jes_dn, "BosonCentrality_type0_jes_dn/F");
fTree->Branch("BosonCentrality_type0_jer_up", &BosonCentrality_type0_jer_up, "BosonCentrality_type0_jer_up/F");
fTree->Branch("BosonCentrality_type0_jer_dn", &BosonCentrality_type0_jer_dn, "BosonCentrality_type0_jer_dn/F");
  fTree->Branch("BosonCentrality_type2", &BosonCentrality_type2 , "BosonCentrality_type2/F");
  fTree->Branch("BosonCentrality_run2", &BosonCentrality_run2 , "BosonCentrality_run2/F");
  fTree->Branch("BosonCentralityPuppi_type0", &BosonCentralityPuppi_type0 , "BosonCentralityPuppi_type0/F");
  fTree->Branch("BosonCentralityPuppi_type2", &BosonCentralityPuppi_type2 , "BosonCentralityPuppi_type2/F");
  fTree->Branch("BosonCentralityPuppi_run2", &BosonCentralityPuppi_run2 , "BosonCentralityPuppi_run2/F");

  fTree->Branch("PtBalance_2Lep",&PtBalance_2Lep,"PtBalance_2Lep/F");
  fTree->Branch("BosonCentrality_2Lep",&BosonCentrality_2Lep,"BosonCentrality_2Lep/F");
fTree->Branch("BosonCentrality_2Lep_jes_up", &BosonCentrality_2Lep_jes_up, "BosonCentrality_2Lep_jes_up/F");
fTree->Branch("BosonCentrality_2Lep_jes_dn", &BosonCentrality_2Lep_jes_dn, "BosonCentrality_2Lep_jes_dn/F");
  fTree->Branch("costheta1_2Lep",&costheta1_2Lep,"costheta1_2Lep/F");
  fTree->Branch("costheta2_2Lep",&costheta2_2Lep,"costheta2_2Lep/F");
  fTree->Branch("costhetastar_2Lep",&costhetastar_2Lep,"costhetastar_2Lep/F");
  fTree->Branch("phi_2Lep",&phi_2Lep,"phi_2Lep/F");
  fTree->Branch("phi1_2Lep",&phi1_2Lep,"phi1_2Lep/F");
  fTree->Branch("VBSCentrality_2Lep",&VBSCentrality_2Lep,"VBSCentrality_2Lep/F");
  fTree->Branch("RpT_2Lep",&RpT_2Lep,"RpT_2Lep/F");
  fTree->Branch("ZeppenfeldWL_2Lep",&ZeppenfeldWL_2Lep,"ZeppenfeldWL_2Lep/F");
fTree->Branch("ZeppenfeldWL_2Lep_jes_up", &ZeppenfeldWL_2Lep_jes_up, "ZeppenfeldWL_2Lep_jes_up/F");
fTree->Branch("ZeppenfeldWL_2Lep_jes_dn", &ZeppenfeldWL_2Lep_jes_dn, "ZeppenfeldWL_2Lep_jes_dn/F");
  fTree->Branch("LeptonProjection_2Lep",&LeptonProjection_2Lep,"LeptonProjection_2Lep/F");
  //fTree->Branch("", & , "/F");

//  fTree->Branch("deltaR_AK4",&deltaR_AK4,"deltaR_AK4/F");
}
